### ISSUE TITLE
Mo2 doesn't detect steam anymore

### ISSUE THREAD

**Issue by mlysle** [sonic2kk/steamtinkerlaunch#586] opened 2022-09-16 20:47 UTC
My first experience with STL was very good, I had a small little modlist ready. Then I somehow managed to break Mo2. I am experiencing two problems:

1. Launching Skyrim from MO2 greets me with a message about Steam not being detected. I can play the game but presumably without Steam integration, which I want.
2. Mo2 is glitched graphically. Specifically, the plugin checkboxes are not visible.

I have tried a complete reinstallation (nuking STL, Skyrim, prefixes, etc) and I still run into this issue.

I have also tried launching Mo2 in the different modes to no success.

**Comment by sonic2kk** [comment] 2022-09-16 22:24
Hello! 

Can you provide some logging information? Try to launch your game again, then open MO2, and try to play. Your log can be found in a few places but the most convenient is probably `/dev/shm/steamtinkerlaunch`.

Also, how are you launching your game via MO2? Are you doing it in Game Mode (an additional wait requester pops up when you click "play") or Standalone Mode (from the menu button in STL's Main Menu).

Did MO2 work previously? I think that's what I'm getting from your post but I just want to confirm. I'll try my New Vegas installation in a bit once I'm at my PC to see if MO2 is working for me or if perhaps it broke with an update (hopefully not!)

Finally, what version of STL are you using, how did you install it, and what distro are you using?

Thank you 😃

**Comment by sonic2kk** [comment] 2022-09-16 22:52
Hm, I just tested my New Vegas modded installation and it seems to work fine. I'm using the latest STL Git with MO2 v2.4.4. Whenever you're able please provide more information to help debug further :)

**Comment by mlysle** [comment] 2022-09-17 21:58
I have managed to workaround the issues. The graphical bugs went away when I switched to the Fusion MO2 theme. As for Steam connectivity, I now launch using the Steam Collection method and not through the MO2 Extra Button.

I can't explain why it would have would have caused it to break in the first place, but I see now that I wasn't launching it in the recommended way to begin with.

**Comment by sonic2kk** [comment] 2022-09-17 22:46
> The graphical bugs went away when I switched to the Fusion MO2 theme. As for Steam connectivity, I now launch using the Steam Collection method and not through the MO2 Extra Button.

Hmm, this is interesting. I am using the Paper theme I think it is called with MO2, but indeed there could be an issue with MO2 and the default theme. This isn't really a problem with SteamTinkerLaunch but more a problem with Proton and MO2 (specifically how Proton/Wine manages rendering the MO2 UI).

Which version of Proton are you launching your game with? Maybe there was a regression in a newer version or a problem with an older version. You can see which version of Proton STL is launching games with in the Game Menu under the Proton settings.

**Comment by sonic2kk** [comment] 2022-09-17 22:57
Checkboxes with the default theme using Proton 7.0-4 seem to be displaying fine on my side:

![image](https://user-images.githubusercontent.com/7917345/190878793-39907c74-feb5-47aa-8592-9aedcccf2f1b.png)

I believe GE-Proton uses a different theme, which could be causing some issues. I don't want to change the version of Proton I'm using for my mods (New Vegas is touchy as is even on Windows :sweat_smile:) so I can't really test this

<details>
<summary>How to fix if you're using GE-Proton or another similar community flavour.</summary>
If you are using GE-Proton, all is not lost. You can change the theme that GE-Proton uses (and Proton-tkg as well). To do this, SteamTinkerLaunch has your back here. Go to the Game Menu, scroll down to "Wine options" and check the box that says "winecfg". Then click save and play. A window will open up that looks like this (it may have a slightly different theme if you're using GE-Proton):

![image](https://user-images.githubusercontent.com/7917345/190878882-c80be398-5f06-45ea-9bf2-2a3ee35d7b71.png)

You'll want to click on the "Desktop Integration" tab and click on the "Theme" dropdown. Change this to "No theme"

![image](https://user-images.githubusercontent.com/7917345/190878908-0d3f6415-c20a-4c22-b615-4bcc0a3c5708.png)

Click the "Apply" button in the bottom right, then press "OK" and the MO2 wait requester window will open up, allowing you to open MO2. Remember to disable this checkbox next time you run the game, otherwise winecfg will open before you launch your game every time :smile: 
</details>

**Comment by sonic2kk** [comment] 2022-09-20 21:04
@mlysle Did any of the steps outlined help you resolve this issue, or are you still having trouble? :slightly_smiling_face:

**Comment by mlysle** [comment] 2022-09-24 02:58
Changing the theme worked. It was set to "light". Setting it to (No theme) fixes my graphical issues.

**Comment by sonic2kk** [comment] 2022-09-24 03:05
Glad to hear it! This is probably a problem with Wine's mono implementation and how it works with DotNet applications, or to be more precise, how it does not.

Also, as for your initial issue of MO2 not detecting Steam, make sure you run your games with MO2 in Game Mode (when you get prompted for "GUI" mode). If you use the Extra Button in the Main Menu this launches MO2 in Standalone Mode. This may also cause issues when trying to use the Nexus Mods "Mod Manager" button. So if you use the Extra Button on the Main Menu, you won't be able to download from Nexus Mods or launch your games, but you can do this if you press "Play" from SteamTinkerLaunch.

There is currently an open issue (#598) discussing potential overhauls of STL's MO2 integration. Feel free to keep an eye on this and voice any experiences you have with MO2 :smile: 

Going to close this issue now as all the issues should be resolved. Please re-open if you feel there are any further issues. Thank you! :smiley:

**Closed as completed by sonic2kk** 2022-09-24 03:05 UTC
Labels: bug, ModOrganizer 2
