### ISSUE TITLE
Problems installing through Flatpak

### ISSUE THREAD

**Issue by locrianz** [sonic2kk/steamtinkerlaunch#1085] opened 2024-04-18 17:14 UTC
## System Information
- SteamTinkerLaunch version: 14.0.20240218-1
- Distribution: Linux Mint
- Installation Method: Flatpak

## Issue Description
I've installed both Steam and Steamtinkerlaunch through Flatpak:
![Screenshot from 2024-04-18 12-09-49](https://github.com/sonic2kk/steamtinkerlaunch/assets/152659636/ebf32017-7dd8-4f02-8cf6-94da5d6b83bf)

But Steamtinkerlaunch does not appear in Steam's list of compatability tools. Also, running the command `steamtinkerlaunch help` in the terminal just returns the error `steamtinkerlaunch: command not found`.

## Logs
The folder `/dev/shm/steamtinkerlaunch/` doesn't exist, so I have no logs.

**Comment by sonic2kk** [comment] 2024-04-18 20:58
It seems you did not check the Flatpak repo to see that this issue is already being tracked: https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110

It has also come up here before and has been closed for this reason. Please search closed issues before opening duplicates. You can also search by label, which is how I found the list of below issues (there may be times when I forget to label, but I do my best to make it easier for myself and especially others to search).

Duplicate of:
- #1066 
- #1043

**Closed as completed by sonic2kk** 2024-04-18 20:58 UTC
Labels: bug, duplicate, Flatpak

**Comment by sonic2kk** [comment] 2024-04-19 02:37
Also, I don't think you can Flatpak commands like this: `steamtinkerlaunch help` - You probably have to do something like `com.valvesoftware.Steam.Utility.steamtinkerlaunch --command="steamtinkerlaunch help"` or something to this effect.

This isn't specific to SteamTinkerLaunch, I don't think Flatpaks can be used from the commandline like this. I don't use or maintain the Flatpak, so I can't help too much with usage on those lines.

Also, just as an fyi in case the documentation wasn't clear, you don't *have* to use Flatpak Steam. SteamTinkerLaunch works fine with the official Steam Client, that's what most people use I think too. I get the feeling sometimes people install Flatpak Steam just to use SteamTinkerLaunch, when the official client works just as fine. The Flatpak was made at the request of Steam Flatpak users and for those users, it's not there to force anyone to use Flatpak Steam.
