### ISSUE TITLE
'Depends' field, missing package name, or garbage where package name expected

### ISSUE THREAD

**Issue by RawPorkSushi** [sonic2kk/steamtinkerlaunch#966] opened 2023-11-04 02:42 UTC
## System Information
- SteamTinkerLaunch version:  unclear; attempt via pacstall
- Distribution:  Pop_OS (Ubuntu 22.04.3 LTS)
- Installation Method:  via pacstall using this guide:  [https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#distro-specific](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation#distro-specific)

## Issue Description
Simply following the instructions to install SteamTinkerLaunch via Pacstall on my System76 laptop.  After resolving an unrelated issue with system76-power, and completing an update/upgrade, the system was running normally and smoothly.  I then successfully installed Pacstall via .deb file using dpkg -i which completed properly.  I then used pacstall to attempt installation of SteamTinkerLaunch as prescribed in the above directions.  When prompted to choose Optional Dependencies, I chose 'Y' in order to install them all (why not, lets just be thorough, right?).  Everything seemed to progress as expected, until it exited with the following error message:

`After this operation, 1911 kB of additional disk space will be used.
Get:1 /usr/src/pacstall/steamtinkerlaunch-git.deb steamtinkerlaunch all 12.12-pacstall1~git64c80557 [592 kB]
dpkg: error processing archive /usr/src/pacstall/steamtinkerlaunch-git.deb (--unpack):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 2:
 'Depends' field, missing package name, or garbage where package name expected
Errors were encountered while processing:
 /usr/src/pacstall/steamtinkerlaunch-git.deb
	[!] ERROR: Failed to install steamtinkerlaunch-git deb
dpkg: warning: ignoring request to remove steamtinkerlaunch-git which isn't installed
[+] INFO: Cleaning up
`
Best regards,
Mike

**Comment by sonic2kk** [comment] 2023-11-04 03:14
Pacstall installs SteamTinkerLaunch from the latest git release :-) No worries there about the version. However, I sadly don't think I can help you much:

>  Everything seemed to progress as expected, until it exited with the following error message:

If I understand right, installation exited, and you could not run SteamTinkerLaunch. Is this correct? If so, this sounds like something that should be brought up to Pacstall, as I don't maintain the Pacstall package.

I did take a quick look at the Pacstall package. I have very little experience on this front, but it looks like the [dependencies section for SteamTinkerLaunch-git](https://github.com/pacstall/pacstall-programs/blob/master/packages/steamtinkerlaunch-git/steamtinkerlaunch-git.pacscript#L4) is correct (it isn't complete, but I assume Ubuntu comes with the rest).

The main thing that stands out to me is `parsing file '/var/lib/dpkg/tmp.ci/control' near line 2: 'Depends' field, missing package name, or garbage where package name expected`, which seems like Pacstall is having troubles with parsing this file which is then causing SteamTinkerLaunch to fail. I am not sure what this part is referring to, but it would probably be worth reporting this upstream to Pacstall, as I think it is unrelated to the core SteamTinkerLaunch project.

I haven't used the Pacstall package before, I recall there have been issues in the past but I think they were all on Ubuntu's site and were resolved further upstream than Pacstall.

Good luck!

**Comment by sonic2kk** [comment] 2023-11-04 03:17
I did a quick search and on Ubuntu, it seems the `/var/lib/dpkg/tmp.ci/control` issue may be a general issue. It would be worth checking if other Pacstall and/or apt packages fail to install. The Pacstall folks may be able to help you diagnose the issue better, I haven't used anything except Arch for the last 5 years or so, so I'm pretty out-of-touch with how things are on Debian-based distros :sweat_smile:

**Comment by sonic2kk** [comment] 2023-11-04 03:47
From looking around some more, this is either some specific system issue, or something related to the packaging end on Pacstall. Though from checking it seems people on occasion run into this issue when tinkering with packages on Ubuntu.

I am going to close this as I don't believe this issue is specific to SteamTinkerLaunch functionality. I hope you can get it resolved, please feel free to leave a comment if you do so if anyone else runs into this in future, they can reference your steps!

**Closed as completed by sonic2kk** 2023-11-04 03:47 UTC
Labels: bug, Upstream

**Comment by Elsie19** [comment] 2023-11-22 00:50
I tested this, and I can't reproduce your issue.

**Comment by RawPorkSushi** [comment] 2024-03-09 10:26
Hey, sorry I never came back, and I missed all of your responses due to Gmail filtering.  Thank you for being so thorough.  To be absolutely truthful, after flailing about trying to resolve the issue myself using various techniques, I just abandoned the endeavor entirely.  I  wouldn't be surprised if it was a Pop_OS issue, or an Ubuntu issue.  At this point, however, we'll never know.  Thanks again for your efforts.
