### ISSUE TITLE
NonSteam Game endless loop

### ISSUE THREAD

**Issue by kamil7732** [sonic2kk/steamtinkerlaunch#754] opened 2023-03-01 14:26 UTC
## System Information
- SteamTinkerLaunch version: 12
- Distribution: SteamOS
- Installation Method: protonup-qt

## Issue Description
"steamtinkerlaunch requested proton none not found trying to find similar"
I'm adding gog game like witcher3 & cyberpunk to steam and then trying to use the tool.
At first it was allowing me to load the menu but after unchecking compatbility (the tool enabled) and enabling it again I get
"steamtinkerlaunch requested proton none not found trying to find similar"
And i'm not able to turn on the game, i'm in a constant loop.
I find it hard to somehow work through console. I listed all the games and got few 'No title found for 'xxxxx''

A bit stuck, don't know how to move it forward.

**Comment by sonic2kk** [comment] 2023-03-01 15:09
Did you select a version of Proton from the Game Menu? It sounds like you didn't, and STL likely can't find one to use because you're using a Non-Steam Game.

You'll also need to attach a log for further support, which was requested on the issue template.

Please also keep in mind that Non-Steam Games are not guaranteed to work with Proton in general, and very limited support will be given for Non-Steam games. I have seen numerous reports that GOG Cyberpunk does not work very well with Wine currently.

**Comment by kamil7732** [comment] 2023-03-01 16:12
Game menu is unavailable to me. I'm in the loop only getting error
notification in the bottom right corner.

**Comment by kamil7732** [comment] 2023-03-01 16:12
Ok will add logs. I was able to play both games when i haven't added the tool.

**Comment by sonic2kk** [comment] 2023-03-01 16:27
> Game menu is unavailable to me. I'm in the loop only getting error

Did you press the Skip button too many times? This disabled the STL GUI completely, by design.

If you get the STL wait requester you should be able to access the Game Menu on the Main Menu. I'm not sure what the problem is. Maybe the wiki is your friend if you haven't used STL before?

> I was able to play both games when i haven't added the tool

Well yeah, because you're using Proton. STL is a separate tool that builds the launch command itself. If it doesn't have a Proton version it can't run a game.

**Comment by sonic2kk** [comment] 2023-03-01 16:34
Just tested setting a game to `none` in the config file and I think I see the problem. It doesn't show the wait requester if it can't find Proton for Non-Steam games.

I'll investigate a fix, you'll have to use STL-git to use it though (available in ProtonUp-Qt with Advanced Mode enabled). I'll send a reply when I have a fix.

**Comment by sonic2kk** [comment] 2023-03-01 17:07
Got an experimental fix up with 5b8c860. It correctly resolves the Proton path and uses the correct launch command, ~~however currently on my system for some reason games are not launching (with and without STL) so while there shouldn't be any regressions with the change I made, I cannot fully test it.~~ after a KDE Qt update games launch again and this fix seems to work for me. 

Try out SteamTinkerLaunch-git and see if that fixes the problem. You can tell you're using the latest Git because the version will be `steamtinkerlaunch-v12.12.20230301-1`

**Comment by kamil7732** [comment] 2023-03-02 14:18
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10872187/steamtinkerlaunch.log)
Logs

Will try to get the newest version.

**Comment by kamil7732** [comment] 2023-03-02 14:35
tried to use pacstall to get the version you're mentioning. Sadly even after adding passwd to deck user..apt isn't available.

A bit lost how to get around it.

**Comment by kamil7732** [comment] 2023-03-02 14:54
ok took your changes and overwritten the file...
I'm able to get into the menu but then the game crashes.
When run without our tool I get into the game.
log
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10872538/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2023-03-02 15:22
Pacstall is only for Ubuntu and derivatives, I'm not sure why you're trying to use it on Steam Deck. You can get the latest version using ProtonUp-Qt in Advanced Mode.

Game crahses cannot be resolved by me. Maybe you need a different Proton version, but this is not an STL issue. STL does not provide support for bugs with third party applications. If you get in-game that's about all I can do here, I'm not a Wine developer.

The only other advice I can think of aside from changing the Proton version is to try running without the Steam Linux Runtime. But again, this isn't an STL issue, so I can't give any more support here.

Closing as the initial issue is resolved and the remaining issue is not caused by STL.

**Closed as completed by sonic2kk** 2023-03-02 15:22 UTC
Labels: bug, Non-Steam Game
