### ISSUE TITLE
How to download shader repos? Shader download stays at 0%

### ISSUE THREAD

**Issue by humanplayer2** [sonic2kk/steamtinkerlaunch#430] opened 2022-03-23 23:01 UTC
I'm sorry if this issue is just me fundamentally misunderstanding the GUI. I'm on steamtinkerlaunch-v9.3.20220306.

*The issue:*
In the main menu, when I click Shader repos, two popups open: One where I can select repos, and a download progress bar. If I do nothing, the progress bar doesn't move. If I deselect all but one repo (I tried `SweetFX` and `OtisFX`) and press Select, both windows close, and I'm back at the main menu. When I then click Game shaders, the repo I just selected does not show (it continues to show four options: `dh-reshade-shaders`, `astrayfx`, `brimson` and `depth3d`).

How do I make more shaders available for selection?

**Comment by zany130** [comment] 2022-03-24 01:08
may be related to the issue I opened https://github.com/frostworx/steamtinkerlaunch/issues/429 I was also having issues with the shader download option though for me the issue is selecting any repo causes the reshade repo to be ignored. Workaround is don't use the shader repo option that way it will just download everything and then on the shader installer select the shaders you want to use

**Comment by frostworx** [comment] 2022-03-25 16:52
@humanplayer2 
the "download progress bar" window can be ignored/closed when opening the Shader repos window.
It is some leftover of a function rewrite which I didn't fix.

Selecting repos here does nothing else than creating the download/block lists _(see `~/.config/steamtinkerlaunch/downloads/shaders/`)_ and you get back to the main menu as you've correctly written _(might be worth to check if I also added a download here as it would make sense, but I currently consider freezing the whole project. either way selected repos are downloaded anyway when they are not available, so this is not urgently required here)_

Selecting "Game Shaders" option in the main menu only has an effect, when you have a "current game", so usually when you started a game through steamtinkerlaunch through steam. If you start the settings using `steamtinkerlaunch settings` the last game started is used as "current game" _(but if there is no last game the "Game Shaders" menu doesn't work)_

Assuming you have a game here, all selected repos _(plus the reshade-shaders repo, which is required by most repos)_ are downloaded to `~/.config/steamtinkerlaunch/downloads/shaders` and then all their shaders and textures are symlinked into the current game directory within subdirectories in an autocreated reshade-shaders directory.
All symlinks of deselected repos in the "Game Shaders" are removed from that directory.
btw the "Game Shaders" menu can be opened any time while a game is running using the steamtinkerlaunch trayicon menu.

Just tested it again, and it still works the same as I left it after the major rewrite.

**Comment by zany130** [comment] 2022-03-25 17:15
one way to fix this and prevent user confusion might be to just get rid of the shader download option all together and just have all shader repos downloaded by default then the user can specify what shaders they want installed to the game with the game shader option. all the different descriptions for the shaders can then be moved from the shader download menu into the game shaders menu. 

As of right now, I'm still able to reproduce my issue by using the shader download option and specifying what shaders I want. Plus it could be confusing to users having both options and redundant. I wouldn't mind looking into doing a pull request (if this is something everyone agrees would be benifital) for this when I have time won't be this weekend though most likely

**Comment by frostworx** [comment] 2022-03-25 17:16
https://github.com/frostworx/steamtinkerlaunch/issues/431

**Comment by frostworx** [comment] 2022-03-29 16:39
just checked for the useless "Shader download" window appearing when opening the repos window,
and the reason is simply that this line

`StatusWindow "$GUI_DLSHADER" "dlShaders $3"  "DownloadShadersStatus"`

[here](https://github.com/frostworx/steamtinkerlaunch/blob/master/steamtinkerlaunch#L16513=)

is also used when opening the repos window.

A proper fix [just landed
](https://github.com/frostworx/steamtinkerlaunch/commit/dcb1ed29747afdfffccd472d854099aaf931476d)

**Closed as completed** 2022-04-05 05:11 UTC
