### ISSUE TITLE
Sonic Frontiers can't open when HHM mod loader is installed

### ISSUE THREAD

**Issue by JJPY523** [sonic2kk/steamtinkerlaunch#676] opened 2022-11-27 17:13 UTC
I am using the current version of HHM Dev installed via STL with Frontiers using Proton Experimental on my Steam Deck. I followed the guide from Linux Gaming Central (https://linuxgamingcentral.com/posts/sonic-frontiers-modding-guide/) for installation. I ran into this problem multiple times and uninstalled and reinstalled the loader and STL multiple times and I followed the guide well. Despite that, I have still been  stuck on the steam logo loop when loading up Frontiers with the loader installed. I even have the mscore.dll file in my Frontiers folder on my SD card. I do not know if it's due to my game being on SD and HHM and STL being on the SSD. Is there any way I can load Frontiers successfully with the mod loader?

**Comment by sonic2kk** [comment] 2022-11-27 19:00
When creating issues, please follow the issue template that would've been presented to you when creating a bug report. It is very unhelpful to create free-text issues.

First of all, you shouldn't have installed Hedge Mod Manager with Proton Experimental. The default should have been GE-Proton, Proton Experimental cannot install `dotnet48` which is needed for 64bit games to run. Was there a specific reason you changed this?

As for the core issue, without a log (which was requested in the initial issue template), it's hard to know, but due to a Steam client bug, on Steam Deck the games you want to mod most likely have to be on the Steam Deck SSD until this bug is fixed by Valve. I reported this issue upstream on the Steam for Linux issue tracker but there has been no update yet, and I haven't checked if it's been fixed in the latest client beta. So:

> I do not know if it's due to my game being on SD and HHM and STL being on the SSD.

This is a probable cause of the issue. However, once again, without the logs and more information, I can't help you unfortunately. You'll need to provide the following logs:
- SteamTinkerLaunch log
- installHMM.log

If you haven't used SteamTinkerLaunch before, these logs are available in `/dev/shm/steamtinkerlaunch`.

You'll also need to provide:
- SteamTinkerLaunch version
- SteamOS version (including Stable/Beta/Preview)
- SteamTinkerLaunch installation method

Thanks!

<hr>

For clarity, I need a SteamTinkerLaunch log generated after running Hedge Mod Manager once. So open HMM, then once it fully opens, attach the two requested log files.

**Comment by JJPY523** [comment] 2022-11-27 19:38
[](https://drive.google.com/file/d/1W2eHALH2XdL3WjGLT23S5yMdQ_fjhfiA/view?usp=drivesdk)

Here's a drive link to my stl log. I unfortunately deleted my install.hhm log not knowing its purpose.

**Comment by JJPY523** [comment] 2022-11-27 19:38
[]()https://drive.google.com/file/d/1W2eHALH2XdL3WjGLT23S5yMdQ_fjhfiA/view?usp=drivesdk

Here's a drive link to my stl.log. Unfortunately I deleted my install.hhm log not knowing its purpose.

**Comment by sonic2kk** [comment] 2022-11-27 19:41
Could you upload the log to GitHub please instead of Google Drive? I'm not sure what the drive link contains but you also need to provide the other requested information:
- SteamTinkerLaunch version
- SteamOS version (including Stable/Beta/Preview)
- SteamTinkerLaunch installation method

**Comment by JJPY523** [comment] 2022-11-27 19:42
Oh yea np

**Comment by JJPY523** [comment] 2022-11-27 19:49
STL version: v11.12.20221124-1
SteamOS Holo version: 3.3.2 Stable
STL installation method: Manual, downloaded via Code, download zip

Anything I'm missing? Besides the install.hhm. wait i forgot the stl log

**Comment by sonic2kk** [comment] 2022-11-27 19:51
Looks good, thanks!

Now I just need the SteamTinkerLaunch log file. Open Hedge Mod Manager once and once it's fully open, and go to `/dev/shm/steamtinkerlaunch` and attach the `steamtinkerlaunch.log` to your issue :-)

EDIT: I see you caught it just before I got my reply out, thanks!

**Comment by JJPY523** [comment] 2022-11-27 19:56
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/10099087/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2022-11-27 20:07
Thanks! As a note, Hedge Mod Manager is actually using GE-Proton, not Proton Experimental. So on that front, everything is fine.

The line of interest from your log is this:

```
Sun Nov 27 02:23:44 PM EST 2022 INFO - prepareHMMGames - Wineprefix for game 'Sonic Frontiers (1237320)' did not already exist at '/run/media/mmcblk0p1/steamapps/compatdata/1237320/pfx' - The game may not have been started before!
Sun Nov 27 02:23:44 PM EST 2022 SKIP - prepareHMMGames - Could not find compatdata dir for 'Sonic Frontiers' - Assuming that it is not installed
```

This indicates me that the problem is that Sonic Frontiers is on the microSD card. The issue is that, for some reason, on Steam Deck the Steam client will sometimes (or seemingly most of the time in my recent experience) create Wineprefixes on the boot SSD instead of on the microSD card. On Desktop, Steam will always create the Wineprefix in the same library folder as the game, which is why each library folder has a `compatdata` folder. However on Steam Deck it doesn't seem to be doing this. I'm not sure when this broke or when it'll be fixed sadly.

To work around the issue, Sonic Frontiers has to be installed on the Steam Deck SSD. This issue is **not** present on the Linux Desktop and for some reason only affects the Steam Deck. I understand for many users this is either massively inconvenient, or just not possible (the boot drive may not have enough space or may take up half of the boot drive!). And checking for this on the SteamTinkerLaunch side may be complicated and introduce further problems (Wineprefixes are not always removed when a game is moved e.g. on Desktop, so it may mistakenly choose the wrong prefix, which means the problem would remain the same pretty much).

So the solution to this issue should be:
1. Move Sonic Frontiers to your boot SSD - There is an option in the Steam Client to do this, if you go to the game options -> Properties -> Local Files -> Move install folder. You can do this from Game Mode or Desktop Mode, whichever is more straightforward for you
2. Run Sonic Frontiers at least once and close it.
3. Run Hedge Mod Manager again, SteamTInkerLaunch will see your game when HMM is starting up and install dotnet48 into the game's prefix. Startup may take significantly longer (up to 10 minutes in some cases).
4. Once HMM starts, ensure that you have that `mscoree.dll` file in the same folder as the game executable. This *may* not be needed but it is useful to have it, as it has fixed issues in instances where the game does not load.
  - You mentioned already that you tried including this, which was correct, so this is just as a reminder to ensure you still have it there
5. Test Sonic Frontiers, probably it's most convenient to do this from Desktop Mode. Once you've confirmed it starts up, reboot your Steam Deck (for good measure) and then try playing from Game Mode.

If Sonic Frontiers still crashes, attach your `steamtinkerlaunch` log again as well as a file named `installDotNet.log`. These can be found in `/dev/shm/steamtinkerlaunch.log` once again.

Thanks!

<hr>

As another note, sine this is a Steam Client bug affecting only Steam Deck, this will apply to any game you want to mod with Hedge Mod Manager.

**Comment by JJPY523** [comment] 2022-11-27 20:16
Thank you. My 64 GB SDD is pretty small so I may have to do a HUGE clean-up job or just wait for a fix. Sorry for not following the issue template, I should've read it. Thanks for your help, I hope I can someday play Frontiers with Giganto hitting gangdam style on Sonic.

**Comment by sonic2kk** [comment] 2022-11-27 20:21
Hmm actually, if you know how to make symlinks you can symlink the Wineprefix I think. One of the easiest ways to do this is to use split mode in the Dolphin file manager, drag the Sonic Frontiers' prefix from the SSD library folder's compatdata (1237320) onto the microSD card library folder's compatdata and choose the "link here" option. Example screenshot:

![image](https://user-images.githubusercontent.com/7917345/204157787-93670619-2bcb-4685-a567-6bc91b7b611e.png)

Don't stress too much if you can't do this, but hopefully that explanation made sense. This may fix the issue. Once the symlink is created, start Frontiers again, open HMM and let it fully install dotnet48, and then try again.

I don't remember if I've tested this when installing dotnet48 for a game, but I do this when games on my microSD card won't start (seems to be when I install them in Desktop Mode that they don't start). In the case of HMM though, it'll probably crash with just the symlink since the modloader is installed but dotnet48 is not installed into the game's prefix, and it is the modloader that requires dotnet48.

Fingers crossed! Or if you don't try this, hopefully the reinstall works :-)

**Comment by JJPY523** [comment] 2022-11-27 22:04
Oof. I actually have linked my SSD compdata folder to my SD's to save space on my ssd(funni since I have 5.6 GB left) [20221127_170347.jpg](https://user-images.githubusercontent.com/119229748/204162042-b2d46497-122b-45b6-ab61-aa520261a54d.jpg)

**Comment by sonic2kk** [comment] 2022-11-27 22:21
That looks like the whole folder is linked. I'm not sure how any program including STL would manage having a compatdata from the microSD card linked like this to be honest. Linking one prefix is something you can do but the whole folder is something I think might mess things up with.

Sorry, since the whole folder is linked I'm not sure what advice to give. Moving Frontiers to the boot SSD might not even help in this case, but you could try it.

**Comment by JJPY523** [comment] 2022-11-27 22:51
Ok this may be crazy, but I'm considering factory resetting my deck, setting up STL and Frontiers, and installing mods. Thank you for your help, I appreciate it!

**Closed as completed** 2022-11-27 22:51 UTC
Labels: bug, Hedge Mod Manager
