### ISSUE TITLE
Update instructions for Flatpak installation

### ISSUE THREAD

**Issue by amyfromearth** [sonic2kk/steamtinkerlaunch#1066] opened 2024-03-17 06:50 UTC
Hi! I was struggling to get STL to show up as a compatibility tool under steam until I found this comment on Reddit:

https://www.reddit.com/r/linux_gaming/comments/14kegjz/comment/kax9xia/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button

>Install Steam from Flathub `flatpak install com.valvesoftware.Steam`
>Install steam-tinker-launch from Flathub `flatpak install com.valvesoftware.Steam.Utility.steamtinkerlaunch`
>Run the following command `flatpak run --command=sh com.valvesoftware.Steam`
>         If you care to know, this command allows you to open a shell inside of the container of the named flatpak. If any command line configuration needs done in a flatpak, this will help.
>Now, just run `steamtinkerlaunch compat add` which will automatically build out the symlinks needed.
>Launch Steam, and the steamtinkerlaunch compatibilty option should be available.
>Ended up searching for about an hour to figure this out myself, so hopefully this helps others!

**Comment by frostworx** [comment] 2024-03-17 14:07
hi,
what exactly is missing in the comprehensive [wiki installation part](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation)?:

**Comment by sonic2kk** [comment] 2024-03-17 18:59
Duplicate of https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110, please search around official channels before resorting to Reddit :-)

Also a duplicate of #1043, the issue template asked already to search closed issues before opening duplicates.

**Closed as completed by sonic2kk** 2024-03-17 18:59 UTC
Labels: duplicate, enhancement, Flatpak

**Comment by amyfromearth** [comment] 2024-03-17 23:15
> hi, what exactly is missing in the comprehensive [wiki installation part](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Installation)?:

Specifically this:

>Run the following command `flatpak run --command=sh com.valvesoftware.Steam`
>         If you care to know, this command allows you to open a shell inside of the container of the named flatpak. If any command line configuration needs done in a flatpak, this will help.
>Now, just run `steamtinkerlaunch compat add` which will automatically build out the symlinks needed.

Literally these few lines of instruction is all I needed to get it working as expected. 

> Duplicate of [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#110](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110), please search around official channels before resorting to Reddit :-)
> 
> Also a duplicate of #1043, the issue template asked already to search closed issues before opening duplicates.

If official channels showed up the results I needed more easily than reddit, then I absolutely would! I looked for HOURS and **ONLY** found these specific instructions on Reddit. That's why I'm asking they be included in the official documentation. 

I opened this issue simply to request updating the installation instructions as I have no knowledge of coding or what it would require to make this happen behind the scenes, so I didn't think it was a duplicate of those issues since it's an instruction update and not a "fix" to your code. Maybe I was mistaken but it made sense in my head. 🤷‍♀️

Also, both those issues are marked as closed while this is clearly still happening.

**Comment by amyfromearth** [comment] 2024-03-17 23:19
> Duplicate of [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#110](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110)

> Also a duplicate of #1043, the issue template asked already to search closed issues before opening duplicates.

I opened this issue simply to request updating the installation instructions as I have no knowledge of coding or what it would require to make this happen behind the scenes, so I didn't think it was a duplicate of those issues since it's an instruction update and not a "fix" to your code. Maybe I was mistaken but it made sense in my head. :woman_shrugging:

**Comment by sonic2kk** [comment] 2024-03-18 00:42
> If official channels showed up the results I needed more easily than reddit, then I absolutely would!

You can search on GitHub instead.

> I looked for HOURS and ONLY found these specific instructions on Reddit.

It's not a problem over here though, it's an issue with the Flatpak (and a complicated one to fix I'd assume).

> since it's an instruction update

It's a bug with the Flatpak, not something to document :-)

> Also, both those issues are marked as closed while this is clearly still happening.

I'm confused, https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch/issues/110 is still open?

If you're referring to this issue and #1043, then yes, they're closed because they're not issues here, it's something (to my knowledge at time of writing) that has to be fixed on the Flatpak packaging side. It is not something to document here because it should be fixed, and the workaround is documented on that issue (and I expect users to search through issue trackers to find temporary workarounds, not usage documentation, since SteamTinkerLaunch is for technical users).

The Flatpak is not maintained here, generally speaking these kinds of issues are best reported to the Flatpak maintainer. Some things can be reported here, such as if the Flatpak cannot pick up files correctly, or other things that can likely be fixed on the script side. But those are relatively rare, normally the Flatpak maintainer is the best point of contact to help with issues, as they have historically been missing dependencies or things along those lines; general packaging issues.

<hr>

I couldn't tell you why this problem occurs, or why only some people have to do it, or what the fix is, or when it'll be implemented. It is not something I think is worthwhile noting here because it is a niche workaround for a bug. If another potential fix came up, we'd have to note that too, and it would become cumbersome to maintain.

If it wasn't clear, **this step should not be necessary** and it **is not meant to be part of the installation process**, it is a **workaround for an intermittent bug** that is **specific to certain users on certain distros**. Documenting a command that I don't understand that may or may not help users is not something I am interested in doing. I would rather users help the Flatpak maintainer fix the issue (if I understood more about Flatpak packaging, I would help, but despite spending time trying to understand, much of it is stlll beyond me).
