### ISSUE TITLE
winetricks option not installing directshow packages

### ISSUE THREAD

**Issue by zany130** [sonic2kk/steamtinkerlaunch#387] opened 2021-12-22 18:58 UTC
[Trails of Cold Steel II.log](https://github.com/frostworx/steamtinkerlaunch/files/7764647/Trails.of.Cold.Steel.II.log)
like the title says packages are not being installed correctly I selected the packages I wanted and hit save and play, a notification comes up saying its being installed and immediately another one saying its finished (which it can't as it takes several minutes with protontricks)

**Comment by frostworx** [comment] 2021-12-22 19:34
Please try with the same winetricks version manually _(the used command is literally in the log, in case you haven't read it)_ and also check the winetricks log.
`steamtinkerlaunch` doesn't do any extra magic here, it is all done by winetricks.
Also, as you're idling on discord anyway, you might want to ask there instead of opening a new "issue" every 2nd day.
Btw implemented feature requests should be at least tested and not simply closed after I wasted my time on it.

**Comment by zany130** [comment] 2021-12-22 20:06
1. I did try using a manual winetricks instead of one provided by system same issue
2. using protontricks works fine so the issue is only reproducible in steamtinker launcher hence it is a steamtinker bug
3. this is not me asking how this works it is me reporting a bug with steam tinker which normally is better done in GitHub so that
a. it is easier to track
b. more people can contribute

4. I did test the gdb option and it works as I reported in the issue so I thought it was okay to close as the feature request was successfully implemented

**Comment by frostworx** [comment] 2021-12-22 20:22
1. -> so it is a winetricks problem
2.  -> no it is not - see 1
3. yes, it would be easier to track when it is clearly a bug. just a handful of people actually contribute and I do not have much time anymore as states multiple times before. so hunting down some "possible" bugs alone, besides maintaining code and wiki
and RL simply doesn't fit into a day
4. "if it is too difficult to solve maybe just making a note on the wiki would be enough for now?" -> "The feature is not really difficult to add (see the commit), but the general functionality seems to be a bit hacky. I don't think I will expand the README again, but please don't hesitate to enhance it." -> `closed`.

**Comment by frostworx** [comment] 2021-12-22 20:24
Don't get me wrong - I'm sure you want to help, but I need more people to help, else I will have to close the project down one day, because it is simply too much work for apparently nothing _(I can have fun writing code as well without releasing it)_

**Comment by zany130** [comment] 2021-12-22 21:03
1. not a winetricks problem protontricks is just simply a wrapper for winetricks for easier usage I can use winetricks without steamtinker and it will run fine

EDIT: just re read your comment I thought you were saying to try selecting the option in the global config to download the latest winetricks instead of using the system one ( now I think you meant to try using the same version without steamtinker to see if its a bug with that version specifically. Originally when I got the error steamtinker was configured to launch the system winetricks what I was saying is that I tried both options and when winetricks (system or downloaded) was called from steamtricks I get the issue. When I run the downloaded version myself (without steamtinker) It fails the first time (like I said all the way at the bottom of this issue) but the second time it works.

3. I'm not paying you or contacting you in any way for you to feel an obligation to solve bug reports I bring up. There are a million other things one could be doing and in no way have I ever expected anything out of the bug reports I just report them because I figure that if I can have the issue so can someone else so since I don't know how to help with pull requests I can at least help by reporting the issues I have and someone else who does have the knowledge can help. If I have in any way caused annoyance or distress with my reports I seriously apologize.

4. what was the issue that I didn't open a pull request to add the info I was suggesting?
I'm sorry I been busy when I have time I might get around to learning how git pull request work (would be a good learning experience for me anyway)


Here come my (very long :sweat_smile: )two cents this part can be ignored if you wish.




For your last comment, I just want to add that I 100% agree that it is a lot for one person to manage all you do by yourself. I have seen others make pull requests, but it's mainly for translations; most of the programming for the script and the wiki entries were done by you. (Thank you so much BTW :smile: ) But if I may add my 2 cents, you stating everywhere that you need help and responding to every bug report with an attitude of "OMG, another bug report by this person, why can't he just contribute to the project" really turns people off. One of the great things about opensource, and I guess it's a drawback here, is you can pick you to want to work with. Disagreed with the owner of the repo? Fork it and forget them. Since the Linux crowd is already a pretty divisive group, people have a low tolerance for others, which sucks as you seem not to have any ill will and genuinely care about this project and contributing something extraordinary to the community. It is just that you are understandably overwhelmed with everything.



back to the original issue I'm trying to see how I can get a winetricks log from steamtinker as I'm wondering if it's related to this winetricks issue https://github.com/Winetricks/winetricks/issues/1648 but it's supposed to work on the second try after trashing the files (that's how I get it to work when I run winetricks my self with protontricks)

**Comment by frostworx** [comment] 2021-12-23 06:15
I was really talking about winetricks, not protontricks. It might be possible that the latter tries to work around some winetricks issues, but I doubt, as an upstream bug should be fixed upstream. As you can see, steamtinkerlaunch simply creates a winetricks command with its arguments and vars and executes it and does nothing which prevents the installation from working.
Some packages fail on the first instance (again winetricks), but may succeed on a 2nd run, which steamtinkerlaunch tries to fix as well, by running the failed installed on a 2nd run again. As you know, steamtinkerlaunch logs a lot - it doesn't log winetricks though because it is a different program - therefore the log looks fine.
The apparently first step to debug this is to reproduce the exact winetricks command `manually`, which I mentioned. The 2nd would be trying a different winetricks with the same options.
winetricks problems can have multiple reasons, btw - one is switching between several wine/proton versions in a wineprefix.

I usually always react polite and helpful to issues, when they are not hostile from scratch or random questions which were asked and answered multiple times before. Sometimes the language barrier probably is an issue as well, and I react more angry than appropriated. Apologies for that. Others open an "issue", I try to help and then OP doesn't react anymore - what for?

Generally _(not steamtinkerlaunch related)_ I think that more and more people are getting too bored reading wikis, but simply expect an answer when they throw in a question somewhere without doing anything initially to solve it by themselves. This attitude is extremely annoying _(and I'm sure it will even worse)_

Indeed, I called too much for help, and wrote just a few days ago somewhere that I should stop it because it apparently doesn't help anyway. I once started with it because I was "turned off" - Hen egg problem.

Enough for now - starting RL work soon...

**Comment by zany130** [comment] 2021-12-23 18:04
Yeah I see why you said its not a steamtinker bug. I been testing so more I think whats happening is that its calling winetricks like its supposed to then winetricks fails due to the bug I mentioned and then steamtinker continues running. What I don't understand is why the workaround of trashing the broken dlls and running again does not work with steamtinker  launcher. Really the only thing you can fault steamtinker for (and maybe I was doing so harshly and inappropriately) is not working with the work around to the upstream issue.

I see 2 ways this issue is resolved

1. the installation bug is fixed upstream (this would be ideal and looking at the github issue there is some progress?)

2. a way to log winetricks is somehow added maybe like this `winetricks -v >> winetricks.log` added to where it calls winetricks (I should be able to do that myself doesn't sound to hard and maybe would make a nice pull request anyway so users can know what winetricks did?) and a temporary fix is implemented to work around this (this might not be worth it and actually in my honest opinion I would agree with you that it should not be done though pull requests are welcome 😄 )


EDIT: was taking a look at the code and there already is a line for a winetricks log https://github.com/frostworx/steamtinkerlaunch/blob/40142290eeff3b4415041e960d7e4b4278bbce9e/steamtinkerlaunch#L9713 don't know why I couldn't find it though it should be in `/dev/shm/steamtinkerlauncher/` could it be because of the stl rename? EDIT: don't think so took a closer look

**Comment by frostworx** [comment] 2021-12-23 18:19
maybe you started winetricks using the gui, in which case it doesn't use the function `installWinetricksPaks` but the function `checkWinetricksLaunch` which does not log _(yet)_

**Comment by zany130** [comment] 2021-12-23 21:17
so I have been using the wine tricks option in the main menu and then clicking select packages so I could select the ones I have been using. I tried it again on a clean prefix and I did get the guess I just didn't see it before as I was looking in .config and it was in /dev/shm/steamtinker/[WINETRICKS.log](https://github.com/frostworx/steamtinkerlaunch/files/7771376/WINETRICKS.log) and it seems like it even installed everything correctly on the first try (it was mentioned in the upstream issue that setting up the winetricks packages BEFORE proton does the first time setup actually workaround the issue). Strangely though the game immediately crashes now
[steamtinkerlog.log](https://github.com/frostworx/steamtinkerlaunch/files/7771388/Trails.of.Cold.Steel.II.log) (don't think there is anything useful there since as far as steamtinker is concerned the game launched successfully, well, and immediately closed) the proton log is empty so I wonder if the first time setup was run? This might be a result of how steamtinker is launched maybe and is expected?

 Something is not working as intended though I tried wiping and recreating the prefix and when steam tinker launcher tries to run lavfilters winetricks package it gives a bunch of errors ( not the same as the upstream issue) and fails. wiping and recreating that prefix again and running `WINE="/home/zany130/.local/share/Steam/steamapps/common/Proton 6.3/dist/bin/wine" WINEARCH=win64 WINEDEBUG="-all" WINEPREFIX="/home/zany130/.local/share/Steam/steamapps/compatdata/748490/pfx" winetricks --unattended amstream lavfilters quartz`
which seems to be the same command steamtinker uses as I got it from the log, the install complete's correctly on the second try after deleting the messed up dlls (because of the upstream issue)
[WINETRICKS.log](https://github.com/frostworx/steamtinkerlaunch/files/7771800/WINETRICKS.log)
vs 
[WINETRICKS-term.log](https://github.com/frostworx/steamtinkerlaunch/files/7771805/WINETRICKS-term.log)

which looking at them side by side when ran from steamtinkerlauncher it is using wine-6.22-380-g27584c14497 ( TkG Staging Esync Fsync )

and when run from the term it  uses

wine-6.3

I see the issue when you install winetricks packages from the main menu winetricks sub menu it actually calls winetricks like this `WINE="" WINEARCH=win64 WINEDEBUG="-all" WINEPREFIX="/home/zany130/.local/share/Steam/steamapps/compatdata/748490/pfx" winetricks --unattended amstream lavfilters quartz`
 
 which will use my systems default wine version which is the tkg one using that one I can reproduce the lavfilters install error

`WINE="/home/zany130/.local/share/Steam/steamapps/common/Proton 6.3/dist/bin/wine" WINEARCH=win64 WINEDEBUG="-all" WINEPREFIX="/home/zany130/.local/share/Steam/steamapps/compatdata/748490/pfx" winetricks --unattended amstream lavfilters quartz` is used when you use the option under game menu to install once you hit play.

**Comment by frostworx** [comment] 2021-12-24 06:30
yes, sometimes steam first run is not triggered. iirc it has to do with the default proton version used.
unlikely that I will investigate this as it is coming from steam and might be getting even worse.

**Comment by frostworx** [comment] 2021-12-24 07:12
[added winetricks gui logging](https://github.com/frostworx/steamtinkerlaunch/commit/c6e241b2f86e32b3a5c5d81fd09e828bbae48f81)

**Comment by zany130** [comment] 2021-12-24 14:53
yup tested it and it creates the log successfully

like I said at the end of the last issue my original problem was that I was using this to install the wine tricks pacages (rn there nothing selected as I already installed them) 

![image](https://user-images.githubusercontent.com/25832539/147359969-fbdb2f96-4743-48d8-b67a-0e95ea0f962a.png)
 
 this uses your system default wine version which for me is the latest tkg.
 and that wine version has issues with installing lavfilters (was able to reproduce on my own)
 
 
![image](https://user-images.githubusercontent.com/25832539/147360220-bb6dee9e-7794-422c-8b20-142a6b58e56d.png)

this one uses the wine version from your currently selected proton version I think (for me it was using 6.3 wine and I was using 6.3-8c proton)

like this the install will succeed if done before the start up of the game or with the workaround I mentioned of trashing the dlls the log complains about and trying again.
 Same thing if launch the GUI it uses 6.3 and works with the above workarounds

**Comment by frostworx** [comment] 2021-12-25 08:03
so, *invalid* as initially said?

**Comment by zany130** [comment] 2021-12-25 17:36
Well if it intended for the install button to use a different wine version than the other methods (GUI and game menus) then i guess yeah it's invalid though i don't know why you would do that. All methods should use the same wine version in my opinion

**Comment by frostworx** [comment] 2021-12-26 07:06
Some packages refuse to be installed with specific wine versions, that is the reason why that option even exists apparently.

**Closed as completed by frostworx** 2021-12-26 07:06 UTC
