### ISSUE TITLE
Compatibilitytools.d is in another directory on Debian Buster

### ISSUE THREAD

**Issue by kadogo** [sonic2kk/steamtinkerlaunch#116] opened 2020-10-24 23:21 UTC
Hello at first thanks for your big work on STL.

It make me discover applications I didn't know and it really ease all the configuration. I just start playing with it and it's already pretty amazing.

It's not a big issue, I will self make a PR myself later if you want but I just want to be sure it's not an issue from my setup (it's a Debian Buster with some unstable stuff so it's not really the most stable system).

When I did `stl compat add` it installed STL in `/home/user/.steam/compatibilitytools.d/` instead of `/home/user/.steam/root/compatibilitytools.d/`. I must move it with the older compatibiitytools from Steam so that it could be detected.

I not know if it's related to may setup or maybe because I had old version of compatibilitytools but if you think it's normal I can take a look to add a check if the directory already exist when we use `stl compat add`

Have a good evening.
Cheers

**Comment by frostworx** [comment] 2020-10-25 04:55
Hello!
Thanks a lot for the friendly feedback! Despite the amount of stars it is sometimes hard to tell if people like or even use my program, because everything is pretty silent.

The absolute path `"$SCTS"` which `stl compat add` currently uses is
`~/.steam/steam/compatibilitytools.d/SteamTinkerLaunch/`.

_(which is set up from `"$STEAMCOMPATOOLS/$PROGNAME"`,
where `"$STEAMCOMPATOOLS"` is `"$HSS/compatibilitytools.d"` and `"$HSS"` in turn is **`"$HOME/.steam/steam"`**
and `"$PROGNAME"` is SteamTinkerLaunch)_

On my system all directories but "steamcmd" in "$HOME/.steam" are symlinks _(I'd say autocreated)_
and both `"$HOME/.steam/steam"` and `"$HOME/.steam/root"` point to `"$HOME/.local/share/Steam"`
where `"compatibilitytools.d"` lies. Not unlikely that all those confusing symlinks are the cause of the issue here.

Hard to tell if using `"$HOME/.steam/steam"` for `"$HSS"` is the/an official way to go, but if using `"$HOME/.steam/root"`
for `"$HSS"` would fix it for you, I'd be happy to change it.
Would be nice if you would test if that fixes the issue, by changing the variable here:
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L128
Have a nice sunday.
cheers

**Comment by frostworx** [comment] 2020-10-25 05:38
I just found 
`Proton-tkg 5.19.r1.gb49e8743 standalone package: Uncompress to ~/.steam/root/compatibilitytools.d on most distros or ~/.steam/compatibilitytools.d on Debian/Ubuntu or other Debian based distros. If the directory doesn't exist, simply create it. `
here https://github.com/Frogging-Family/wine-tkg-git/releases
So `~/.steam/root/` seems to be correct, but does that fix the problem for debian (flavors)?
Would it make sense to make some kind of distribution check? Do you know how reliable `/etc/lsb-release` is meanwhile?
IIRC it was no official standard last time I read about it _(several years ago)_, but there was no alternative as well.

**Comment by kadogo** [comment] 2020-10-25 07:06
> Hello!
> Thanks a lot for the friendly feedback! Despite the amount of stars it is sometimes hard to tell if people like or even use my program, because everything is pretty silent.

Hello, you are welcome. I didn't tried the modification yet I will do that in the day.
I discover STL on GamingOnLinux if I remember and I didn't had try to test it. It was just bookmarked for later. I started to play with it because I wanted to try to use Reshade Depth3D for Amnesia Dark Descent (Debian is a bit too old for vkBasalt ^^).

If could it run it with Reshade and vr-video-player my next step will be to see how work opentrack and if it would be a good thing maybe add in STL if it work correctly but that will be other issues and PR (I'm not there yet ^^).

I think it could have some potential for Windows users too for all the "auto-setup" stuff like Reshade or other applications that can work on Windows but that's another story and it would be done by a Windows user for testing etc.

> I just found
> `Proton-tkg 5.19.r1.gb49e8743 standalone package: Uncompress to ~/.steam/root/compatibilitytools.d on most distros or ~/.steam/compatibilitytools.d on Debian/Ubuntu or other Debian based distros. If the directory doesn't exist, simply create it. `
> here https://github.com/Frogging-Family/wine-tkg-git/releases
> So `~/.steam/root/` seems to be correct, but does that fix the problem for debian (flavors)?
> Would it make sense to make some kind of distribution check? Do you know how reliable `/etc/lsb-release` is meanwhile?
> IIRC it was no official standard last time I read about it _(several years ago)_, but there was no alternative as well.

My lsb_release command looks like that but the file `/etc/lsb-release` not exist.

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
```

Pretty surprising because I must use `~/.steam/root/compatibilitytools.d` maybe it's related if there are already existing compatibiiltytools. I will give it a try by remove them and just using STL install again. If it work I think just a path check would be enough. I will give an update when I did my tests (in the evening).

Cheers

**Comment by frostworx** [comment] 2020-10-25 07:26
Among multiple other things I also improved Stereo3D detection _again_ offline, but current release should basically work.
For Depth3D ReShade is currently better anyway and it works excellent with proton.
I never really did anything with opentrack, but if it makes any sense to implement some support in stl it would be a good idea.
I agree that such a tool could be interesting for Windows users as well, as it simplifies pretty much, but I would not take care of any compatibility personally.
Ah, sure totally forgot `lsb_release`, but looks like/I hope it shouldn't be required to pull it in as dependency. A path check would not work though, as I can't expect `compatibilitytools.d` to already exist in either path.
In any case I already replaced `"$HOME/.steam/steam"` with `"$HOME/.steam/root"` and all `HSS` occurrences `HSR` offline.

**Comment by kadogo** [comment] 2020-10-25 18:01
Hello,

At first, I tried to remove my "compatibilitytools.d" but it not work if it's installed in "$HOME/.steam/steam/compatibilitytools.d"

If I change "STEAMCOMPATOOLS" to "$HOME/.steam/root/compatibilitytools.d" it's working when I do `stl compat add`

I think it's better to change this one than "HSS" because you use it for "HSSCC" and my config.vdf is correctly in "$HOME/.steam/steam/config/config.vdf"

For what I saw "$HOME/.steam/root/" i end is "$HOME/.steam/" but it look like "$HOME/.steam/root/" is recommended better using this one maybe.

**Comment by frostworx** [comment] 2020-10-25 19:38
Hi,
ok, then `"$HOME/.steam/root/compatibilitytools.d"` is generally correct and debian doesn't require an extra path - so far so good.
please paste the output of
`readlink ~/.steam/steam`
and
`readlink ~/.steam/root`

Not unlikely that both symlinks point to the same directory `~/.local/share/Steam` on your system as well.
If so splitting all related path variables would not be necessary.
Maybe that is that what you said with your last sentence, but I'm not 100% sure.
In any case `"$HOME/.steam/steam/config/config.vdf"` is valid here as well.

**Comment by kadogo** [comment] 2020-10-25 19:55
Here is the output

```
$ readlink ~/.steam/steam
$  readlink ~/.steam/root
/home/user/.steam
```

Yes sorry english is not my native langage ^^

**Comment by frostworx** [comment] 2020-10-25 19:58
Yay, thanks for testing! So the paths are identical and everything should be fine.
Or do you think there's something which should be resolved in this issue?

NP, it isn't my native language as well. Could have also been a communication problem on my side :)

**Comment by kadogo** [comment] 2020-10-25 20:01
I think we can just change "HSSCC" but maybe it can have some issues with other distro?

**Comment by frostworx** [comment] 2020-10-25 20:07
On my current _(offline)_ code HSRCC resolves to `~/.steam/root/config/config.vdf`
Do I understand correctly, that you have concerns that
`~/.steam/steam`
and
`~/.steam/root`
do not point to the same directly on every system?
Sure this might be possible, but probably not very likely.
I tend to leave it as it is until someone really cries :)

**Comment by kadogo** [comment] 2020-10-25 20:42
For me my config is in .steam/steam

```
$ find ~/.steam/ -name "config.vdf"   
/home/user/.steam/steam/config/config.vdf
```

In my case it's really just the compatibilitytools.d that is another directory but the config is in the right one (pretty weird...) ^^

**Comment by frostworx** [comment] 2020-10-25 20:52
I just added
```
HSR="$HOME/.steam/root"
HSS="$HOME/.steam/steam"

HSRCC="$HSR/config/config.vdf"
if [ ! -f "$HSRCC" ];then
	HSRCC="$HSS/config/config.vdf"
fi
```
which should cover both correctly in any case.

Just have recognized that your symlinks point into the directory where the symlinks are and not into `~/.local/share/Steam`
This whole symlink mess should be corrected upstream...

**Comment by kadogo** [comment] 2020-10-25 20:55
I think it would be good, I let you push the modification and close the issue.

I will make another one a bit later because I have remarked that the saving of the configuration didn't work but I need to take a bit of time to read the bash output before so it will be more easier for you and I will be sure it's not an issue because my system is broken ^^

**Comment by frostworx** [comment] 2020-10-26 08:16
I already messed around in my "commit directory" readme and translations, so this fix will be pushed with the next release `(hopefully this week)`.

**Comment by kadogo** [comment] 2020-10-26 09:23
No issue no need to rush ^^

**Comment by frostworx** [comment] 2020-10-27 09:00
fixed in https://github.com/frostworx/steamtinkerlaunch/releases/tag/v2.6.0

**Closed as completed by frostworx** 2020-10-27 09:00 UTC
