### ISSUE TITLE
Proton experimental needs to be reselected after each update

### ISSUE THREAD

**Issue by koplo199** [sonic2kk/steamtinkerlaunch#661] opened 2022-11-16 18:42 UTC
## System Information
- SteamTinkerLaunch version:  v11.11
- Distribution:  Arch Linux
- Installation Method:  AUR

## Issue Description

Each time Proton Experimental receives an update, it needs to be reselected or the game will not launch. I believe it is caused by the name format being `experimental-7.0-DATE`, which means after an update it becomes `experimental-7.0-NEWDATE` and causes a crash as `experimental-7.0-DATE` cannot be found anymore

**Comment by sonic2kk** [comment] 2022-11-16 19:03
Hi there! 

This is fixed in the latest git, it is noted on the [changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) :-) Since you're on Arch, you can use the `steamtinkerlaunch-git` package. Before updating, I recommend deleting `/dev/shm/steamtinkerlaunch` just to ensure the cached Proton versions are updated.

Thanks! Closing this, please reopen if the issue persists.

P.S. - Your description of what caused the issue is actually completely spot on!

**Closed as completed** 2022-11-16 19:04 UTC
Labels: bug

**Comment by koplo199** [comment] 2022-11-16 20:35
Thanks a lot @sonic2kk!

**Comment by sonic2kk** [comment] 2022-11-16 21:37
No problem! It was an annoyance I ran into myself and fixed :smile:
