### ISSUE TITLE
Settings wont save on Debian/Ubuntu/Mint with GUI

### ISSUE THREAD

**Issue by staticnation** [sonic2kk/steamtinkerlaunch#124] opened 2020-11-01 18:20 UTC
if I use the gui to change something like gamemode, and save+reload, save, etc. the settings do not save. STL is in /usr/local/bin and stl doesnt seem to be updating the conf files in ~/.config/stl.

```
/usr/local/bin$ ls
.rwxrwxrwx 261k static  1 Nov  6:36 stl
.rwxrwxrwx 7.6M static  1 Nov  6:18 Yad-313ada9-x86_64.AppImage
```

**Comment by kadogo** [comment] 2020-11-01 23:58
I had the same issue with my Yad package build really so I not think it's an AppImage issue.

But I didn't dig yet. As workaround You can click on "editor menu" and select the file that concern the game.
You can edit the parameter in your editor, it's not the best but it can still help.

**Comment by staticnation** [comment] 2020-11-02 06:03
@kadogo thanks for the reply, yeah Ive been editing the conf files in sublime text editor, just wanted to get the issue on the tracker

**Comment by frostworx** [comment] 2020-11-03 11:53
@staticnation 
Pretty sure this is appimage related, but I'm sure we'll find out soon or later.
Would be nice if you would attach an initial log like this (1+2 to make sure we start from scratch)
1) remove/rename the `~/.config/stl` directory
2) remove the temp directory _/dev/shm/stl_ if it exists
3) `stl settings`
4) change any value and "save"
5) attach the `/dev/shm/stl/stl.log` here

If you have the chance to try the same with a self-rolled yad this would be great.

**Comment by kadogo** [comment] 2020-11-03 15:18
Hello

I dig a bit and I found what to change for make it work but I not understand why it's not working with the extRun function. It looks like it's related to extRun that make the result empty.

```
diff --git a/stl b/stl
index 91c4c14..2849836 100755
--- a/stl
+++ b/stl
@@ -1794,10 +1794,10 @@ function saveYadCfg {
                loadCfg "$YADCFG"
                YLC=1
                YADCATLIST="$STLSHM/yadcatlist.txt"
-               extRun sed -n "/^#STARTYAD$DELIM/,/^#ENDYAD$DELIM/p;/^#ENDYAD$DELIM/q" "$0" | grep "\-\-field" | rev | cut -d '{' -f1 | rev | sed '/LBL/c\NOVAL' | sed '/BTN/c\NOVAL' | cut -d '/' -f1 > "$YADCATLIST"
+               sed -n "/^#STARTYAD$DELIM/,/^#ENDYAD$DELIM/p;/^#ENDYAD$DELIM/q" "$0" | grep "\-\-field" | rev | cut -d '{' -f1 | rev | sed '/LBL/c\NOVAL' | sed '/BTN/c\NOVAL' | cut -d '/' -f1 > "$YADCATLIST"
 
                while extRun read -r YADVAL; do
-                       YADCAT="$(extRun sed "${YLC}q;d" "$YADCATLIST")"
+                       YADCAT="$(sed "${YLC}q;d" "$YADCATLIST")"
                        YADVALUNQ="${YADVAL//\'/}"
                        WRITEYADVAL="${YADVALUNQ/# -/-}"
```

Edit:

I think I just found it... Debian have sed in /bin/ ...

```
$ whereis sed
sed: /bin/sed /usr/share/man/man1/sed.1.gz /usr/share/info/sed.info.gz
```

If I unset the variables like in extRun sed is not found anymore

```
$ LC_ALL="" PATH="/usr/local/bin:/usr/bin" LD_LIBRARY_PATH="" LD_PRELOAD="" sed
bash: sed : commande introuvable
```

I changed added `/bin` to the PATH variable in extRun and it's working for me.

**Comment by frostworx** [comment] 2020-11-03 15:37
Hi,
thanks for digging through this.

To quickly explain extRun: Some system programs do simply not work when executed with the Steam internal environment (f.e. "file"), that's why I disable multiple variables centrally in extRun to get the programs working - so extRun is here for a reason :)
In other words - avoiding extRun f.e. with a simple "USINGAPPIMAGE" boolean apparently could get the AppImage to work here, but very likely will break multiple other functions and external system calls.

**Comment by kadogo** [comment] 2020-11-03 15:40
Sorry I edit a bit before for avoiding multi posting. But I think the issue is sed because it's not in /usr/bin or /usr/local/bin at least for Debian. But by adding /bin to PATH it worked for me but maybe it's different for Ubuntu or Mint.

**Comment by frostworx** [comment] 2020-11-03 15:50
Oh wow, debian still has "/bin/" as standalone variable?
I thought any major distribution symlinks to /usr/bin since years.
Very good find! Thanks a lot! :)

**Comment by frostworx** [comment] 2020-11-03 15:52
@kadogo 
Would you please paste a default $PATH? I'd like to use the same order in extRun, to avoid _(unlikely)_ priority glitches

**Comment by kadogo** [comment] 2020-11-03 15:53
@frostworx You are reading my mind I was just copy pasting ^^

```
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
```

**Comment by frostworx** [comment] 2020-11-03 15:57
thanks a lot! Will use that 1to1 :)

**Comment by frostworx** [comment] 2020-11-03 16:09
Could you please check if this is fixed in https://github.com/frostworx/steamtinkerlaunch/commit/1432743712da14bd653cb7b38bd5a99b4cf62a90 ?

**Comment by kadogo** [comment] 2020-11-03 16:19
@frostworx I just tested on a native linux game by changing the options and saving / reload and it looks good on Debian Buster at least.

**Comment by frostworx** [comment] 2020-11-03 16:22
Thanks @kadogo! Sounds good!
I'll leave the issue open until op can confirm that it works now.

**Comment by staticnation** [comment] 2020-11-04 07:24
@frostworx @kadogo good job guys, this fixed it on my end

**Comment by frostworx** [comment] 2020-11-04 07:28
nice! Thanks for the feedback @staticnation!
*closing here*

**Closed as completed by frostworx** 2020-11-04 07:28 UTC
