### ISSUE TITLE
HMM cant boot

### ISSUE THREAD

**Issue by RoseyLemonz** [sonic2kk/steamtinkerlaunch#808] opened 2023-05-20 22:51 UTC
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: SteamOS
- Installation Method: ProtonUP-QT / Terminal

## Issue Description
Trying to mod Sonic Generations on Deck, installed STL through ProtonUp-Qt and then ran [ steamtinkerlaunch hmm start ] in the terminal, let it install (for like an hour and a half goddam) and the terminal showed the thing in the log. Tried reinstalling 3 times and it still doesnt work

## Logs
[startHMM.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11523323/startHMM.log)

**Comment by sonic2kk** [comment] 2023-05-20 23:11
From looking at the logs I don't see anything immediately wrong, this seems like another case of .NET not installing properly with Wine. This has become more and more of a problem with SteamOS, with Vortex also failing to install dotnet48 (it no longer requires it as of 1.8.0 thankfully, but it did fail).

I'm sorry to say there isn't much I can do about .NET not installing properly on SteamOS. Some users have reported more success by trying a few times with Protontricks, though others recently have reported Protontricks not working on SteamOS in general and not just with dotnet48.

If you haven't already tried the troubleshooting steps on the wiki (mainly using Proton 5.0 to install HMM in a clean prefix and then once installed, changing the Proton version back to something newer like Proton 8) then I don't think there's much else I can do to help. DotNet48 in my experience seems to work more reliably outside of SteamOS for some reason.

I'm going to close this issue as issues with program components not installing properly under Wine on a specific distro isn't something I can do much about unfortunately. I would like to, especially for #625, but the issue is not even consistent on SteamOS (searching through reported HMM and Vortex issues on here you can see the .NET breakages sometimes just go away, or sometimes prefixes break out of nowhere).

You can see information about .NET installation in `/dev/shm/steamtinkerlaunch` and you can use this information to try and troubleshoot what mightve failed. One user was able to isolate their specific instance to one DLL being required, but this didn't work for others. You may be able to use this to try and investigate further.

Good luck, feel free to update if you figure out what caused .NET to fail to install for you, or if any of the troubleshooting steps on the wiki helped.

**Closed as completed by sonic2kk** 2023-05-20 23:11 UTC
Labels: bug, Hedge Mod Manager
