### ISSUE TITLE
stl launched but no visible editor

### ISSUE THREAD

**Issue by LuvIsBadToTheBone** [sonic2kk/steamtinkerlaunch#97] opened 2020-10-08 15:35 UTC
Hello,

when launch a game ,i tried civ iv, civ vi, oxygen not included and  advisors at the end of the universe. then popup come 
https://imgur.com/a/n0GNzcS when click setting the setting editor but no opens it says in the upper riight corner steam tinker launcher started but i see nowhere.

https://pastebin.com/hxGmygXz civ 4
https://pastebin.com/KGMax7Ue oni
need more info, or i do waht w rong?

**Comment by frostworx** [comment] 2020-10-08 15:42
Someone recently opened an issue and suspected that his debian yad is too ancient to properly work.
Unfortunately he never confirmed it.
Maybe that is your problem as well.
In the first paste the requester timeouted though, so this was normal behaviour.

**Comment by frostworx** [comment] 2020-10-08 15:49
Please also start `stl settings`
from terminal.
Might also help to restart with clean stl settings (before):
just rename _(or delete if there's nothing which you want to keep)_ `~/.config/stl`

**Comment by LuvIsBadToTheBone** [comment] 2020-10-08 15:55
i tried the yad from repo.it works too. but after settings ask of game still no editor from stl :(
from terminal this is the output:
toni@rechenknecht:~$ stl settings 3900
Do 8. Okt 17:57:08 CEST 2020 INFO - openSettings - opening Settings
yad: cannot create shared memory for key 31337: Die Datei existiert bereits

**Comment by frostworx** [comment] 2020-10-08 16:03
ah there you have it.
Stray yad files are lying in your /dev/shm which need to be removed and apparently you have no
ipcrm installed (as this should delete them automatically)
when installed try
`ipcrm -M 31337`
and try `stl settings` again.

**Comment by LuvIsBadToTheBone** [comment] 2020-10-08 16:27
ipcrm is installed, at least terminal not moaning when enter ipcrm -M 31337
after run this command and write stl settings 3900 the error msg is no more but terminal seems be idle after. and there is no
further focus in terminal

**Comment by frostworx** [comment] 2020-10-08 16:33
I still think it is your yad version and not stl itself which is failing here, because it doesn't do much more at this state.

You could change `USEGUI="yad"` to `USEGUI="zenity"` in the global.conf to have limited functionality.
I have yad-7.2 on arch linux here.

Bad about the time, but after the community feedback being at zero _(on irc)_ I consider freezing development on stl, so it might not even worth the trouble for you.

**Comment by LuvIsBadToTheBone** [comment] 2020-10-08 16:53
for all debian ubuntu and mint users the version o.4o.0 only is available. looks like we excluded from stl.
beside theres no USEGUI="yad" entrie in  global.conf https://pastebin.com/q8i9Kxa7
thank u very much for help :)

**Comment by frostworx** [comment] 2020-10-08 16:55
Uh oh, "config Version: v2.0.0"
this is ancient!
You should try the latest version!
and yad 0.40.0 is really ridiculous old...

**Comment by frostworx** [comment] 2020-10-08 17:10
hm?

**Comment by frostworx** [comment] 2020-10-08 17:20
So are you sure you wanted to close the issue without any comment?

**Comment by frostworx** [comment] 2020-10-09 07:17
.

**Closed as completed by frostworx** 2020-10-09 07:17 UTC

**Comment by frostworx** [comment] 2021-01-27 11:21
~~No idea what the  point is, but as the same just happened on irc, I assume **yes!**~~

Edit: looks like it was just a misunderstanding. All good!
