### ISSUE TITLE
STL attempts to install ModOrganizer2 v2.5.1rc

### ISSUE THREAD

**Issue by Opal18** [sonic2kk/steamtinkerlaunch#1019] opened 2024-01-17 23:13 UTC
## System Information
- SteamTinkerLaunch version: e.g. v12.12
- Operating System: Garuda Linux 
KDE Plasma Version: 5.27.10
KDE Frameworks Version: 5.114.0
Qt Version: 5.15.12
Kernel Version: 6.7.0-zen3-1-zen (64-bit)
Graphics Platform: Wayland
Processors: 16 × 12th Gen Intel® Core™ i5-12600K
Memory: 31.1 GiB of RAM
Graphics Processor: NVIDIA GeForce RTX 3070 Ti/PCIe/SSE2
Manufacturer: ASUS
- Installation Method: Octopi (package manager)

## Issue Description
Upon clean installs of STL and steam games (FO4, TES4, TES5), trying to install mod organizer 2 will install the latest git version (v2.5.1RC) which then promptly fails. No idea how or why since I thought this was coded to only use v2.4.4

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13969755/steamtinkerlaunch.log)
![Screenshot_20240117_175704](https://github.com/sonic2kk/steamtinkerlaunch/assets/152035555/b52edeec-de53-4466-8e23-1ed612deb587)

**Comment by sonic2kk** [comment] 2024-01-19 00:32
Only STL-git is pinned to use v2.4.4, if you read the changelog and the closed issues you would've seen this has already been covered extensively. Please follow the guidance on the issue template and do a bit of research into past issues, they can have the answer or a hint to fix the problem yourself.

Make sure you follow the steps on the wiki to remove it from the game prefiix (on Steam Deck you can use Developer settings to remove Proton files to remove it from the prefix).

<hr>

For what it's worth, duplicate of:
- #1018
- #1016
- #1012
- #1009 
- #986
- #982
- #976
- #974
- #973 (the original issue that resulted in STL being pinned for v2.4.4)

**Closed as completed by sonic2kk** 2024-01-19 00:32 UTC
Labels: bug, duplicate, ModOrganizer 2
