### ISSUE TITLE
Fresh Fedora 39 KDE install, flatpak Steam doesn't show STL in its compatability list

### ISSUE THREAD

**Issue by ZdrytchX** [sonic2kk/steamtinkerlaunch#1043] opened 2024-02-19 06:38 UTC
_(Linux newbie here, hadnt touched linux since ubuntu 11. Sorry I know GH issue tracker isnt for technical support but I'm not sure where to ask regarding this since google found nothing?)_
Steam Flathub version 1.0.0.78    
STL flathub version 14.0.20230110-1

both installed via discover as directed. Previously thought the issue was that I had steam snaps/image installed and couldn't uninstall steam snaps, so I ended up flashing the hard drive and reinstalling fedora. Even with a fresh fedora install, steam flatpak still doesn't detect steamtinker

STL does not show up in the compatability launch list nor can it be run via konsole:

```
zdrytchx@fedora:~$ steamtinkerlaunch yad ai
bash: steamtinkerlaunch: command not found...
```

EDIT: I also tried using ProtonUp-Qt which just shows STL on discover already installed

**Comment by sonic2kk** [comment] 2024-02-19 17:20
Issues like this should not be reported here, but upstream at [flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch](https://github.com/flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch), since this is with general Steam Flatpak usage. The Flatpak packaging is handled by a different maintainer.

> steam flatpak still doesn't detect steamtinker

This sounds like a duplicate of the well-known at this point flathub/com.valvesoftware.Steam.Utility.steamtinkerlaunch#110. The instructions on that issue will hopefully resolve the problem for you. If not, open a new issue there and the maintainer should be able to help you out :-)

> nor can it be run via konsole

You can't run Flatpaks this way as far as I know. You might be able to run `com.valvesoftware.Steam.Utility.steamtinkerlaunch`, but that's something to ask about upstream, not here.

> *Linux newbie here*

Just as a small caution, SteamTinkerLaunch is for Linux enthusiasts and not newbies. You may not have a good experience if you don't come from a long-time Linux background, or a developer-esque background. It is a tinker utility, hence why it is called Steam*Tinker*Launch, emphasising that it is for tinkerers and Linux enthusiasts.

<hr>

Closing as there are no action items on my end. Good luck!

**Closed as completed by sonic2kk** 2024-02-19 17:20 UTC
Labels: Flatpak, Upstream
