### ISSUE TITLE
MO2 Refuses to start

### ISSUE THREAD

**Issue by ggibson50** [sonic2kk/steamtinkerlaunch#974] opened 2023-11-11 04:22 UTC
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: SteamOS
- Installation Method: ProtonUp-QT

## Issue Description
I followed the officially documented guidelines for installation on SteamOS. I set everything right, and appeared to be working just fine, until I ran MO2. It refuses to open at all, I click it multiple times, it just sits. Sometimes when the splash screen does appear to download stuff, it never extracts or progresses the operation forward. I followed some steps that fixed this issue for others. I downloaded a local Mo2 v2.4.4.7z file and manually extracted that to the .config/steamtinkedlaucher/mo2 but that didn't change my result either. Ran out sources to attempt debugging. My Device is pretty much stock, I just got a few days ago, so there isn't much background clutter on the device. BTW the game I'm running steamtinker on is Fallout New Vegas. I also tried to go with the alternative which is Vortex, but that also was broken, but idc I'd prefer to use Mo2 anyways.

## Logs
Fri Nov 10 09:58:25 PM CST 2023 INFO - setflatpak - started SteamTinkerLaunch from /home/deck/stl/prefix/steamtinkerlaunch
Fri Nov 10 09:58:26 PM CST 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '22380'
Fri Nov 10 09:58:26 PM CST 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/deck/.local/share/Steam/steamapps/compatdata/22380'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Language from command line is 'english'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Seems like we have a Steam Deck here - making some specific settings
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Did not detect a running 'gamescope' process - assuming we're running in Desktop Mode
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Set 'FIXGAMESCOPE' to '0'
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Set 'SMALLDESK' to '1'
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Looks like we have a game but we're running from the Steam Deck install Prefix, not doing any updating here!
Fri Nov 10 09:58:26 PM CST 2023 INFO - steamdedeckt - Seems like we're being run by Steam here, not doing any installation steps
Fri Nov 10 09:58:26 PM CST 2023 INFO - setLocalInstall - Looks like we don't have a local non-root install
Fri Nov 10 09:58:26 PM CST 2023 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/deck/stl/prefix/collections' in config 'global.conf'
Fri Nov 10 09:58:26 PM CST 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'fav 22380 set'
Fri Nov 10 09:58:26 PM CST 2023 INFO - saveOrgVars - Storing some original variables to restore them later
Fri Nov 10 09:58:26 PM CST 2023 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Fri Nov 10 09:58:26 PM CST 2023 INFO - emptyVars - Set $PATH to '/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/deck/stl/deps/usr/bin::/home/deck/stl/deps/usr/bin:'
Fri Nov 10 09:58:26 PM CST 2023 START - ######### Initializing Game Launch 22380 using SteamTinkerLaunch v12.12 #########
Fri Nov 10 09:58:26 PM CST 2023 INFO - main - Starting with a clean log
Fri Nov 10 09:58:26 PM CST 2023 INFO - main - Start creating default configs
Fri Nov 10 09:58:26 PM CST 2023 INFO - createDefaultCfgs - START
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Language from command line is 'english'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Fri Nov 10 09:58:26 PM CST 2023 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Fri Nov 10 09:58:26 PM CST 2023 INFO - createDefaultCfgs - setSteamPaths:
Fri Nov 10 09:58:26 PM CST 2023 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Fri Nov 10 09:58:26 PM CST 2023 INFO - getGameOS - Starting game OS detection
Fri Nov 10 09:58:26 PM CST 2023 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Fri Nov 10 09:58:26 PM CST 2023 INFO - setWin - '' determined to be a Windows Game
Fri Nov 10 09:58:26 PM CST 2023 INFO - createDefaultCfgs - createProtonList:
Fri Nov 10 09:58:26 PM CST 2023 INFO - createDefaultCfgs - createProtonList end
Fri Nov 10 09:58:26 PM CST 2023 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Fri Nov 10 09:58:26 PM CST 2023 INFO - createDefaultCfgs - STOP
Fri Nov 10 09:58:26 PM CST 2023 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Fri Nov 10 09:58:26 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/deck/.local/share/Steam/steamapps'
Fri Nov 10 09:58:26 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'
Fri Nov 10 09:58:26 PM CST 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_sniper:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared'
Fri Nov 10 09:58:26 PM CST 2023 INFO - main - Checking internal dependencies:
Fri Nov 10 09:58:27 PM CST 2023 INFO - checkIntDeps - Skipping yad version check on SteamDeck
Fri Nov 10 09:58:27 PM CST 2023 INFO - main - Initializing first Proton:
Fri Nov 10 09:58:27 PM CST 2023 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Fri Nov 10 09:58:27 PM CST 2023 INFO - initFirstProton - Initializing Proton
Fri Nov 10 09:58:27 PM CST 2023 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/deck/.config/steamtinkerlaunch/default_template.conf' is 'proton-8.0-4c'
Fri Nov 10 09:58:27 PM CST 2023 INFO - main - Initializing default window resolution
Fri Nov 10 09:58:27 PM CST 2023 INFO - setInitWinXY - Using '1280x800' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Fri Nov 10 09:58:27 PM CST 2023 INFO - main - Welcome to SteamTinkerLaunch
Fri Nov 10 09:58:27 PM CST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/appinfo'
Fri Nov 10 09:58:27 PM CST 2023 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/header'
Fri Nov 10 09:58:27 PM CST 2023 INFO - main - Checking command line: incoming arguments 'fav 22380 set'
Fri Nov 10 09:58:27 PM CST 2023 INFO - getGameName - Found Game Name '"Fallout New Vegas"' in '/home/deck/.config/steamtinkerlaunch/gamecfgs/id/22380.conf'
Fri Nov 10 09:58:27 PM CST 2023 INFO - getGameName - Outgoing game name is 'Fallout New Vegas'
Fri Nov 10 09:58:27 PM CST 2023 INFO - pollWinRes - Creating initial '/home/deck/.config/steamtinkerlaunch/guicfgs/1280x800/22380/SteamTinkerLaunch-FavoritesSelection.conf' with unused default values
Fri Nov 10 09:58:27 PM CST 2023 INFO - setShowPic - Determining game picture
Fri Nov 10 09:58:27 PM CST 2023 INFO - setShowPic - Using '/home/deck/.config/steamtinkerlaunch/games/header/22380.jpg' as game picture
Fri Nov 10 09:58:27 PM CST 2023 INFO - favoritesMenuEntries - Using global favorites preset for preselecting some entries
Fri Nov 10 09:59:31 PM CST 2023 INFO - setGuiFavoritesSelection - Selected CANCEL - creating empty '/home/deck/.config/steamtinkerlaunch/favorites.conf' to skip asking again
Fri Nov 10 09:59:31 PM CST 2023 INFO - goBackToPrevFunction - 'setGuiFavoritesSelection' closed

**Comment by sonic2kk** [comment] 2023-11-11 04:53
You're using SteamTinkerLaunch v12.12. You should try using SteamTinkerLaunch from git. Also, if you installed SteamTinkerLaunch via package manager, you probably disabled the read-only filesystem, which is incorrect. Just download STL from the master branch and double click the `steamtinkerlaunch` script. Installing packages via Pacman on SteamOS is not a good idea (I hear Nix might be coming to SteamOS, but I doubt this is the Nix build).

The log you posted is incomplete, is doesn't look like a log for STL ModOrganizer 2 installation, but based on #973, I suspect the issue is 
1.  STL v12.12 is too old, you should always use STL git, especially on a very low priority system like the Steam Deck
2. MO2 is actually using v2.5.0rc1. Downloading 2.4.4 won't fix the issue, as STL will still download v2.5.0rc1. There was a fix just a few hours ago to ignore the pre-release builds.

Try using STL-git, and removing the existing ModOrganizer 2 installation at `~/.config/steamtinkerlaunch/mo2`. Just the whole `mo2` folder. Then, remove `~/.config/steamtinkerlaunch/downloads/mo2` to remove any old MO2 executables, just to be safe.

In future, please search through closed issues (you might've spotted #973), and [read the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck) to see that SteamTinkerLaunch git should always be used on SteamOS. This specific fix was [also mentioned on the changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) under "fixes".

Using STL git with a fresh prefix should resolve the issue.

**Comment by sonic2kk** [comment] 2023-11-11 05:01
I'm fairly sure this is a case of using an unsupported version of SteamTinkerLLaunch and a duplicate of the pre-release MO2 issue from #973. If you're having trouble getting ModOrganizer 2 to download after that, that's a network issue, as I just re-tested and it's working, so you could try restarting your device, but that's not really an issue I can fix.

Feel free to re-open, with installation logs and Wine output just like what was provided in #973, if ModOrganizer 2 v2.4.4 still doesn't work from STL-git. If you're using SteamOS 3.5, you'll need an updated version of `innoextract` bumped to `1.9-8`, which for the moment you'll have to install manually (you can download it from the [Arch Linux mirrors](https://archive.archlinux.org/packages/i/innoextract/innoextract-1.9-8-x86_64.pkg.tar.zst) - Download it and install it to `~/stl/deps/usr/bin`, overwriting the existing file should work). Once SteamOS 3.5 is out in stable, #931 will be merged and the dependency can be updated with `steamtinkerlaunch cleardeckdeps` so all dependencies will be refreshed.

**Closed as completed** 2023-11-11 05:03 UTC
Labels: bug, duplicate, ModOrganizer 2
