### ISSUE TITLE
FlawlessWideScreen does not start

### ISSUE THREAD

**Issue by WildPenquin** [sonic2kk/steamtinkerlaunch#1006] opened 2024-01-10 19:41 UTC
## System Information
- SteamTinkerLaunch version: 12.12
- Distribution: Arch Linux
- Installation Method: from AUR

## Issue Description

FlawlessWideScreen does not start, when enabled from game preferences.

FlawlessWideScreen is installed automatically by steamtinkerlaunch in `~/.config/steamtinkerlaunch/downloads/flawlesswidescreen/64/` (there is a typo in the wiki), but it's window never pops up.

I've also installed MangoHud and gamemode (at least mangohud runs correctly).

I'm running GTAV (and intend to install updated plugin for GTAV from wsgf into flawlesswidescreen).

## Logs

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13892745/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2024-01-10 21:40
Sounds like a duplicate of #996. Should be fixed by updating to latest git, this was noted on the changelog as fixed too.

In general, when software hasn't had a release in a while, it's good to avoid using an old version. You might also want to search through closed issues before opening a new one, which the issue template also encourages.

If the issue persists you'll need to do more troubleshooting to figure out what causes the problem because it launches for me since #996.

**Closed as completed by sonic2kk** 2024-01-10 21:40 UTC
Labels: bug, duplicate

**Comment by sonic2kk** [comment] 2024-01-10 21:56
Also, fyi, the log you attached is not from the game log as the issue template requests, it's from when you ran `--version`.

If the issue is not fixed you will need to provide a fixed log from an attempted game launch, and the technical information about the steps you did before opening an issue (any Wine logs or debug information, check if the FlawlessWidescreen EXE is valid, does it run with Wine in general on your system, etc)

**Comment by WildPenquin** [comment] 2024-01-11 11:31
Oops! I forgot I had run `--version` =).

You got me for not searching for "closed" issues (I usually do, sorry!).

Just a few comments from a user POW:

- FWIW it seems like this is the latest release. Are people assumed to just use the latest GIT?
- I can not find this in any changelog (which one are you referring to?). Not that it matters, but other users might not be able to find it, either.

Keep up the good work!

**Comment by sonic2kk** [comment] 2024-01-11 19:40
No problem! I'm sorry for being a bit harsh in my reply, reading back I should've made an effort to be a bit more polite.

> FWIW it seems like this is the latest release. Are people assumed to just use the latest GIT?

I had hoped people would move over to it, since my hope was to stop making releases, but that has since changed with the planned release of v14.0 later this year (see #992).

Right now it's best to use the latest git, since there are a huge amount of changes. If people aren't using git, I can't imagine how broken STL must be for them to be honest!

> I can not find this in any changelog

The changelog is available [on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) as the first page under "Quick Links", and it is also linked to on the Readme, at the bottom of the "[What Does It Do?](https://github.com/sonic2kk/steamtinkerlaunch#what-does-it-do)" section. The part of the changelog in question is under "[Fixes](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog#fixes)" (note for anyone reading in future, this will be under the "v14.0" subheading):

> FlawlessWidescreen: Increase startup delay from `2` seconds to `5` seconds, giving more time to detect game process

There is no PR attached because the change was pushed directly to master with 9366dd440fe11bf43412e9fb1c3a35290a1ee61f, as it was a very small change.

<hr>

I didn't make this clear, but I think FlawlessWidescreen not starting is a byproduct of STL v12.12 being very outdated, along with the process simply not having enough time to start. The way Steam juggles processes in the Proton prefix has changed a bit in recent months, and the main workaround is to add a delay on the STL side.

The magic number in my tests across different hardware has been `5`, but I plan to make this configurable, similar to the delay we have for custom program launches.

**Comment by WildPenquin** [comment] 2024-01-14 16:57
Thanks for your reply! All is clear now.

I didn't take your reply as harsh at all. There was just some confusion here still =). Keep up the good work!
