### ISSUE TITLE
Does STL now install MO2 2.5 by default?

### ISSUE THREAD

**Issue by Montag-451** [sonic2kk/steamtinkerlaunch#1126] opened 2024-06-16 18:20 UTC
I installed STL 12.12 on my OpenSuse Tumbleweed installation using ProtonTricks. I made sure I had all the dependencies first including YAD. It installed fine. Then I clicked Mod Organizer 2 assuming it would install version 2.4.4 because the Github installation guide said 2.4.4 was hard wired into STL. However. MO2 2.5 Rel 2 got installed instead. 

I went ahead and tried running Fallout 4 with it using Proton GE 9.7. Fallout started fine but after the opening cut-scene when you end up at the bathroom mirror to create your character, all sound disappeared. I can interact and move around just fine, just no sound. I tried changing to Proton Experimental but same problem. All of this was with no mods installed.

So my question is has STL now been updated to use MO2 2.5 or do I need to find a way to force it to use 2.4.4 instead? To do the latter, I assume I will need to remove STL completely first, then manually install using 2.4.4. If 2.5 is now supported, then my sound problem must be related to some other issue that I haven't found, yet. Thanks.

**Comment by sonic2kk** [comment] 2024-06-16 19:14
This probably isn't related to the ModOrganizer 2 version or SteamTinkerLaunch.

You are using SteamTinkerLaunch v12.12 which is over a year out-of-date. You should be using SteamTinkerLaunch from master, as the issue template notes (which you removed from your OP despite filing this as a bug).

SteamTinkerLaunch v12.12 was not pinned to a specific MO2 version, so it would always download the latest, including the latest pre-release. This is fixed on master, [as the changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog) (which the issue template directed you to read) notes.

Information on ModOrganizer 2.5.0 not being supported, and how to downgrade to v2.4.4 is available on the [ModOrganizer 2 wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250). You don't need to remove SteamTinkerLaunch completely, just the ModOrganizer 2 installations. Feel free to back up your mod folders. You can find the paths where MO2 put your mods in the MO2 settings.
- There was discussion around updating to v2.5.0 as the default for v14.0 (#1110), but the jury is still out on whether it truly works with Proton yet (there are mixed reports)

All SteamTinkerLaunch wiki information relates to the latest available version, which is strictly not releases. Releases could be, at best, some months out-of-date. Since SteamTinkerLaunch is not compiled and is just a Bash script it is best to use the latest version from master, similar to what one would do with Winetricks.

<hr>

However, irrespective of all of this, this is not related to SteamTinkerLaunch and more than likely not related to ModOrganizer 2.5.0. This is likely an issue specific to GE-Proton9-7, a mod, or something else. I don't think the ModOrganizer 2 version is relevant here. I do not think that ModOrganizer 2 v2.5.0 caused your problem here. A similar issue was reported a while back for Fallout: New Vegas where the audio source was changing incorrectly, perhaps that is happening here? The issue was caused by a missing 32bit PipeWire dependency on the user's system: #1115 (not a SteamTinkerLaunch dependency, but a Wine dependency).

However, I will iterate again, please do not use releases of SteamTinkerLaunch, as you are blocking yourself out from the latest features and fixes. There will eventually be another release but this is not an excuse to not use master. The readme will be made clearer on this prior to v14.0's release.

<hr>

Closing this as the ModOrganizer 2 version is very likely not relevant here and SteamTinkerLaunch is probably irrelevant here as well.

**Closed as completed by sonic2kk** 2024-06-16 19:14 UTC
Labels: bug, ModOrganizer 2

**Comment by Montag-451** [comment] 2024-06-16 23:55
Thank you. I didn’t intentionally delete the change log you mentioned nor did I see it, but I will try the master file. You can delete my bug post if you like or I will if the system will let me. I do think STL is a cool program. I just need to learn it better.


Sent from Yahoo Mail for iPad


On Sunday, June 16, 2024, 2:15 PM, Eamonn Rea ***@***.***> wrote:




This probably isn't related to the ModOrganizer 2 version or SteamTinkerLaunch.

You are using SteamTinkerLaunch v12.12 which is over a year out-of-date. You should be using SteamTinkerLaunch from master, as the issue template notes (which you removed from your OP despite filing this as a bug).

SteamTinkerLaunch v12.12 was not pinned to a specific MO2 version, so it would always download the latest, including the latest pre-release. This is fixed on master, as the changelog (which the issue template directed you to read) notes.

Information on ModOrganizer 2.5.0 not being supported, and how to downgrade to v2.4.4 is available on the ModOrganizer 2 wiki page. You don't need to remove SteamTinkerLaunch completely, just the ModOrganizer 2 installations. Feel free to back up your mod folders. You can find the paths where MO2 put your mods in the MO2 settings.

All SteamTinkerLaunch wiki information relates to the latest available version, which is strictly not releases. Releases could be, at best, some months out-of-date. Since SteamTinkerLaunch is not compiled and is just a Bash script it is best to use the latest version from master, similar to what one would do with Winetricks.

However, irrespective of all of this, this is not related to SteamTinkerLaunch and more than likely not related to ModOrganizer 2.5.0. This is likely an issue specific to GE-Proton9-7, a mod, or something else. I don't think the ModOrganizer 2 version is relevant here. I do not think that ModOrganizer 2 v2.5.0 caused your problem here. A similar issue was reported a while back for Fallout: New Vegas where the audio source was changing incorrectly, perhaps that is happening here? The issue was caused by a missing 32bit PipeWire dependency on the user's system: #1115 (not a SteamTinkerLaunch dependency, but a Wine dependency).

However, I will iterate again, please do not use releases of SteamTinkerLaunch, as you are blocking yourself out from the latest features and fixes. There will eventually be another release but this is not an excuse to not use master. The readme will be made clearer on this prior to v14.0's release.

Closing this as the ModOrganizer 2 version is very likely not relevant here and SteamTinkerLaunch is probably irrelevant here as well.
