### ISSUE TITLE
Steam Tinker Launch fails to start or install vortex

### ISSUE THREAD

**Issue by TheSaneWriter** [sonic2kk/steamtinkerlaunch#367] opened 2021-12-05 01:14 UTC
Ever since I updated to v.8.0, Steam Tinker Launch has been unable to start or install Vortex, throwing up multiple errors about not recognizing commands or being able to complete downloads. To be exact, my terminal says this:

steamtinkerlaunch vortex start
Sat Dec  4 08:09:17 PM EST 2021 INFO - setDotNetWine - Downloading: 'https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/download/Proton-6.17-STL-1/Proton-6.17-STL-1.tar.gz'
Sat Dec  4 08:09:23 PM EST 2021 ERROR - setDotNetWine - DNPROTON '' was not found - can't continue
/usr/bin/steamtinkerlaunch: line 11633: : command not found
/usr/bin/steamtinkerlaunch: line 11643: : command not found

For the convenience of anyone checking this out, here's the log file.
[steamtinkerlaunch.log](https://github.com/frostworx/steamtinkerlaunch/files/7655034/steamtinkerlaunch.log)

Does anyone know of any fixes? For now I'll revert to version 7.0, but if there's anything I could do on my end to fix this that would be great. Thanks!

**Comment by frostworx** [comment] 2021-12-05 08:31
`Sat Dec  4 08:09:23 PM EST 2021 INFO - notiShow - Message 'Archive 'https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/download/Proton-6.17-STL-1/Proton-6.17-STL-1.tar.gz' does not contain a Proton file - not extracting' `

looks like your download is is broken.
please remove the downloaded file and try again _(github had serious download problems recently, likely related)_

_(of course the message should point to the downloaded file and not the source url and line 11633 should not be reached when the proton command is not available - fixing this)_

**Comment by frostworx** [comment] 2021-12-05 08:53
I could not reproduce your problem here, so very likely the problem was a broken downloaded as suspected.
_(already fixed above glitches btw)_

**Comment by frostworx** [comment] 2021-12-05 09:50
Just [added](https://github.com/frostworx/steamtinkerlaunch/commit/f87116283b4febbaa4e5b771eb797a9aa5634dd9) a checksum check for already downloaded Proton archives where available _(so `GE` and `STL`)_.
Before only archives just downloaded were checked.

**Comment by TheSaneWriter** [comment] 2021-12-05 14:55
Thanks, it's all fixed. I redownloaded version 8.0, found and deleted my proton download, and it redownloaded and is now working.

**Comment by frostworx** [comment] 2021-12-05 15:06
Thanks for confirming. *closing here*

**Closed as completed by frostworx** 2021-12-05 15:06 UTC
