### ISSUE TITLE
Inaccurate games list for Vortex support

### ISSUE THREAD

**Issue by 62832** [sonic2kk/steamtinkerlaunch#764] opened 2023-03-18 22:31 UTC
## System Information
- **SteamTinkerLaunch version:** v12.12
- **Distribution:** Artix Linux
- **Installation Method:** AUR package ([`steamtinkerlaunch`](https://aur.archlinux.org/packages/steamtinkerlaunch))

## Issue Description
Been trying to make use of STL to install mods for Borderlands 2 via Vortex and I can't seem to figure it out. I noticed eventually that Vortex, as run through the game I'm trying to mod, isn't actually returning BL2 as an available game to mod. I took a look at the "Games" list under STL's Vortex menu to see if something is missing, and I see this.
![image](https://user-images.githubusercontent.com/5098830/226143443-62902cc6-ff03-4eed-b631-aca0deab8bba.png)
The thing is, I've never actually installed Ace Combat 7. I don't even _own_ Ace Combat 7, yet it shows up as the only available game for Vortex support.

Am I missing something here or is something going horribly wrong?

## Logs
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11009759/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2023-03-18 22:44
That games list is definitely incorrect. It should be the same but what happens if you run `steamtinkerlaunch vortex li`? Does Borderlands 2 show up in this list?

<hr>

However this bug aside, you should still be able to manually add and mod Borderlands 2 via Vortex.

Borderlands 2 is available as a native game, but Vortex only supports modding the Windows release of games, so ensure that you're using the Proton build. Some of the logging in the log file hints that this may be the native release of Borderlands 2.

**Comment by 62832** [comment] 2023-03-18 23:05
~~No, actually, I had to force the Windows version of BL2 since about half of the DLC packs for it aren't actually available on native Linux. So I am in fact running it under Proton.~~ Scratch that, I'm actually not sure how I would verify if it's running the correct build when I specify Steam Tinker Launch as the compatibility tool.

That said, the command line option gave the exact same output of nothing but `Ace Combat 7: Skies Unknown ()`.

**Comment by sonic2kk** [comment] 2023-03-18 23:09
Borderlands isn't showing up for me either, and it also doesn't appear in the unpacked Vortex plugins. I guess that would explain why it isn't showing up. I booted up Vortex and support for it is provided through an extension, so it is not natively supported by Vortex (yet).

This is likely why it isn't showing up, however the games list should not show games you don't own, so that in itself is still a bug. Though Borderlands 2 not showing up is expected behaviour from what I can tell - If a game isn't in `~/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/resources/app.asar.unpacked/bundledPlugins`, then it isn't something Vortex ships support for and so not something STL will detect as an Vortex support game as, really, it *isn't* supported *by Vortex*, it requires the extension.

You should be able to manually add Vortex to Nexus and mod it that way I believe, so there should be no bug to this end :-)

EDIT: Just did exactly this and it seems to work. Did not install any mods but I was able to install the extension and manually add Borderlands 2.

<hr>

> Scratch that, I'm actually not sure how I would verify if it's running the correct build if I specify Steam Tinker Launch as the compatibility tool.

If STL is forced as the compatibility tool, you are using the Windows build. If you're using `steamtinkerlaunch %command%`, you're using the native build. When you force STL as the compatibility tool, the Windows build will *always* be downloaded ([see here](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Compatibility-Tool)).

> That said, the command line option gave the exact same output of nothing but `Ace Combat 7: Skies Unknown ()`.

Thanks for checking. I would guess that perhaps a game you have is being parsed incorrectly by SteamTinkerLaunch and thus is bugging out the games list. The brackets are where the AppID is meant to go, but since you don't actually own this game, STL can't fetch the AppID for it, so it's showing up blank.

**Comment by 62832** [comment] 2023-03-18 23:16
If it's any clarification, I have on occasion gone through things like SteamDB's free packages page to claim licenses for old shit before. I presume there must be some weird app ID acquired from there that's throwing STL off.

Also, I had seen BL2 in the list of supported games under `/usr/share/steamtinkerlaunch/misc` and just assumed it would work more or less. I'm eager to know what to do instead as a workaround for this game, however, for installing and playing BL2 with mods. Something like a dedicated Vortex installation for any and all such games on my end, maybe?

**Comment by sonic2kk** [comment] 2023-03-18 23:26
> Something like a dedicated Vortex installation for any and all such games on my end, maybe?

Not at all! All you have to do is add Borderlands 2 manually to the existing STL Vortex installation. Enable the Vortex checkbox for your game under the Game Menu (should be towards the bottom), then just start the game. You should get a prompt asking you to start Vortex. Then you can manually search for your game in Vortex, click on it and Vortex will tell you it needs to install an extension for the game. It'll do than and then restart. Sometimes Vortex freezes after installing an extension so you may need to restart it (just restart your game, you'll get prompted to open Vortex again after the wait requester). Then you can search for Borderlands 2 in Vortex again and manually add it. You'll have to browse for the path using Wine's ugly file browser but there's not much that anyone can do about that on the STL side :-)

Not sure where the confusion on this came from, but you can launch Vortex with any STL game. Whether or not the game is supported by Vortex is another matter entirely.

> Also, I had seen BL2 in the list of supported games under /usr/share/steamtinkerlaunch/misc and just assumed it would work more or less.

This list just includes every game that Vortex may eventually support. If Vortex ever stops relying on an extension and ships native support, it will probably work. Though the game list parsing issue could get in the way of that, I'm not sure.

<hr>

> If it's any clarification, I have on occasion gone through things like SteamDB's free packages page to claim licenses for old shit before. I presume there must be some weird app ID acquired from there that's throwing STL off.

It's possible that this could be it. I had a lot of issues similar to this pre-v12 with the games list which I managed to fix. It's definitely possible there's a scenario that I couldn't account for.

I looked through the log again and the output for the current Vortex game is really strange. The log line that's meant to show the current game is just listing every game in the Vortex games file for some reason. This definitely seems like a parsing issue, so there's some kind of bug on the STL side here...

**Comment by sonic2kk** [comment] 2023-03-18 23:42
You could do a list for `steamtinkerlaunch list installed` and see if you have any games that have quotes or some other sort of strange characters that could potentially break parsing. From skimming the code (wasn't written by me so I'm not fully familiar with it) it looks like it should check based on AppID rather than names. Probably the main thing I would look for is any games that have double quotes (`"`) in the name. I checked and I don't own any games that have quotes in the name and don't recall ever seeing any on Steam with this. I do own some games with some crazy names including those with emojis, but they still work.

Quotes and semicolons are the main things that come to mind to check for, but I've already verified that games I have installed with semicolons work fine (`STEINS;GATE`, `CHAOS;HEAD NOAH`, `Hyperdimension Neptunia Re;Birth1`). So quotes are the last thing that come to mind to check for.

It's possible that the `list installed` command could return garbage, which could also be a hint at something going wrong here, as the Vortex games parsing code and the list installed code use some of the same internal functions, and if those functions aren't parsing your library correctly then that could be a hint!

**Comment by 62832** [comment] 2023-03-18 23:48
Listing installed games might not be the answer here, since that appears to be going through `appmanifest` files and pulling the names of the games from their respective manifest and app ID.

**Comment by sonic2kk** [comment] 2023-03-18 23:54
Hmm, perhaps not. I'm just not sure why the games are being parsed incorrectly. I definitely think there's *something* that STL isn't accounting for, but I'm not sure what it could be...

**Comment by sonic2kk** [comment] 2023-03-19 00:21
You can use `steamtinkerlaunch list installed id` which will list all installed AppIDs. If the output looks strange (blank, or not displaying AppIDs you recognise if you recognise any at all :sweat_smile:), that could be a potential hint.

**Comment by 62832** [comment] 2023-03-19 00:27
No luck there either, that one's all clear.
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11009922/steamtinkerlaunch.log)

Here's another log for the prior command (no `id` option) listing out full game manifests too. I indeed have 61 titles currently installed, three of which are the Steam runtime itself and its common redists along with Proton.
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11009923/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2023-03-19 00:43
Thanks for testing!

I suspect then that it's the cutting in the Vortex games list file that's causing the issues, though I'm not sure why.

Since the Vortex `li` command is also falling over and giving bad output, I suspect that the problem lies in either the splitting of the installed Vortex game entries (`INSTALLEDVTXNAME="$( grep "$INSTALLEDVTXAID" "$VORTEXGAMES" | cut -d ";" -f 2 | cut -d '"' -f 2 )"`, similar logic is applied for both `li` and the Games Dialog in `VortexGamesDialog`), or the `getInstalledGamesWithVortexSupport` function. The latter function should also only be working off of AppIDs so I'm not sure what could be going on...

**Comment by sonic2kk** [comment] 2023-03-19 00:54
Aha! I was able to re-create the problem by having a blank installed Vortex AppID!

Inside of `VortexGamesDialog`, inside the while loop for `VINGAMES=`, I set `f=""` for each entry and got this result. Even right down to seeing Ace Combat as the defaulted game!

![image](https://user-images.githubusercontent.com/7917345/226147903-f6363bf4-7f63-4f06-8efa-5b3ab1adf6bc.png)

All of these entries are for actual Vortex-supported games I have installed.

Could you check if you have a `vortexgames.txt` file at `/usr/share/steamtinkerlaunch/misc`? You can also run `cat /usr/share/steamtinkerlaunch/misc/vortexgames.txt`. This should return the entire contents of the file.

If the output of this file does not look correct we may be onto something.

I took a look at the `PKGBUILD` on the AUR. Reading these files is certainly not my specialty (my main exposure to them has been recently with debugging some SDL2 issues), but I believe the path I provided should be correct (https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=steamtinkerlaunch#n45). I think the PKGBUILD should put the STL files into `/usr/share/steamtinkerlaunch`.

**Comment by 62832** [comment] 2023-03-19 10:28
I do indeed have the `vortexgames.txt` file. This is what I used to check if Borderlands 2 was supported to begin with, and there seems to be nothing wrong with the contents either when using `cat`. However, I find it odd that AC7 is only the *second* game on that file's list while the first game is actually 7 Days to Die.

Also, just one more thing I noticed is that I actually have multiple games installed — albeit all on a separate partition to BL2 except for GTA V — that fall under the Vortex games list.

- Counter-Strike: Source
- Dying Light
- Grand Theft Auto V
- Slime Rancher
- Team Fortress 2
- Yakuza 4 Remastered.

Even so, the list of games under STL's Vortex menu stops at AC7 despite me not owning it or having it installed.

**Comment by sonic2kk** [comment] 2023-03-19 13:24
> This is what I used to check if Borderlands 2 was supported to begin with

Ahh my mistake, I thought you checked on the repo, I gotcha now :-) 

> However, I find it odd that AC7 is only the second game on that file's list while the first game is actually 7 Days to Die

I also found this quite strange, I'm not sure why in the test case I created and your issue that it's showing the wrong games list.

I own almost all of the games you listed, I may try installing them later and seeing if I can re-create the issue with any of them.

It may also be interesting to check `~/.config/steamtinkerlaunch/vortex/compatdata` and seeing if you have a `seenvortexgames` text file. I think it's in the compatdata folder, or it may be in a `pfx` folder if Vortex has one, I don't quite remember off the top of my head 😅 

That file is appended to each time STL sees a game in the Vortex app.asar folder that matches an entry in `vortexgames.txt`.

**Comment by 62832** [comment] 2023-03-19 15:45
Haven't been able to find such a `seenvortexgames` file anywhere, I'm afraid. Though, the fact that this *is* meant to be present suggests that something is in fact going wrong with the game detection.

**Comment by sonic2kk** [comment] 2023-03-19 16:00
Hmm, have you definitely installed and opened Vortex with SteamTinkerLaunch? Either with `steamtinkerlaunch vortex start` or by enabling it for your game in the Game Menu and launching the game with SteamTinkerLaunch. The file should always exist if Vortex has at least been opened, though it may be empty or have invalid data in this instance which is sort of what I was expecting.

**Comment by 62832** [comment] 2023-03-19 16:01
My mistake, I'd forgotten to start it up again since I was habitually clearing my config directory trying to get to the bottom of this. I'll get back with a reply right away when I see it.

**Comment by 62832** [comment] 2023-03-19 16:08
Hmm. No, it's still not there. However, I do notice some console output from `sed` when using the start command which looks to me (as someone who doesn't use `sed`, mind) like it could be an error.

`sed: -e expression #1, char 0: no previous regular expression`

**Comment by sonic2kk** [comment] 2023-03-19 16:09
Actually, it may be because most of the games you seem to have available rely on a third-party extension for Vortex support.
- Borderlands 2
- Counter-Strike: Source
- Dying Light
- Grand Theft Auto V
- Slime Rancher
- Yakuza 4 Remastered

The only outlier here is TF2, but that is available as native game. I might sound like a broken record here but is TF2 using Proton? I haven't ever modded TF2 so I'm not sure what mod parity is like.

Regardless, I would've just assumed that if there were no Vortex support games, then would've created a blank file, but perhaps not.

<hr>

> `sed: -e expression #1, char 0: no previous regular expression`

That is quite interesting. I'll have a look at where `sed` is used in and around the Vortex startup code :+1:

**Comment by 62832** [comment] 2023-03-19 16:12
TF2 is currently installed as native, so no Proton there. I also don't understand `>what Nexus meant by this` given that the game already has a modding presence on both Steam Workshop and GameBanana.

**Comment by sonic2kk** [comment] 2023-03-19 16:20
I'm not sure where the `sed` command causing the problem is located exactly but I did some testing in my terminal and that error would come back if one of the values passed to `sed` is blank, i.e. if there was something like `sed "s:$GAMENAME:blah:g"`, and `$GAMENAME` was empty, then `sed` would give this exact error.

So somewhere along the way, I think a variable being passed to `sed` is blank. And it is probably blank because of a deeper issue somewhere in STL that isn't parsing the games properly. That's my thinking for now anyway :-)

**Comment by sonic2kk** [comment] 2023-03-19 16:22
It may be interesting to see a log from `steamtinkerlaunch vortex start`. If you run that command and then attach a fresh log from `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`, perhaps  there would be a hint here. Maybe there are some empty values being logged which shouldn't be empty.

**Comment by 62832** [comment] 2023-03-19 16:25
Yep, does seem to be some kind of empty name being thrown in.
`Sun 19 Mar 16:22:52 GMT 2023 SKIP - prepareVortexGame - Skip game '' is not supported by Vortex or the ID is not listed in '/usr/share/steamtinkerlaunch/misc/vortexgames.txt'`
[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/11011632/steamtinkerlaunch.log)

**Comment by 62832** [comment] 2023-03-19 16:30
Is there by any chance any way to specify a more verbose log to be generated, i.e. each step of the way for each game being added to the log/output?

**Comment by sonic2kk** [comment] 2023-03-19 16:46
> Is there by any chance any way to specify a more verbose log to be generated, i.e. each step of the way for each game being added to the log/output?

Not currently but this is something I thought about adding before, I just never got around to it (probably it would be quite straightforward, it would be adding the verbose logging statements that would be the most lengthy part haha).

The log statement is formatted as such: `[DateTime] [LogType] - [FunctionName] - [Log Message]`. So the `prepareVortexGame` part here is the function that the log is being called from. Though it isn't each step of the way, this is how issues are traced.

> Yep, does seem to be some kind of empty name being thrown in.

Hoho, I wonder why this is coming back. `prepareVortexGame` is indeed called from `startVortex`. Looking at my log every found Vortex game is correctly shown so the log statement you provided only makes me more confident that this is some sort of parsing issue.

<hr>

I don't see any immediate place that `sed` is used here but I think given that there's an empty game name, I think somewhere that `sed` is used, it expects to take a game name. And since this is blank, some part of the code that is shared between the Vortex games list logic and the logic used to detect Vortex games is getting a blank value and falling over.

The solution here I think is to figure out why blank values are getting to `sed` at all (and potentially other parts of the code) and how to stop them from getting there.

**Comment by 62832** [comment] 2023-03-19 16:56
Would it help to add you on Steam directly in case I happen to have a specific title in my library that is throwing it off altogether?

**Comment by sonic2kk** [comment] 2023-03-19 17:07
Okay, so the `gVSIDs` is called to get all installed Vortex games' AppIDs and store them in an array called `INSTVGAMES`. This array is then passed to the Vortex games list GUI and used as part of its while loop to display all the installed games in the games dialog (`<<< "$(printf "%s\n" "${INSTVGAMES[@]}")"`).

If this array is blank (which I simulated by forcing it to `INSTVGAMES=("")` just before `VINGAMES` is set in `VortexGamesDialog`), then I get the output of only one game being in the games list, and that game is: Ace Combat 7.

![image](https://user-images.githubusercontent.com/7917345/226192016-add08948-dd6a-446d-9f3e-b784c26ab0e5.png)

This issue can be fixed by putting the following check in the while loop which builds `VINGAMES`:

```bash
VINGAMES="$(while read -r f; do
    if [ -z "$f" ]; then
        continue
    fi
    # ...
```

This explains the issue with the games list GUI. As for the `list-installed` command, it also relies on the `INSTVGAMES` array having a value. If this is not set, which I simulated again by forcing the array to be blank but this time in `getInstalledGamesWithVortexSupport`, then the output of the `steamtinkerlaunch vortex list-installed` command is... `Ace Combat 7: Skies Unknown ()`!

<hr>

I haven't found exactly what might be causing the `sed` error when starting Vortex but I would guess it is something very similar. In short, the issue here appears to be that STL is not finding any supported Vortex games, as all the games you mentioned require Vortex extensions, except for TF2 but as discussed it's a native game so it doesn't apply here :-)

The solution to the inaccurate games list appears to be that STL needs some checking for empty games list. Vortex support has been in place for almost 2 years it looks like, and somehow checks for having no supported Vortex games when viewing the games list was never caught. I can push a couple of changes that should fix the games list.

<hr>

As for actually modding your games, since they cannot be autodetected as they rely on extensions (so support isn't bundled *with* Vortex), it should just be a case of starting Vortex with STL, adding the extension (which Vortex should install for you automatically and then restart), and then manually entering the path to the game. It's a bit of a hassle but modding should work, at least I believe so.

SteamTinkerLaunch properly set the Borderlands 2 staging folder for me one I enabled the Vortex setting for the game on the Game Menu (force STL as the compat tool for Borderlands 2 > Start Game > Go the STL Main Menu > Open Game Menu > Towards the bottom there should be an "Enable Vortex" checkbox > Save and Play game). That created the Vortex staging folder on the drive I had with Borderlands 2 installed.

Having games in the `vortexgames.txt` file I believe helps with properly creating this staging folder, too, but I am not absolutely certain on that :sweat_smile: I have not tested any mods with Vortex for Borderlands 2 but all being well this should work to get you set up for modding.

<hr>

Thanks for taking so much time to help diagnose and troubleshoot the games list issue. I am fairly confident that having no Vortex games that have bundled Vortex support installed is the cause of the issue, and I'll get a commit up that should hopefully fix this. 

If you'd like to test that, once the fix is pushed: you can remove the AUR package (it will keep your `~/.config/steamtinkerlaunch` folder so no worries there), and then you can manually download and install SteamTinkerLaunch from the Makefile (`git clone https://github.com/sonic2kk/steamtinkerlaunch/ && cd steamtinkerlaunch`, then `sudo make install`). To go back to stable after testing, you can run `sudo make uninstall` (from the steamtinkerlaunch folder) and then re-install the AUR package.

> Would it help to add you on Steam directly in case I happen to have a specific title in my library that is throwing it off altogether?

I really appreciate the initiative here but I think we figured out the cause :-)

**Comment by 62832** [comment] 2023-03-19 17:14
Sounds good. I'll have a go at building STL from source and testing it out.

**Comment by sonic2kk** [comment] 2023-03-19 17:14
With 1236a6c3d21d49bb18a3d0bcbd8a044fbdadc599, this fix should be in place. If you'd like to test, you can install SteamTinkerLaunch from source manually. These are the steps to do that:
1. Remove the AUR package (if you use `yay`, it might be something like `yay -R steamtinkerlaunch`)
2. Download the repo: `git clone https://github.com/sonic2kk/steamtinkerlaunch`
3. Change into the repo folder: `cd steamtinkerlaunch`
4. Install: `sudo make install`

Then you should be able to close your terminal and re-open it (to refresh any environment variables etc), then run `steamtinkerlaunch version`. That should return `v14.0.20230319-1`. If that is the case, you can run `steamtinkerlaunch vortex list` and it should show an empty games list. You can also run `steamtinkerlaunch vortex li`, which should return an empty games list from the command line.

To roll back to stable STL, you can do the following:
1. `cd steamtinkerlaunch`
2. `sudo make uninstall`
3. Re-install AUR package

Good luck!

**Comment by sonic2kk** [comment] 2023-03-19 17:18
`steamtinkerlaunch vortex start` also appears to be relying on the `getInstalledGamesWithVortexSupport` function (which makes sense I just didn't realise until now), and so it is very possible that the empty array returned here is causing the `sed` warning. I'm going to push a similar fix that skips any blank Vortex game data coming back from being parsed :-)

**Comment by 62832** [comment] 2023-03-19 17:19
So far so good, though the only thing I'll say is that `steamtinkerlaunch vortex list` actually just prints the help menu as opposed to anything else. `li` gives no output as expected.

**Comment by sonic2kk** [comment] 2023-03-19 17:24
Ah, `vortex list` isn't a valid command, so that makes sense why it's just showing the help screen.

Glad to hear the rest is working as expected though! This issue was probably around for quite a long time but somehow no one noticed, sorry you ran into it. All being well though your modding should go smoothly enough :-) Thanks for all the patience with this issue. I'll leave it open for a while to let you do any further testing and for any potential further discussion, but if the games list issue is resolved and you can manually configure Borderlands 2 within Vortex, hopefully this issue is solved.

Borderlands 2 seems to be working on my end at least:

![image](https://user-images.githubusercontent.com/7917345/226195041-00dca2a4-356a-450f-a645-c2ea1342eaeb.png)

**Comment by 62832** [comment] 2023-03-19 18:00
The only thing I had qualms with over BL2 was the fact that every now and then Vortex would warn me that mods' files had been deleted when I did nothing to them (requiring me to revert... *some* change?), along with an issue that had already been brought up in #721 of only having Symlink Deployment available for Vortex. Hopefully that still doesn't cause any problems when actually playing a modded instance of BL2.

**Comment by sonic2kk** [comment] 2023-03-19 18:04
> along with an issue that had already been brought up in https://github.com/sonic2kk/steamtinkerlaunch/issues/721 of only having Symlink Deployment available for Vortex

As far as I know this is an issue with Vortex and Wine, and not something related to STL. It's unfortunate but I don't think there's anything I can do, and if there is a way to work around it it'll need to be someone from the community that contributes it, as I don't use Vortex.

Once upon a time, Vortex was a pain to get working on Linux but it was possible with workarounds. In the last year or so though, Vortex has gotten more and more unstable under Wine, and fresh installs actually broke for about a month.

As I don't use Vortex I cannot give too much help with Wine-specific issues, getting Vortex to the point where it opens is about as much help as I can provide I'm sorry to say. I hope your mods work but if they don't, I don't know if there's a whole lot else I can help with :frowning:

**Comment by 62832** [comment] 2023-03-19 18:05
No problem. Thanks at least for sorting out the game list issue.

**Comment by sonic2kk** [comment] 2023-03-19 18:06
For what it's worth, I can see Hardlink and Symlink available for me in my Borderlands 2 profile settings:

![image](https://user-images.githubusercontent.com/7917345/226197807-b17e0e0d-7211-41b2-87db-a867554bfdfe.png)

Maybe the staging folder for Borderlands 2 is not set properly? It should be `Z:\path\to\drive\Vortex\{GAME}\mods`, for me this is `Z:\run\media\user\Drive\Vortex\{GAME}\mods`.

If the file path is not valid or left at default (`{USERDATA}\{GAME}\mods` or something), then only symlink deploy is available.

**Comment by 62832** [comment] 2023-03-19 18:13
I have Borderlands installed on another SSD partition (as opposed to the HDD installation of Steam on my `home` directory), and this is mounted at a dedicated `/extra` directory. The staging directory I used for this was `/extra/_/Steam/vortex/borderlands2/mods` (and hence, presumably, `Z:\extra\_\Steam\vortex\borderlands2\mods` under WINE).

Is there a problem with this path as it stands?

**Comment by sonic2kk** [comment] 2023-03-19 18:17
The staging directory is set by SteamTinkerLaunch, it should be put on the root of the partition/drive, and it should have a capital V in `Vortex` (Linux paths are case-sensitive, unlike Windows where afaik they aren't).

So the path that SteamTinkerLaunch created should be `/extra/_/Vortex/borderlands2/mods`. If this path doesn't exist, that could be why Vortex isn't giving you the hardlink option. Inside the mods folder should be a plaintext file called `__vortex_staging_folder`. For me this file says `{"instance":"548a2c48-bfdc-4849-b48a-8694f2a7112e","game":"borderlands2"}`.

**Comment by 62832** [comment] 2023-03-19 18:25
Hah, so is my issue just the fact that I didn't have `vortex` start with a `V`? I'll have to give this another try.

**Comment by sonic2kk** [comment] 2023-03-19 18:29
That is possible, it may also be that the path itself doesn't exist: `/extra/_/Vortex/borderlands2/mods` - The `{GAME}` part that Vortex uses is substitutes with what Vortex calls a "domain", basically an all-lowercase no-space identifier for a game. In this case, it's `borderlands2`.

SteamTinkerLaunch should have created the folder on the drive/partition that Borderlands 2 was found on, assuming you started Vortex via Borderlands 2 with SteamTinkerLaunch as the compatibility tool (otherwise it won't have tried to detect and set up this directory in the first place). Vortex should be enabled on the Game Menu with the "Vortex" checkbox (should be near the bottom, it is for me), and then you can press "Save and Play".

![image](https://user-images.githubusercontent.com/7917345/226199091-4c471ec4-a04f-4976-aac9-f67e151b0436.png)

You'll then be prompted to open Vortex:

![image](https://user-images.githubusercontent.com/7917345/226199106-ac71c43c-747c-4e03-9dae-62d6c72e35dc.png)

And SteamTinkerLaunch will set up the staging folder:

![image](https://user-images.githubusercontent.com/7917345/226199117-1039ec72-f10d-4ae2-b068-a0522aad4ff0.png)

I believe it is possible to manually create the directories for games, as I think this is what was done manually before STL, but I'm not too sure about that.

**Comment by sonic2kk** [comment] 2023-03-19 18:36
I did notice that Vortex sometimes "forgets" where the game EXE is. Not sure if this a STL issue or Vortex issue or what, but once the path is added again, Vortex should remember your mods (since it remembers the path to the staging folder)

**Comment by 62832** [comment] 2023-03-19 19:06
Yeah, nah, even with the default staging directory selection the only contents of my `__vortex_staging_folder` are `{"instance":"empty","game":"NEXUSGAMEID"}`. STL chose the directory for this to be, equivalently, `Z:\extra\_\Steam\Vortex\borderlands2\mods`.

I would carry on further, but I feel like this might be out of scope for the initial issue by now.

**Comment by sonic2kk** [comment] 2023-03-19 19:24
Hmm, that is strange. SteamTinkerLaunch writes out this default line if the file doesn't exist, I guess this file is meant to be created by Vortex just from glancing at the code.

You could try removing the staging folder and seeing if that helps, and if not, you could try clearing the `__vortex_staging_folder` file and pasting in the following line: `{"instance":"548a2c48-bfdc-4849-b48a-8694f2a7112e","game":"borderlands2"}`

When I renamed the folder, once Vortex started up, it created the staging folder again and had the same line as before in the `__vortex_staging_folder`.

> I would carry on further, but I feel like this might be out of scope for the initial issue by now.

Maybe a bit but I like to try and help as much as I possibly can, even if I'm not super knowledgable on how Vortex works (on Windows or on Linux).

**Comment by sonic2kk** [comment] 2023-03-19 19:29
Vortex also gave me an option to "suggest" a new path. It was a button beside the mod staging folder textbox. I was able to click "suggest", then "apply" and Vortex created a new deployment folder with the same folder structure and that same text file with that very same line for `borderlands2` I gave.

![image](https://user-images.githubusercontent.com/7917345/226204218-42b834d5-6795-4936-a50e-5be9cc37adbb.png)

Switching back to the default `Vortex\{GAME}\mods` path also worked too.

Perhaps playing around with the path for the Borderlands 2 staging folder could help? I am not totally sure.

**Closed as completed** 2023-03-30 18:47 UTC
Labels: bug
