### ISSUE TITLE
Custom command set on its own and game crash

### ISSUE THREAD

**Issue by maplepy** [sonic2kk/steamtinkerlaunch#294] opened 2021-08-16 16:20 UTC
Using stl 6.13-1 on AUR but I've had this issue with every version in the past too

So basically, I changed some default settings to my liking for stl in the "DEFAULT" section. But whenever I'm trying to launch a game, it doesn't launch because of that "Custom Command" being empty or being linked to another game while it has to be the path to the game. I don't understand why I have to set the path for each game manually and if there is a way of resetting the settings to default to avoid this annoying bug?

Another annoying bug is having the "Game crashed menu" popping up when the game launched just fine (it happens on every game even though they don't crash and launch perfectly), it might be linked to the first issue I was talking in this post but I'm not sure on how I could resolve it either.

Finally, is having the default value not change any non set value for a specific game config normal ? Or should I change it manually on every game even though I want it to be changed by default and applied to every game where I haven't defined that particular value yet

Thank you

**Comment by ClemGlacee** [comment] 2021-08-16 16:21
https://user-images.githubusercontent.com/28269333/126053414-851a1505-9ba5-4fd1-add9-09da7e114f70.png

Since I can't post my image for some reason

**Comment by frostworx** [comment] 2021-08-16 16:31
apparently you haven't read my reply previously.
also reading/understanding the wiki might help
duplicate of #261

edit: and 6.13 is old...

**Comment by ClemGlacee** [comment] 2021-08-16 16:34
I did read your reply and added the version number but I’m still facing the issue. Won’t you answer my questions at least ?

**Comment by frostworx** [comment] 2021-08-16 16:40
looks like trolling to me, but anyway:

1st: you read my previous reply and understand it
2nd: you read at least the configuration part of the wiki and understand it.
3rd: you update to the latest release

If the "problem" still exist you open a useful and polite bug report with sane logs
and I might consider helping you.

**Comment by ClemGlacee** [comment] 2021-08-16 17:08
I don’t know what’s not polite or insane in my bug report tbh but okay. How is that a not a problem to you ? It’s very annoying and should be considered a problem imo

**Comment by ClemGlacee** [comment] 2021-08-16 17:24
I’m not even sure how logs would help for this but I’ll send them when I’m on my machine if that’s okay with you

**Comment by ClemGlacee** [comment] 2021-08-17 00:27
Is there a way to change every game config for a specific parameter or is it not something you're interested in implementing or maybe it is already in the tool ?

**Comment by ClemGlacee** [comment] 2021-08-17 01:19
[454120.log](https://github.com/frostworx/steamtinkerlaunch/files/6996303/454120.log)

There you go, for the game Starbase

**Comment by ClemGlacee** [comment] 2021-08-17 01:26
Well seems like Gamescope is the issue but I have no idea how to fix it

**Comment by frostworx** [comment] 2021-08-17 07:53
ok!

Let's see:

**1st "annoying bug":**

- not sure if you have read it meanwhile, but the purpose of the `DEFAULT` button is to configure the template configuration _(`~/.config/stl/default_template.conf`)_, which is used for all games without an own config yet. See [here](https://github.com/frostworx/steamtinkerlaunch/wiki/Configuration-Files#default-config)
- to configure settings for a game you need to use the  `GAME MENU` instead of the `DEFAULT` button
- so **IF** you want to define a **"Custom Command"**, you need to configure it there as well
- a "Custom Command" is only used if the separate "Use custom command" checkbox is activated as well

Looking at your log there is no attempt to start the custom command. I assume you simply misunderstood the custom command entry (by default, so if not configured, it points to the actual game exe simply because it the game directory is available at once, when the user actually really wants to use a custom exe. Use custom command is disabled by default, so this entry is not used at all, until the user changes this). I guess this should cover your 1st problem, right?

**2nd "annoying bug":**
The "Game crashed menu" window popped up, because ProtonGE and TKG fork their process into background and therefore stl reached the "game ended code, before it actually did. Regular proton doesn't have that problem, so I haven't noticed this until recently. With the latest release 6.15 this is fixed, with stl waiting now directly for the wineserver to end when those proton versions are detected and not for proton itself.

Your log shows that it you updated to 6.15 now and also that it triggered correctly (l 228) but no pid was found for it (so looks like the game did not even start here, right? You might be right that gamescope is the problem here. Did you try without, or without gamemoderun? I recently did major changes in the start parameter code, so this might be a regression where gamemoderun and
gamescope collide. If so, this should be easy to fix.
Don't have Starbase to test, but I'll check gamemode <->gamescope as well.

Your last question probably is related to the `DEFAULT` vs `GAME MENU` buttons again. Don't mix them up!
Everything you set in `DEFAULT` is default for every game starting with a NEW config (the template).
If the template does not exist as well, it is created from the defaults from the code
_(see function `setDefaultCfgValuesdefault_template` in the code if interested)_

**Comment by ClemGlacee** [comment] 2021-08-17 12:11
### 1st issue: Custom command

The weird thing is that I tried to change the template (the default config) but when I did, it did change the custom command to the starbase executable, thus having to change each game config to find the executable for the latter.

I did understand how the default button work, it's supposed to be a template and not a "global" config (it doesn't change not defined values in other configs but only the template) I didn't even wanted to define a custom command, it just changed the default "echo" if I remember correctly to the executable of the game (I was in the default section, not the game menu one). To launch a game in the past, I had to define the custom command as the game executable and didn't even have to tick the custom command checkbox for some reason.

### 2nd issue: Crash
I'm not sure if I fixed it by not having to use `CUSTOM COMMAND` any-more but as of now, I'm no longer facing this annoying issue.
The game did not launch, that's correct but I fixed it by disabling **gamescope** as it seems to be the problem in this latest version. I did try disabling every feature I turned on and managed to pin point it back to gamescope, with it turned on the game will crash after 0 sec, so won't even start at all, without it will run fine. I did try with gamemode on and gamescope off and it started fine but I didn't try with gamescope on and gamemode off, I'll try that in a few minutes and will get back to you.

I'm pretty sure, the issue is not directly linked to Starbase but any game running with gamescope on but to be sure I'll try that too!

### 3rd question: Global config
Yeah, it's related to the buttons because I thought the default config was more like a global config and not a template. Do you plan on adding such a feature as being able to change every game config for a specific not defined variable? Let's say I've never changed the replay sorcery parameter on any of my game and I now want to use it on every game, I'd have to tick it for every game config since as far as I understand it, there is no easy way to change it globally right?

**Comment by ClemGlacee** [comment] 2021-08-17 12:19
Just tried launching Starbase with gamescope and not gamemode and it crashed within 1 sec, I'll send the log if you want to check it

**Comment by ClemGlacee** [comment] 2021-08-17 12:20
[454120.log](https://github.com/frostworx/steamtinkerlaunch/files/6999853/454120.log)

**Comment by frostworx** [comment] 2021-08-17 12:46
ok, so
1) this is invalid, because you misconfigured it
2) as described the initial problem was ProtonGE forking which was fixed already.
The problem now doesn't look like a stl problem, so likely gamescope itself is the problem. Maybe up/downgrade your current installation(?).
3) this can be easily done via command line. The feature is ancient, and I haven't used it for a long time, but I guess it still does work. from `stl --help`:
```
    set <var> <for> <value>          Change configuration settings
                                       Example:
    set RUN_REPLAY all 1               Set RUN_REPLAY for all games to 1

```

**Comment by ClemGlacee** [comment] 2021-08-17 13:54
1. It changed by itself without me touching it (talking about the default config), I simply launched starbase and tried to edit the default config, haven't touch that custom command at all in the process
2. should I downgrade gamescope? because I have the latest version
3. ooh alright thanks! I couldn't find it in the big wiki

**Comment by frostworx** [comment] 2021-08-17 14:08
1. Sure, this could be improved by always using echo for "Custom Command" in the template. Anyway, as already said this would not have any effect on the game launch:  "Custom Command" is only used if the separate "Use custom command" checkbox is activated as well, so this was invalid anyway
2. Not my bug, just an idea. Shouldn't be too hard to test if a previous version has the same problems. Alternatively checking upstream for similar problems might help as well.
3. Sure, np. Indeed it is big.

**Comment by frostworx** [comment] 2021-08-17 14:51
@ 1) The default value for `CUSTOMCMD` **is** `default_template.conf` on creation
and it also does not magically change when changing and saving other options afterwards.
So nothing to improve here as well.

**Comment by ClemGlacee** [comment] 2021-08-17 16:01
> @ 1) The default value for `CUSTOMCMD` **is** `default_template.conf` on creation
> and it also does not magically change when changing and saving other options afterwards.

I'd love to say otherwise but it changed on its own as I definitely didn't touch that parameter in my default config
Please note I was editing the default section prior to launching Starbase so it put the Starbase executable as the customcmd

**Closed as completed** 2021-08-17 16:12 UTC

**Comment by frostworx** [comment] 2021-08-17 16:15
No idea what the point is really. What I said is reproducible and even if not it would be a minor glitch not even worth discussing it.
I'd say I helped more than enough with all those "annoying issues"

**Comment by ClemGlacee** [comment] 2021-08-17 16:27
Just launch any game, open `DEFAULT`and you'll see that the Custom command is set to the game executable. No need to argue here, just wanted to let you know of this weird behaviour. Please don't be condescending, there's no need to be thank you for your help

**Comment by frostworx** [comment] 2021-08-17 16:35
Just launch `stl settings` manually and the default is echo. Instead of adding a fix for this, a hint to initially start with `stl settings` might make more sense.

"Please don't be condescending" where?

**Comment by frostworx** [comment] 2021-08-17 18:28
https://github.com/frostworx/steamtinkerlaunch/commit/8cd17fe888cec3223b53a4343364284c48d0fd24

edit: ah nice, someone removed all of their comments...
["looks like trolling to me"](https://github.com/frostworx/steamtinkerlaunch/issues/294#issuecomment-899655031): QED
