### ISSUE TITLE
stl %command% did not work with DOTA 2

### ISSUE THREAD

**Issue by damachine** [sonic2kk/steamtinkerlaunch#90] opened 2020-10-05 15:25 UTC
hello title say all. have edit the startparameter to "stl %command%" but dota 2 did not start, without stl it works.

**Comment by frostworx** [comment] 2020-10-05 15:36
Hi,
does stl work for you with other games? Maybe it is just missing a dependency.

Could you please check/post the relevant log? It might have some hints on what went wrong.
`~/.config/stl/logs/${DOTA_GAMEID}.log`

**Comment by frostworx** [comment] 2020-10-05 15:38
Oh, I already have an idea:
Is it possible that DOTA 2 has a space in its game path?
I fixed a bug (offline) with empty space in linux game filepaths

**Comment by frostworx** [comment] 2020-10-05 15:41
If you want you could replace the three lines after
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L115
with
```
GP="$(printf "%s\n" "$@" | grep -m1 "steamapps/common")"											
GE="$(basename "$GP")"																	
EFD="${GP//$GE/}"	
```

**Comment by damachine** [comment] 2020-10-05 16:18
hello stl works great with csgo and gta 5.
in the stl log for dota2:
Mon Oct  5 17:35:07 CEST 2020 INFO - calculateDefaultResolutions - 'xrandr' found screenresolution '3840x2160'
Mon Oct  5 17:35:07 CEST 2020 INFO - calculateDefaultResolutions - found Screen Width '3840' and Screen Height '2160'
Mon Oct  5 17:35:07 CEST 2020 INFO - checkZenity - using '/home/christian/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/zenity' for the GUI
Mon Oct  5 17:35:07 CEST 2020 INFO - prepareGUI - using '/home/christian/.local/share/Steam/ubuntu12_32/steam-runtime/amd64/usr/bin/zenity' for 'zenity'


The changes are not help dota not start
GP="$(printf "%s\n" "$@" | grep -m1 "steamapps/common")"											
GE="$(basename "$GP")"																	
EFD="${GP//$GE/}"

**Comment by frostworx** [comment] 2020-10-05 16:27
Hi again!
Thanks for testing it!
Strange, that is a pretty short log!
Looks like I need to download dota to try myself. :)
Pretty sure it is some "support native linux games" bug, because it is still pretty much untested.

**Comment by damachine** [comment] 2020-10-05 16:42
thx no problem you do a great work

**Comment by frostworx** [comment] 2020-10-05 17:04
Download finished, and I just gave it a try with default settings.
I can reproduce your issue with the latest v2.0.7, but **yay**,
the game works ootb using my current (not yet released) version. :)
I'm going to release the new version within the next 1-2 days, so I think this will fix it for you as well.

**Comment by frostworx** [comment] 2020-10-05 17:33
Found the remaining issue:
You also need to change the "$GE" in
https://github.com/frostworx/steamtinkerlaunch/blob/master/stl#L5578
to "$GP"
then the game also works with v2.0.7

**Comment by damachine** [comment] 2020-10-05 20:03
DOTA is now playable with this change. thx for your fast help i wish you all best. see ya

**Comment by damachine** [comment] 2020-10-05 20:10
one question outside. i want to change some environment variable like __GL_SYNC_TO_VBLANK to 0. Is it right i put __GL_SYNC_TO_VBLANK="0" to the gamecfg file and it is apply for the game. Because when i look via echo $__GL_SYNC_TO_VBLANK it shows me 1. sorry my english

**Comment by frostworx** [comment] 2020-10-06 05:39
Yes, the gamecfg is a good place for env variables and 
__GL_SYNC_TO_VBLANK="0" is correct.
To see what finally got applied to your game you could add
`env > /tmp/stl-env`
to the very last line.
Your __GL_SYNC_TO_VBLANK should be 0 there.

**Comment by frostworx** [comment] 2020-10-06 05:41
> DOTA is now playable with this change. thx for your fast help i wish you all best. see ya

Thank you for testing and your friendly feedback! I wish you all the best as well :)

**Comment by frostworx** [comment] 2020-10-06 09:02
hopefully fixed in https://github.com/frostworx/steamtinkerlaunch/commit/c6548fcb4bdbb185dc8ae259602b9f3f296d4905
hf!

**Closed as completed by frostworx** 2020-10-06 09:02 UTC
