### ISSUE TITLE
Mod Organizer 2 and vortex not installing or running 

### ISSUE THREAD

**Issue by Aidenbiggg** [sonic2kk/steamtinkerlaunch#1109] opened 2024-05-17 15:00 UTC
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: Steam OS
- Installation Method: ProtonUp-Qt

## Issue Description
I have been trying to get Vortex to work on my steam deck using Proton 9.0-1 and all it does is sit there at installing "Dotnet". After i tried to see if mod organizer 2 would work and all it does is show a windows saying its installing then closes 2 seconds later. Am i doing anything wrong here i have q4wine installed on my steam deck if that helps to find out whats wrong.
[kde-purpose-pastebin-plugin.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/15351615/kde-purpose-pastebin-plugin.txt)

## Logs
[kde-purpose-pastebin-plugin.txt](https://github.com/sonic2kk/steamtinkerlaunch/files/15351631/kde-purpose-pastebin-plugin.txt)

**Comment by sonic2kk** [comment] 2024-05-17 17:53
It seems you did not read the issue template or wiki, despite opening two issues for this.

The biggest thing here is that you entirely ignored the issue template and insist on using an 18 month old release instead of using the latest git. [The Steam Deck wiki page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Steam-Deck) already told you to use STL-git. You can even get this from ProtonUp-Qt, as noted on [the ProtonUp-Qt page](https://github.com/sonic2kk/steamtinkerlaunch/wiki/ProtonUp-Qt) of the wiki.

I will preface my reply by saying I don't expect modding tools to work on SteamOS and so the best thing to do is to just not use them on SteamOS. The steps here are for how to fix MO2 on the Linux Desktop, the primary platform for SteamTinkerLaunch and the only platform I actually maintain. These steps may or may not work on SteamOS.

First off, don't bother with Vortex, in general, ever. It is a piece of garbage. The rest of this reply is for MO2.

You need to fully uninstall MO2 and Vortex, for MO2 make sure you [READ ***ALL*** OF THE MO2 WIKI](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2), especially [the steps for how to uninstall v2.5.0](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250) which STL v12.12 will install. Make sure you do these steps first. I cannot emphasise enough, ***remove all borked MO2 installs*** as instructed on the wiki.

After this, you need to reinstall SteamTinkerLaunch from master (remember to regularly update each time you see a new commit on GitHub, like you would on your Linux Desktop), run `steamtinkerlaunch cleardeckdeps` to update the `innoextract` dependency, and then re-install MO2.

If it still does not work, then that is unfortunate but there is nothing I can do. You will have to mod your games manually.

I am just so sick of repeating myself, you could've read previously closed issues with the MO2 label to find this out as well...

<hr>

I cannot mandate how you use SteamOS or SteamTinkerLaunch, but I emplore you, if you're not a Linux enthusiast and do not have familiarity with tinkering on the Linux Desktop (in other words if you do not use Linux full-time on your PC), DO NOT mod games on SteamOS. This is advice _from_ a Linux enthusiast that knows how goddamn awful tinkering is on SteamOS. SteamTinkerLaunch is not a modding tool, it is an enthusiast tool.

Another word of note: SteamTinkerLaunch support on SteamOS is no longer maintained, and I will stop advertising support. I do not use STL on SteamOS, no one has been able to step up as a SteamOS support maintainer, most of STL does not work on SteamOS by design of the OS (immutable distro). Once again, if you are not a developer.

<hr>

Closing as this is a duplicate of many closed MO2 issues and either could've been avoided by reading the wiki (MO2 wiki page, Steam Deck wiki page, ProtonUp-Qt wiki page) and following the guidance on the issue template (use latest git, check prior closed issues).

**Closed as completed by sonic2kk** 2024-05-17 17:53 UTC
Labels: bug, duplicate, ModOrganizer 2, Steam Deck

**Comment by Aidenbiggg** [comment] 2024-05-17 17:55
Installed steamtinkerlaunch via GitHub and followed instructions on how to install it looks like installing it via ProtonUp-Qt is broken

**Comment by sonic2kk** [comment] 2024-05-17 18:13
Report issues installing SteamTinkerLaunch-git to upstream ProtonUp-Qt, giving details on the error message.
