### ISSUE TITLE
A place to discuss other than Reddit and GitHub (such as Discord)

### ISSUE THREAD

**Issue by Faalagorn** [sonic2kk/steamtinkerlaunch#232] opened 2021-05-01 21:29 UTC
I myself am a Reddit user and I like it a lot so while it's nice that [/r/SteamTinkerLaunch](https://www.reddit.com/r/SteamTinkerLaunch/) exists, it's not a best platform to discuss things at glance.

GitHub is nice to discuss issues, PRs and individual commits. It recently got discussions too, so that might be worth enabling (you can see it in action e.g. in [luxtorpeda-dev](https://github.com/luxtorpeda-dev/luxtorpeda/discussions) which would be a good start as people contributing all have GitHub accounts anyway. 

However, sometimes a loose unformulated discussions/chats are good to have, as in not having to write a post and wait for reply, so I've been thinking of something in lieu of Discord or something similar. Discord is the most popular nowadays especially with gamers, so it might be the best bet and unless there's something I don't know, I think STL doesn't have one.

It might also be a good idea to ask folks at [VKx](https://github.com/disks86/VK9/) or [Frogging Family](https://github.com/Tk-Glitch/PKGBUILDS/) to create a channel for STL, that way more like-minded people could be reached easily on an established servers.

**Comment by frostworx** [comment] 2021-05-02 08:11
Oh nice, didn't know that github has discussions. Will enable it soon. Thanks for the hint :)
Discord is not really my cup of tea. I even had a steamtinkerlaunch discord channel, but closed it pretty early again, and announcements in other linux gaming related channels were ignored _(maybe I wasn't patient enough)_.

As I already spend pretty much time in working on stl, I don't want to spend even more in promoting it without any obvious effect.
If someone wants to moderate a discord channel, I'd be happy to help occasionally as "user", but won't maintain one by myself anymore.

**Comment by Faalagorn** [comment] 2021-05-02 08:15
Sure, gonna close it in the meantime, as to not clutter the issue list, especially as you opened the discussions already! If someone wants to, the discussion should be still be able to find by searching anyway. :)

**Comment by UltraBlackLinux** [comment] 2021-07-29 16:15
> Oh nice, didn't know that github has discussions. Will enable it soon. Thanks for the hint :)
> Discord is not really my cup of tea. I even had a steamtinkerlaunch discord channel, but closed it pretty early again, and announcements in other linux gaming related channels were ignored _(maybe I wasn't patient enough)_.
> 
> As I already spend pretty much time in working on stl, I don't want to spend even more in promoting it without any obvious effect.
> If someone wants to moderate a discord channel, I'd be happy to help occasionally as "user", but won't maintain one by myself anymore.

Am I blind, or are the discussions still not enabled? I need it I think, so I'd love to have it enabled xD

**Comment by frostworx** [comment] 2021-07-29 16:32
No sorry, you're not blind, they are disabled again.
"As I already spend pretty much time in working on stl" I'd love to have it disabled (for now)
Feedback is close to 0 anyway, so I doubt a discussion board will save me time _(like in an active community)_
but will need even more.
This might change in the future, when more people are willing to help

**Comment by frostworx** [comment] 2021-07-29 16:54
Reopening for discussion

**Comment by UltraBlackLinux** [comment] 2021-07-29 17:16
What about maybe opening a matrix space? It's somewhat widely used and stuff

**Comment by frostworx** [comment] 2021-07-29 17:39
I personally don't care that much which platform to use _(still no discord friend though)_
The problem is simply that I don't want to spend even more time into maintaining **any** channel,
so it would require helpful people who would like to moderate those.

Every additional appearance is extra work, which needs time
I already spent time previously in opening

- a discord channel
- an IRC channel
- the discussion board here
- 
- patron
- liberapay
*(no it is not about the money, but thought it might be the only option for some people to help in some way)*

and closed them all because there's no **active** community.

Thanks to those very few people who actually **really** helped _(directly and indirectly)_
I'm still motivated to work publically on the project.

**Comment by frostworx** [comment] 2021-08-07 10:03
The re-opening of this issue for discussion is apparently a proof on its own, that there is no need for a discussion board.

**Closed as completed by frostworx** 2021-08-07 10:03 UTC

**Comment by Faalagorn** [comment] 2021-08-07 10:52
> The re-opening of this issue for discussion is apparently a proof on its own, that there is no need for a discussion board.

I mostly stick at Discord, there's a Linux Gaming Dev where projects related to Proton as well as [MangoHud](https://github.com/flightlessmango/MangoHud) or [GRVK](https://github.com/libcg/grvk) are having their dedicated channels, but since you aren't active there, guess it's mostly communicating through GitHub for now :)

**Comment by frostworx** [comment] 2021-08-07 11:14
Maybe I should take a look, but might not find the time to be very active in there.
