### ISSUE TITLE
Cheat Engine Not starting along side the game

### ISSUE THREAD

**Issue by ImpactKaizer** [sonic2kk/steamtinkerlaunch#159] opened 2020-11-29 18:18 UTC
Tried with Dark Souls Remastered Here are the logs from the config DIR for ST.
Do let me know if you require any other info.

[570940.log](https://github.com/frostworx/steamtinkerlaunch/files/5612609/570940.log)

**Comment by frostworx** [comment] 2020-11-30 08:50
Does ProtonHax still work reliable with an older Proton version and if so with which version *(please that from the "version" file inside the proton directory, it is more exactly)*?

Reference: https://www.reddit.com/r/SteamPlay/comments/k1e4ja/protonhax_dose_not_work_with_513/

**Comment by ImpactKaizer** [comment] 2020-11-30 08:56
> Does ProtonHax still work reliable with an older Proton version and if so with which version *(please that from the "version" file inside the proton directory, it is more exactly)*?
> 
> Reference: https://www.reddit.com/r/SteamPlay/comments/k1e4ja/protonhax_dose_not_work_with_513/
> 

Protonhax works all the way till 5.0-10 fine 5.13 is the one it's has an issue from what I have noticed.

**Comment by frostworx** [comment] 2020-11-30 09:01
Yeah, I've just read that Protonhax parses the commandline incorrectly because of the SLR.
If this is the only problem, as a workaround you can use SteamTinkerLaunch as "compatibility tool" and ProtonHax as you regular do (as command line parameter) and it will work (because the SLR is not part of the command line when using a compatibility tool: https://github.com/frostworx/steamtinkerlaunch/issues/140)

**Comment by ImpactKaizer** [comment] 2020-11-30 09:06
> Yeah, I've just read that Protonhax parses the commandline incorrectly because of the SLR.
> If this is the only problem, as a workaround you can use SteamTinkerLaunch as "compatibility tool" and ProtonHax as you regular do (as command line parameter) and it will work (because the SLR is not part of the command line when using a compatibility tool: https://github.com/frostworx/steamtinkerlaunch/issues/140)

I'll give it a shot but how do you disable slr in the stl setting ?

**Comment by frostworx** [comment] 2020-11-30 09:10
It has a checkbox in the gui, but you don't have to disable it when SteamTinkerLaunch is a "compatibility tool" because it is not active then anyway.
I think I found the problem why it doesn't work with steamtinkerlaunch. I use the proton wine binary to start custom programs, which opens a new wineserver in the wineprefix. If I use proton directly (what ProtonHax does as well) it should simpy work).

**Comment by ImpactKaizer** [comment] 2020-11-30 09:15
> It has a checkbox in the gui, but you don't have to disable it when SteamTinkerLaunch is a "compatibility tool" because it is not active then anyway.
> I think I found the problem why it doesn't work with steamtinkerlaunch. I use the proton wine binary to start custom programs, which opens a new wineserver in the wineprefix. If I use proton directly (what ProtonHax does as well) it should simpy work).
> 

So should wait for an update on stl ?
Cause I'm abit confused on what I need to do as of now ?

**Comment by frostworx** [comment] 2020-11-30 09:19
When I'm done, yes. Of course programming should be sane.
Depending on how big the changes will be I can push them before the next release. If they are too big (f.e. might migrate the checkCustomLaunch function) I'll commit the changes with the next release, which will need some more days, as there's still some work left.

**Comment by ImpactKaizer** [comment] 2020-11-30 09:21
> When I'm done, yes. Of course programming should be sane.
> Depending on how big the changes will be I can push them before the next release. If they are too big (f.e. might migrate the checkCustomLaunch function) I'll commit the changes with the next release, which will need some more days, as there's still some work left.

I'll wait for the update then if you require any testing form me do let me know.

**Comment by frostworx** [comment] 2020-11-30 09:22
If it is urgent you can do that
https://github.com/frostworx/steamtinkerlaunch/issues/159#issuecomment-735652041

**Comment by ImpactKaizer** [comment] 2020-11-30 09:25
> If it is urgent you can do that
> https://github.com/frostworx/steamtinkerlaunch/issues/159#issuecomment-735652041

I'm in no rush I was just confused as to why protonhax stopped working with the new version of proton.

But since I got my answer I'm more than satisfied.

**Comment by frostworx** [comment] 2020-11-30 10:41
I already have it working, but changes are too big to push them in between.
A quick&dirty workaround would be to split 
`extWine64Run "$RUNWINE" "$LACO" "${RUNCUSTOMCMD_ARGS[@]}"`
into
```
				if [ -n "$1" ]; then
					(sleep 2; LC_ALL="C" "$RUNPROTON" run "$LACO" "${RUNPROGARGS[@]}") &
				else
					extWine64Run "$RUNWINE" "$LACO" "${RUNCUSTOMCMD_ARGS[@]}"
				fi
```
and replace
`launchCustomProg &`
with
`launchCustomProg "X"`

*(untested)*

The proper fix will be in the next release, maybe even with a direct Cheat Engine Option

**Comment by ImpactKaizer** [comment] 2020-11-30 10:43
> I already have it working, but changes are too big to push them in between.
> A quick&dirty workaround would be to split 
> `extWine64Run "$RUNWINE" "$LACO" "${RUNCUSTOMCMD_ARGS[@]}"`
> into
> ```
> 				if [ -n "$1" ]; then
> 					(sleep 2; LC_ALL="C" "$RUNPROTON" run "$LACO" "${RUNPROGARGS[@]}") &
> 				else
> 					extWine64Run "$RUNWINE" "$LACO" "${RUNCUSTOMCMD_ARGS[@]}"
> 				fi
> ```
> and replace
> `launchCustomProg &`
> with
> `launchCustomProg "X"`
> 
> *(untested)*
> 
> The proper fix will be in the next release, maybe even with a direct Cheat Engine Option

Thanks for letting me know and thanks adding cheat engine option also down the line.

**Comment by frostworx** [comment] 2020-11-30 10:48
Thanks for *(indirectly)* having discovered the issue! :)

**Comment by frostworx** [comment] 2020-11-30 14:20
fyi: https://github.com/frostworx/steamtinkerlaunch/issues/160

**Comment by ImpactKaizer** [comment] 2020-12-01 15:56
> fyi: https://github.com/frostworx/steamtinkerlaunch/issues/160

Thanks for the update .
Also wanted to ask regarding trainers is there a way to check why they don't load ?
Cause it's not a proton issue it's mostly new trainers don't load, old run fine is there a way to find out why ?

**Comment by frostworx** [comment] 2020-12-01 16:03
I don't understand your question. What makes you think this is not a proton issue?
What do you think where the problem is exactly?

**Comment by ImpactKaizer** [comment] 2020-12-01 16:07
> I don't understand your question. What makes you think this is not a proton issue?
> What do you think where the problem is exactly?

Cause it's the same on wine as well .

There is a trainer (premade cheats) called Fling tried it with the outer worlds but won't load.
With witcher 3 the trainer for this game will load fine 

If you want the link let me and I'll share with you want For the trainer.

**Comment by frostworx** [comment] 2020-12-01 16:14
Ah ic, so it is a wine problem in general.
I personally don't use the Cheat Engine at all, so you probably understand that I'm not going to spend much time in debugging wine compatibility for one of its "3rd party addons" as it is not my bug.

With some luck some more people will be interested in the new feature in steamtinkerlaunch and help debugging it.
Either way you can easily enable `PROTON_LOG` *(in steamtinkerlaunch)* which already have some usable information what needs. Have you checked Proton issues and/or the appdb from wine directly for hints?

**Comment by ImpactKaizer** [comment] 2020-12-01 16:20
> Ah ic, so it is a wine problem in general.
> I personally don't use the Cheat Engine at all, so you probably understand that I'm not going to spend much time in debugging wine compatibility for one of its "3rd party addons" as it is not my bug.
> 
> With some luck some more people will be interested in the new feature in steamtinkerlaunch and help debugging it.
> Either way you can easily enable `PROTON_LOG` *(in steamtinkerlaunch)* which already have some usable information what needs. Have you checked Proton issues and/or the appdb from wine directly for hints?
> 

It's not cheat engine it's a separate program.

I'll check the logs forgot they generate for each game I'll let you know.

The fix with be available to run parallel to the program in the next update correct ?

Anyway thanks again for the support.

**Comment by frostworx** [comment] 2020-12-01 16:27
Yeah, Cheat Engine support is ready for the next update.
I'm already fine-tuning and ironing out the last bugs, and pretty confident that I can roll a new release within the next 1-3 days.

"Hacky" programs often tend to be programmed pretty suboptimal and using routines which often segfault in wine.
If you don't find other bug reports I doubt that you will get very far *(and then probably a basic `PROTON_LOG` won't help very much)* I might be wrong though *just guessing*

**Comment by frostworx** [comment] 2020-12-01 16:41
Oh, steamtinkerlaunch logs won't help here of course and if you have `PROTON_LOGS` you could try your luck with opening an issue on their project page: https://github.com/ValveSoftware/Proton/issues

**Comment by ImpactKaizer** [comment] 2020-12-01 16:42
> Yeah, Cheat Engine support is ready for the next update.
> I'm already fine-tuning and ironing out the last bugs, and pretty confident that I can roll a new release within the next 1-3 days.
> 
> "Hacky" programs often tend to be programmed pretty suboptimal and using routines which often segfault in wine.
> If you don't find other bug reports I doubt that you will get very far *(and then probably a basic `PROTON_LOG` won't help very much)* I might be wrong though *just guessing*

Well it game me this if you could explain what it means I'd be grateful

`002c:fixme:winediag:LdrInitializeThunk wine-staging 5.22 is a testing version containing experimental patches.
002c:fixme:winediag:LdrInitializeThunk Please mention your exact version when filing bug reports on winehq.org.
00c0:err:setupapi:SetupDefaultQueueCallbackW copy error 1812 L"@mscms.dll,-1" -> L"C:\\windows\\system32\\spool\\drivers\\color\\srgb color space profile.icm"
00c0:err:module:open_builtin_file failed to load .so lib "/usr/lib/wine/l3codeca.acm.so"
00c0:err:module:open_builtin_file failed to load .so lib "/usr/lib/wine/mp3dmod.dll.so"
0120:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0xfd306d, context 0x549c690, init_notify 0, handle 0x5f5fa70): stub
00c0:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0178:err:module:open_builtin_file failed to load .so lib "/usr/lib32/wine/l3codeca.acm.so"
0178:err:module:open_builtin_file failed to load .so lib "/usr/lib32/wine/mp3dmod.dll.so"
0180:fixme:iphlpapi:NotifyIpInterfaceChange (family 0, callback 0x12df537, context 0x500be00, init_notify 0, handle 0x5a1fcc4): stub
0178:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0178:err:module:open_builtin_file failed to load .so lib "/usr/lib32/wine/winegstreamer.dll.so"
wine: configuration in L"/home/ahmad/.wine" has been updated.
01e0:fixme:kernelbase:AppPolicyGetThreadInitializationType FFFFFFFFFFFFFFFA, 0000000000ADFE10
01d4:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION

Unhandled Exception:
System.Runtime.InteropServices.MarshalDirectiveException: [MarshalAs] attribute required to marshal arrays to managed code.
 at (wrapper native-to-managed) System._AppDomain.Load(intptr,intptr,intptr)
[ERROR] FATAL UNHANDLED EXCEPTION: System.Runtime.InteropServices.MarshalDirectiveException: [MarshalAs] attribute required to marshal arrays to managed code.`

**Comment by frostworx** [comment] 2020-12-01 16:53
Nice, you're simply ignoring all of my questions and hints and paste your logs in here anyway...
Looks like a dotnet problem.

**Closed as completed by frostworx** 2020-12-01 16:53 UTC

**Comment by ImpactKaizer** [comment] 2020-12-01 16:55
> Nice, you're simply ignoring all of my questions and hints and paste your logs in here anyway...
> Looks like a dotnet problem.

Thanks for the reply and sorry for the silly questions.
