### ISSUE TITLE
commandline "stl launcher" with any commands does nothing.

### ISSUE THREAD

**Issue by OracleToes** [sonic2kk/steamtinkerlaunch#359] opened 2021-11-22 16:07 UTC
I am using Arch Linux, with steamtinkerlaunch-git-7.211118.r528.b71e794-1 from the AUR, launching the STL menu using the steam "Play" button works just fine.
The problem is that Steam likes to force users to update their game, whether that's via auto-update, or when the user presses "Play". This breaks a lot of mod compatibility with a LOT of games.
I want to use the STL launcher from the command line to bypass the update process.
When I type "stl launcher" and hit enter, the terminal breaks to a new line and nothing happens.
I have tried "stl launcher" with "menu" "last" "auto" "update" and also with the Steam ID for the game, but there is no error, nothing.

**Comment by frostworx** [comment] 2021-11-22 16:55
I tried to reproduce your problem with current master _(so with the [name migration](https://github.com/frostworx/steamtinkerlaunch/issues/350) applied)_, but "steamtinkerlaunch launcher" _(including options)_ still works here _(every game entry usually has an own icon/picture and I only see yad placeholder icons, but this is a different story)_.
I'm not really sure what you expect this function does, though.
It is just a little listing of all your games, but when you choose one it will be started through steam anyway, so it probably won't help you with steam updating game data.
If you want to debug this anyway, please provide a log _(`/dev/shm/steamtinkerlaunch/stl.log` like described [here](https://github.com/frostworx/steamtinkerlaunch/issues/93) should be enough)_

**Comment by frostworx** [comment] 2021-11-22 17:05
[Just pushed a fix](https://github.com/frostworx/steamtinkerlaunch/commit/8b1b4cba86009ee281be01cd65dab1d27fffaa82) for the missing icons _(caused by the name migration)_. So, thanks for reporting indirectly

**Comment by OracleToes** [comment] 2021-11-22 18:14
Okay, thanks for informing me that launching through the terminal won't save me an update, but here's the logfile.
[stl.log](https://github.com/frostworx/steamtinkerlaunch/files/7583444/stl.log)

**Comment by frostworx** [comment] 2021-11-22 18:43
Thanks for the log.
Oh, only "'1' parsable Game Entries" was found in your `sharedconfig.vdf`.
The command searching for installed games is
`awk "/Apps/,/StartMenuShortcutCheck/" sharedconfig.vdf | grep -v  "Apps\|/Apps/,/StartMenuShortcutCheck/" | awk '{printf "%s+",$0} END {print ""}' | sed 's/"[0-9][0-9]/\n&/g'`
which could be optimized for sure 😀, but it does find 467 games here _(which probably is correct)_
Either way, even if you have one game installed, it should be available in the launcher, of course.
Apparently it didn't create/find the corresponding desktop file, but I need to look deeper into this, because I haven't seen/touched that function for several months and need to find out myself what could have gone wrong.

**Comment by frostworx** [comment] 2021-11-22 18:51
Could you please try:
`stl update gamedata`
and then
`stl launcher`
This shouldn't be necessary, but should create your missing desktop file(s), which are required for the launcher.

Edit: no sorry, wait:
the "auto" parameter, which you already tried does exactly the same like `stl update gamedata`
_(calls the function `getGameDataForInstalledGames`)_

**Comment by frostworx** [comment] 2021-11-22 19:00
Please check if
`stl list installed`
returns a list of numbers `(SteamAppIds of your installed games)`

**Comment by OracleToes** [comment] 2021-11-22 19:59
Okay, I ran `stl list installed` first, and it did return a list of the appid's.
Running `stl update gamedata` returned no output or errors, and then `stl launcher` didn't launch anything either, still no error or output.
[stl.log](https://github.com/frostworx/steamtinkerlaunch/files/7584000/stl.log)

**Comment by frostworx** [comment] 2021-11-23 06:00
`stl list installed` was just to test if your games could be even found.
Would you mind updating to latest git master? It should have a complete log in `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log`.

**Comment by frostworx** [comment] 2021-11-28 14:53
ping?

**Comment by frostworx** [comment] 2021-11-29 14:54
invalid

**Closed as completed by frostworx** 2021-11-29 14:54 UTC
