### ISSUE TITLE
Cannot start Vortex after upgrading to 0.8

### ISSUE THREAD

**Issue by MattSturgeon** [sonic2kk/steamtinkerlaunch#372] opened 2021-12-07 23:44 UTC
I am unable to start Vortex in v0.8. 967822e973f480e48374c790a303eb99aa1b2c09 seems to introduce this issue:

```
$ git bisect bad
967822e973f480e48374c790a303eb99aa1b2c09 is the first bad commit
commit 967822e973f480e48374c790a303eb99aa1b2c09
Author: frostworx
Date:   Sat Nov 20 13:11:50 2021 +0100

    Migrated stl to steamtinkerlaunch and several fixes

 Makefile                       |     8 +-
 README.md                      |    25 +-
 lang/dutch.txt                 |     2 +-
 lang/english.txt               |     2 +-
 lang/englishUK.txt             |     2 +-
 lang/german.txt                |     4 +-
 lang/italian.txt               |     4 +-
 lang/polish.txt                |     2 +-
 lang/russian.txt               |     4 +-
 misc/steamtinkerlaunch.desktop |     4 +-
 steamtinkerlaunch              | 17064 +++++++++++++++++++++++++++++++++++++++
 stl                            | 16983 --------------------------------------
 12 files changed, 17095 insertions(+), 17009 deletions(-)
 create mode 100755 steamtinkerlaunch
 delete mode 100755 stl
```

Here's stdout/stderr when running with 967822e973f480e48374c790a303eb99aa1b2c09

```
$ steamtinkerlaunch vortex start
Tue  7 Dec 22:24:54 GMT 2021 INFO - setDotNetWine - Downloading: 'https://github.com/frostworx/steamtinkerlaunch-tweaks/releases/download/Proton-6.17-STL-1/Proton-6.17-STL-1.tar.gz'
Tue  7 Dec 22:24:55 GMT 2021 ERROR - setDotNetWine - DNPROTON '' was not found - can't continue
Tue  7 Dec 22:24:58 GMT 2021 INFO - startVortex - Starting Vortex without options
```

The key line seems to be `ERROR - setDotNetWine -DNPROTON '' was not found - can't continue` which comes from [this line](https://github.com/frostworx/steamtinkerlaunch/blob/b71e7945695889deb1c1ad6cd3e9e311517fdc55/stl#L11531) in `setDotNetWine`, but I guess that could be a red herring _/shrug_

----

I noticed that on c46c44b4d31e7895dfd07cf8f1ab1a7cc46342ce `~/.config/stl` is used for some stuff and `~/.config/steamtinkerlaunch` is used for other stuff (including the `vortex` directory). Interestingly, **when I merged these together** (having one symlinked to the other) I was able to start vortex using 967822e973f480e48374c790a303eb99aa1b2c09 and newer...

Maybe the issue is some sort of caching issue or config upgrade edge-case? Or perhaps something in the code is referencing the old `~/.config/stl` directory? Seeing as when I have that symlinked to `~/.config/steamtinkerlaunch` everything works as expected...

**Comment by frostworx** [comment] 2021-12-08 06:09
Thanks for the detailed report.
Unfortunately, I don't have the time to hunt this down in detail, so please check
if this is a duplicate of [this [solved] issue](https://github.com/frostworx/steamtinkerlaunch/issues/367)

**Comment by frostworx** [comment] 2021-12-11 07:26
🤔

**Comment by MattSturgeon** [comment] 2021-12-11 19:42
> 🤔

Sorry, I've not had a chance to look into this yet. From a quick glance at that issue it looks different, but I'll confirm once I've had a chance to investigate properly

**Comment by frostworx** [comment] 2021-12-12 08:27
Ok, please provide a log if the problem persists.
`DNPROTON '' was not found` looks like the proton binary required for dotnet was not found, which might be caused by a broken download indeed. Then this should be solved with above commit. Good luck.

**Comment by frostworx** [comment] 2021-12-17 16:50
please reopen with a log if the problem persists.

**Closed as completed** 2021-12-17 16:50 UTC
