### ISSUE TITLE
Mod Organizer 2 doesn't start

### ISSUE THREAD

**Issue by thecreatures** [sonic2kk/steamtinkerlaunch#1018] opened 2024-01-16 03:37 UTC
## System Information
- SteamTinkerLaunch version: v12.12 
- Distribution: Nobara 39 KDE
- Installation Method: ProtonUp-Qt

## Issue Description
Mod Organizer 2 and Vortex appear to be completely incapable of working. First attempted with standard Fedora 39, STL installed with ProtonUp-QT, multiple games installed and attempts made with MO2 and Vortex, nothing works. One of the attempts had a window pop up that said 0% and instantly disappeared. 

Then wiped everything clean and installed Nobara 39 Official, and had pretty much the same experience. Worth noting that entering "steamtinkerlaunch mo2 start"  in terminal resulted in "bash: steamtinkerlaunch: command not found...
Install package 'steamtinkerlaunch' to provide command 'steamtinkerlaunch'? [N/y]" even though STL was already accessible starting it up with Steam. This Nobara install was having enough other issues that we decided to try reinstalling again with a different iso. 

Today wiped everything clean and installed Nobara 39 KDE, installed GE-Proton8-27 and STL with ProtonUp-Qt, installed Fallout New Vegas, started up NV once, set compatibility tool to STL, opened up STL, clicked on Mod Organizer 2, this time a window popped up very briefly that actually had the MO2 logo, then that disappeared and another window popped up with a progress bar that made it to roughly 35% before disappearing, nothing else happened even after waiting 10 min. Started up STL, went to game menu and set MO2 to gui, hit save and play, MO2 didn't start. Attempts start up with GE-Proton8-27 and then with experimental-8.0-2024111c did not work. Moving '~/.config/steamtinkerlaunch/mo2' and removing '/dev/shm/steamtinkerlaunch' then entering 'steamtinkerlaunch mo2 start' in terminal got this result:

`bash: steamtinkerlaunch: command not found...
Install package 'steamtinkerlaunch' to provide command 'steamtinkerlaunch'? [N/y] y

 * Waiting in queue... 
 * Loading list of packages.... 
The following packages have to be installed:
 gameconqueror-0.17-15.fc39.1.x86_64    CheatEngline-alike interface for scanmem
 innoextract-1.9-11.fc39.x86_64 Tool to extract installers created by Inno Setup
 libmad-0.15.1b-36.fc39.x86_64  MPEG audio decoder library
 p7zip-16.02-26.fc39.x86_64     Very high compression ratio file archiver
 scanmem-libs-0.17-15.fc39.1.x86_64     Memory scanner library
 scummvm-2.7.1-1.fc39.x86_64    Interpreter for several adventure games
 scummvm-data-2.7.1-1.fc39.noarch       Data files for scummvm
 steamtinkerlaunch-12.12-1.fc39.noarch  Wrapper tool for use with the Steam client for custom launch options
 strace-6.6-1.fc39.x86_64       Tracks and displays system calls associated with a running process
Proceed with changes? [N/y] y

 * Waiting in queue... 
 * Waiting for authentication... 
 * Waiting in queue... 
 * Downloading packages... 
 * Requesting data... 
 * Testing changes... 
 * Installing packages... 
Mon Jan 15 07:30:38 PM CST 2024 INFO - setMO2Vars - USEMO2PROTON is 'none', so using latest Proton-GE 'GE-Proton8-27' automatically
Mon Jan 15 07:30:54 PM CST 2024 INFO - startMO2 - Starting '/home/kreatures/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe'
Mon Jan 15 07:30:54 PM CST 2024 INFO - startMO2 - WINEDEBUG="-all" WINEPREFIX="/home/kreatures/.config/steamtinkerlaunch/mo2/compatdata/pfx" "/home/kreatures/.local/share/Steam/compatibilitytools.d/GE-Proton8-27/files/bin/wine" "/home/kreatures/.config/steamtinkerlaunch/mo2/compatdata/pfx/drive_c/Modding/MO2/ModOrganizer.exe"
wineserver: using server-side synchronization.
wine: RLIMIT_NICE is <= 20, unable to use setpriority safely
creating minidump for the current process
trying file '.\ModOrganizer-2.5.1rc2-20240116T013056.dmp'
writing mini minidump
minidump written correctly
`
And MO2 still doesn't start.

This is our first time trying to get mods working on Linux as well as our first attempt to submit a bug report like this, let us know if we screwed anything up.

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/13944648/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2024-01-16 04:01
I think the first mistake is using SteamTinkerLaunch v12.12, the issue template told you to search closed issues and check the changelog. ModOrganizer 2 is not compatible with Valve Proton yet, as there is a missing Wine patch. To resolve this, SteamTinkerLaunch pins to MO2 v2.4.4 in the latest version from git. This is also available from ProtonUp-Qt. Why people default to stable releases of very old packages, I'll never know :sweat_smile: (*EDIT: Just remembered the issue template even asks for you to try the latest git, guess people don't read it...*)

MO2 should install correctly from the latest -git install from ProtonUp-Qt. Remove any existing install, and you will probably also have to remove the MO2 install from the New Vegas prefix (or any other game you tried) if it got that far.

> This is our first time trying to get mods working on Linux as well as our first attempt to submit a bug report like this, let us know if we screwed anything up.

For future reference, output like you provided should:
1. Be submitted as a text file as you did and not put into the issue. This, to be blunt, pisses off project maintainers.
2. The output you showed, specifically the minidump, is typically Wine output and is a hint that this is a **Wine incompatibility**.

Also, if you are only using SteamTinkerLaunch for ModOrganizer 2, and are using it as a mod tool installer, you will likely not have a great experience. It is an enthusiast-orientated tool.

In future, please follow the guidance in the issue template and search through closed issues and the changelog, where you would've seen these changes. And spread the word for people to STOP using STL v12.12. It really annoys me :sweat: Even when v14.0 comes out, if people stick to using it I will lose a lot of hope for this project. There is zero reason to use a "stable" version of a Bash script...

You can search issues, browse closed issues, and use labels to filter issues. For instance, this issue is a duplicate of:
- #1016 (possibly, OP has yet to provide enough information)
- #1012 (partially)
- #1009 
- #986
- #982 (likely didn't remove previous installs in prefix, no log provided to confirm)
- #976
- #974
- #973

Sorry if this is harsh, but I am sick of people using MO2 with SteamTinkerLaunch and raising this same issue without doing a little bit of Wine compatibility investigation work beforehand, nevermind searching previous issues.

<hr>

Useful links:
- SteamTinkerLaunch changelog wiki page: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Changelog
- SteamTinkerLaunch MO2 wiki page: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2
    - Specifically, the wiki has a section documenting the v2.5.0+ incompatibility, although users should search around on Wine compatibility before installing third-party tools: https://github.com/sonic2kk/steamtinkerlaunch/wiki/Mod-Organizer-2#modorganizer-2-v250
- You can also search closed PRs, in this case it is not particularly relevant but for other changes and even other projects, this is useful to do: https://github.com/sonic2kk/steamtinkerlaunch/pulls?q=is%3Apr+is%3Aclosed
- You can switch to the "Closed" tab on the main issue page, and select labels and other filtering options from the dropdown. Additionally, GitHub has some documented [Advanced Search Syntax](https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests).

**Closed as completed** 2024-01-16 04:03 UTC
Labels: bug, duplicate, ModOrganizer 2

**Comment by sonic2kk** [comment] 2024-01-16 04:21
Also looking at your command output, it looks like you installed a Community SteamTinkerLaunch package when you tried to run `steamtinkerlaunch` without it being on your PATH, so you are not using the ProtonUp-Qt version. You ran the command and it prompted you to install a system package. Make sure you uninstall this before switching to SteamTinkerLaunch-git from ProtonUp-Qt.

This is general distro usage though which isn't anything to do with SteamTinkerLaunch.

**Comment by thecreatures** [comment] 2024-01-16 06:17
Understood. I'll give it another go sometime in the next few days, once I've had time to go through and understand everything you have linked. One way or another I'll find out how to get MO2 working, STL just happens sound like best way to get MO2 working well according to various people on the internet. Thank you for your time.
