### ISSUE TITLE
STL turns off my second monitor when I start a game

### ISSUE THREAD

**Issue by materemias** [sonic2kk/steamtinkerlaunch#916] opened 2023-09-23 17:31 UTC
## System Information
- SteamTinkerLaunch version: v12.12
- Distribution: Arch Linux
- Installation Method: Package Manager

## Issue Description
When I start certain games with my dual monitor setup my other monitor is turned off. This happens with simple default settings as well. If I chose any other compatibility layer (GE, built in etc) it doesn't happen.

## Logs
https://pastebin.com/LvFdXP1L

**Comment by sonic2kk** [comment] 2023-09-23 17:43
SteamTinkerLaunch has no logic to control monitors, I have no idea why this is happening to you. I can't reproduce the problem and you'd need to give a lot more to go off of than this. You could try SteamTinkerLaunch-git, as v12.12 is extremely out of date, but this doesn't sound like a SteamTinkerLaunch bug.

The fact that it only happens with certain games makes this seem like some kind of system problem that STL is bringing to light. I use 4 monitors and haven't had any issues with them caused by SteamTinkerLaunch. I guess there are a couple of things that might be worth knowing
- Does it happen reliably with certain games?
- Does it only happen with Origin games? (it appears your log is from an Origin game)
- Does it happen with native games using SteamTinkerLaunch as a launch option?
- What desktop environment/window manager/compositor do you use?

In your log you seem to be using some unknown Proton version, please confirm of this is valid, in case your system is freaking out because of this Proton version: `/data/r/SteamData/steamapps/common/SteamLinuxRuntime_sniper/_v2-entry-point --verb=waitforexitandrun -- /usr/share/steam/compatibilitytools.d/proton-ge-custom/proton waitforexitandrun link2ea://launchgame/1238000?platform=steam&theme=mea`

It doesn't seem to be in a normal path.

Sorry, I don't think this is anything to do with SteamTinkerLaunch. It's a Bash script that ends with launching the game via a built launch command mirroring what Steam uses, it doesn't control multiple monitors. Take a look at the code for yourself to confirm, but I don't think this is SteamTinkerLaunch related. If anything, it could be a problem with Yad, but even that seems like a stretch.

**Comment by materemias** [comment] 2023-09-23 22:23
@sonic2kk thanks a lot for the quick answer. Based on your suggestions I have tried a few things and here is what I found:
- the proton version I am using is the one provided by [arch's aur](https://aur.archlinux.org/packages/proton-ge-custom-bin), I don't think there is anything wrong with it
- I tried the git version of STL and the situation is the same.
- it does not happen with native games run via STL
- it seems to reliably happening with all Origin games (EA Play via Steam)

I use KDE/Kwin. I understand this is not possibly caused by STL, still, I'd love it if you could help me with the next steps, and what to look for. I really appreciate any help you can provide.

**Comment by sonic2kk** [comment] 2023-09-23 23:48
I also use KDE, I use KDE Plasma Wayland and also have a multi-monitor setup.

I'll try and run some EA games I own and see if I can re-create the problem, I only have a few though. In my experience in the past, EA games are inconsistent but ever since the move to the EA app, don't work at all with SteamTinkerLaunch for me (though one user reported success with Mass Effect: Legendary Edition, a game I am trying to test with at the moment).

**Comment by sonic2kk** [comment] 2023-09-24 00:00
Well, I can't test the games themselves because they still don't work for me, probably due to however the DRM works as the command should be correct. The EA app opens as though it were launched "normally", and then says they encountered an error and could not start the game.

My guess is though that the EA launcher is causing this problem somehow. It doesn't appear from your log that you're using any strange settings. It might be worth trying to use a compatibility tool that isn't from the AUR as well, something installed to `compatibilitytools.d`, but I don't see that helping.

The EA app opened though, and I didn't have any issues, and I haven't seen any other reports of a display turning off. It could simply be the EA app causing problems here, but STL shouldn't be doing anything, unless it has trouble with the compatibility tool installed as a system package.

**Comment by sonic2kk** [comment] 2023-09-24 00:27
Do you use any environment variables to control your displays, by any chance? For Origin to work back when it did actually work over a year ago, there was an issue the previous maintainer resolved by basically unsetting a whole bunch of SteamTinkerLaunch environment variables. There's a (imo astronomically low) possibility that these variables are ones you have set on your system which STL is causing problems with.

**Comment by sonic2kk** [comment] 2023-09-24 17:55
I think this can be closed, as I did an extra thorough check and can't see how STL could be causing this. Probably there's some issue with Wine rather than STL here.

Origin games don't work for me anyway, so it's probably better to note somewhere that Origin games are expected to not work, that a PR is welcome to fix it, and to just avoid those games.

Sorry we couldn't get to the bottom of this general issue but I'm sure there are other places you can ask for guidance :-)

**Closed as completed by sonic2kk** 2023-09-24 17:55 UTC
Labels: bug

**Comment by materemias** [comment] 2023-09-24 21:16
@sonic2kk Thanks a lot for your thorough testing and explanation! I will report back here once/if I find a solution for this!

**Comment by CWSurpris3** [comment] 2024-02-22 18:17
I'm also now getting this problem. It happened when I changed my option of "Game Screen Resolution" from none to 1920x1080. 

I'm using steam, trying to play American Truck Simulator. I changed the screen res setting, and now Kubuntu won't even detect the second monitor I'm using. After rebooting, Kubuntu loads great. As soon as I log in, however, the second monitor immediately loses connection again. Taking steam out of STL in the compatibility launcher didn't do anything. Changing the STL Game Screen Resolution in the settings back to none, still no change, second monitor still dark. Not sure if this might be caused by Wine like previously mentioned, or if it's something different. Going to see if uninstalling STL fixes the issue, but I don't think it will. 

Not sure if there may be any other solution...

**Comment by CWSurpris3** [comment] 2024-02-22 19:10
@sonic2kk @materemias I believe it may be controlled by xrandr. I'll test that theory when I'm back and able to access my computer. Not sure if you had figured out a solution to the issue at all yet

**Comment by CWSurpris3** [comment] 2024-02-22 19:53
Ok confirmed it was xrandr that disabled the second monitor. For some reason I think when the resolution got changed, it just disables a secondary monitor... I'm not sure why, or if this will happen to others, but that's what happened to me. All i had to do was enable the second monitor using the xrandr -display command, "reformatting" it is the best way I can describe it. 

Again, this might be very niche but it's what fixed it for me. Will edit this if it happens with any other games tonight.
