### ISSUE TITLE
How to run a game with a trainer?

### ISSUE THREAD

**Issue by TheBitcoinBaron** [sonic2kk/steamtinkerlaunch#1199] opened 2024-12-14 18:18 UTC
People say this can be done but theres no instructions for how to do it. So how is it done?

**Comment by zany130** [comment] 2024-12-14 23:10
https://github.com/sonic2kk/steamtinkerlaunch/wiki/Custom-Command

**Comment by TheBitcoinBaron** [comment] 2024-12-15 11:26
I looked at that but it doesn't mention trainers.

I tried making a custom command be for the cyberpunk trainer but all that happened was it ran the game there was no trainer.

**Comment by sonic2kk** [comment] 2024-12-15 17:46
> I looked at that but it doesn't mention trainers.

Why would it mention trainers? This project isn't specifically for such programs. It is a general tool for Linux enthusiasts.

<hr>

Did you make sure to tick the "Use custom command"? Are you sure the trainer is compatible with Wine? Sometimes these "trainers" require extra .NET components.

SteamTinkerLaunch is not specifically for, or not for, these "trainer" programs. Barring SteamOS, which by design attempts to block multiple applications running in the same prefix at once, SteamTinkerLaunch has a feature that allows you to run custom executables in a game's prefix. There is no guidance specifically for or not for trainers, because it is just another type of executable. Users are responsible for understanding compatibility and how to get their programs running, this project can in part simply facilitate running the executables.

Closing as this does not appear to be a SteamTinkerLaunch bug, but a question of how to accomplish a specific action. The wiki page that @zany130 linked should sufficie with getting you up to speed on how to use the Custom Command functionality. If it doesn't, please open an issue detailing the improvements you would like to see (noting that it must be general; instructions specific to trainers are not relevant to Custom Commands as a whole, as that functionality is not only for that type of program).

Good luck!

**Closed as completed by sonic2kk** 2024-12-15 17:46 UTC
Labels: enhancement

**Comment by zany130** [comment] 2024-12-15 21:28
Sorry about adding to this now that it is closed but as sonic2kk mentioned the custom command only runs a specified executable ( can be for windows or Linux , a game specific trainer's, a mod loader, cheat engine, a game patcher, ect it's really powerful and useful feature 😂 probably my favorite feature of STL)  either alongsode, instead, before , or after the games executable 

(for example I on persona 3 I wanted to load my mod manager which would then launch my games with mods instead of the persona exe)

Any extra dependencies (usually.net)

Need to be installed by you.

You can use the built in wine tricks support https://github.com/sonic2kk/steamtinkerlaunch/wiki/Winetricks

If you know specifically what dep you want I remember there being a text box somewhere in the game menu that lets you specify winetricks verbs to install 

I think there might also be two ways of getting the winetricks GUI the button in the main menu and you can also have winetricks start on every launch of the game
