### ISSUE TITLE
Vortex trying to make a folder for fallout 4 where it doesn't have permission.

### ISSUE THREAD

**Issue by Lii-Kun** [sonic2kk/steamtinkerlaunch#911] opened 2023-09-21 15:29 UTC
## System Information
- SteamTinkerLaunch version: v14.0.20230921-1
- Distribution: Garuda Linux
- Installation Method:  Built from Git

## Issue Description
Trying to add Fallout 4 to vortex to manage it tries to create a folder in /home/vortex but it fails since it doesn't have write permissions(I assume) to that folder. I Can't find anyway to change where it creates this folder before adding the game to vortex. There is a spot in settings to set it after the game is added.

[steamtinkerlaunch.log](https://github.com/sonic2kk/steamtinkerlaunch/files/12686485/steamtinkerlaunch.log)

**Comment by sonic2kk** [comment] 2023-09-21 15:33
The log you attached isn't from your Vortex installation attempt, and doesn't contain any useful information. Regardless, this really isn't the kind of issue STL should be dealing with, tinkering and fixing these issues is the user's responsibility in 99% of cases.

You'll need to be more specific as well if you want any advice. I don't use Vortex, so you'll need to try and explain it a bit better, as well as attaching a lot from at least an attempt to start Vortex. You should also specify where Fallout 4 is installed, is it on your home drive or an external drive, etc. You should also note if this is somehow specific to Fallout 4.

Are you sure you got that path correct though? As in, `/home/vortex` where the user's name would be `vortex`? This doesn't really make any sense to me. It wouldn't have write permissions to `/home` but it also shouldn't be trying to write there, and I haven't seen this.

I will test later to see if this issue is potentially caused by games on the boot drive, but that shouldn't be the case, and STL shouldn't create a staging folder on the home folder. If Fallout 4 is not on your boot drive then I dunno, setting the path manually sounds like a straightforward enough workaround.

**Comment by Lii-Kun** [comment] 2023-09-21 15:53
It's not happening on the install but when setting the game to manage in vortex. Vortex installs just fine and I have it managing Starfield just fine. But when I try to change the game to Fallout 4 it tries to make a staging folder in `/home/vortex` which doesn't exist as no user is named vortex.

![2023-09-21_10-46](https://github.com/sonic2kk/steamtinkerlaunch/assets/2645955/c5090b47-036d-4c62-8a6a-8ff0a9810dae)
```
ENOENT: no such file or directory, open 'Z:\home\Vortex Mods\fallout4\__vortex_staging_folder'
ENOENT: no such file or directory, open 'Z:\home\Vortex Mods\fallout4\__vortex_staging_folder'
Error: ENOENT: no such file or directory, open 'Z:\home\Vortex Mods\fallout4\__vortex_staging_folder'
Prior Context:
    at Object.writeFileAsync (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9456:27)
    at writeStagingTag (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5193:12)
    at ensureStagingDirectoryImpl (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5193:75)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
Prior Context:
    at Object.writeFileAsync (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:9456:27)
    at writeStagingTag (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5193:12)
    at ensureStagingDirectoryImpl (C:\Program Files\Black Tree Gaming Ltd\Vortex\resources\app.asar\renderer.js:5193:75)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

**Comment by sonic2kk** [comment] 2023-09-21 16:04
Can't recreate the problem with Fallout 3 (moved to home steamapps for testing) or Baldur's Gate 3 (on external drive). Sounds like a Vortex problem, not a SteamTinkerLaunch problem.

The path the error is showing is not correct, it isn't exactly what you said but it's still not correct. The path to the staging folder in general is not correct. SteamTinkerLaunch creates a mod staging folder on either `~/.config/steamtinkerlaunch/vortex/staging/<gamename>`, or on the external drive with the game at the root, `/path/to/mountpoint/Vortex/<gamename>/` (no `staging` folder inside `Vortex` on the external drives).

I have no idea what's causing this, it sounds like something has gone wrong with Vortex being unable to see certain paths. This is not a SteamTinkerLaunch issue and not a Vortex support forum I'm afraid.

If Vortex installs and starts, the rest isn't up to SteamTinkerLaunch to fix, especially if another game works. I don't use or encourage the use of Vortex either, so I have little interest in troubleshooting general issues with using 3rd party tools under Wine once they install. As SteamTinkerLaunch is for tinkerers, it is expected that users will tinker and work around problems caused. Closing.

EDIT: fwiw I also did a check on `steamtinkerlaunch vortex getset` and no paths returned `\\Vortex Mods` at all. All of the install paths set by STL or updated within/by Vortex returned the correct results: `Z:\\path\\to\\drive\\Vortex\\{GAME}\\mods` (or for Fallout 3 on my boot drive, `Z:\\home\\user\\.config\\steamtinkerlaunch\\vortex\\staging\\{GAME}\\mods`)

**Closed as completed by sonic2kk** 2023-09-21 16:04 UTC
Labels: Vortex Mod Manager

**Comment by Lii-Kun** [comment] 2023-09-21 16:11
You can call it a vortex issue but it's not like I can post this problem with them as they don't support Linux and will just wash their hands of the problem like you just did.

**Comment by sonic2kk** [comment] 2023-09-21 16:14
And therefore it's up to me to troubleshoot an issue, which I can't reproduce, with very little information, for software I don't use? SteamTinkerLaunch is a tool for tinkerers, bugs saying that something doesn't work with little investigation work, *especially* when it pertains to modding which is just a bad idea all-around on Linux imo, is not something I can help with.

If Vortex installs at all I call that a miracle, and I have been considering for months to pull support, as too many people expect this to be a support forum for modding their games. SteamTinkerLaunch is a tinker utility, not modding software. Once third-party tools install you're expected to tinker and research to get them to work just like if you had done it manually.

If you need to ask somewhere I'm sure there are Linux gaming communities that can help you with modding. Not to mention you can just change the Vortex staging folder location and fix this issue.

**Comment by Matth3wW** [comment] 2024-01-15 23:32
> Can't recreate the problem with Fallout 3 (moved to home steamapps for testing) or Baldur's Gate 3 (on external drive). Sounds like a Vortex problem, not a SteamTinkerLaunch problem.
> 
> The path the error is showing is not correct, it isn't exactly what you said but it's still not correct. The path to the staging folder in general is not correct. SteamTinkerLaunch creates a mod staging folder on either `~/.config/steamtinkerlaunch/vortex/staging/<gamename>`, or on the external drive with the game at the root, `/path/to/mountpoint/Vortex/<gamename>/` (no `staging` folder inside `Vortex` on the external drives).
> 
> I have no idea what's causing this, it sounds like something has gone wrong with Vortex being unable to see certain paths. This is not a SteamTinkerLaunch issue and not a Vortex support forum I'm afraid.
> 
> If Vortex installs and starts, the rest isn't up to SteamTinkerLaunch to fix, especially if another game works. I don't use or encourage the use of Vortex either, so I have little interest in troubleshooting general issues with using 3rd party tools under Wine once they install. As SteamTinkerLaunch is for tinkerers, it is expected that users will tinker and work around problems caused. Closing.
> 
> EDIT: fwiw I also did a check on `steamtinkerlaunch vortex getset` and no paths returned `\\Vortex Mods` at all. All of the install paths set by STL or updated within/by Vortex returned the correct results: `Z:\\path\\to\\drive\\Vortex\\{GAME}\\mods` (or for Fallout 3 on my boot drive, `Z:\\home\\user\\.config\\steamtinkerlaunch\\vortex\\staging\\{GAME}\\mods`)

Thank you for this! Once I set my "Mod Staging folder" to: 

`Z:\home\[my username]\.config\steamtinkerlaunch\vortex\staging\{GAME}\mods`

my issue was fixed.

I experienced this issue on Nobara Linux 38 with steamtinkerlaunch version 12.12 installed from protonup-qt. The game was starfield and I, mistakenly, added the game in vortex manually specifying the path to the game, before adding the game to the vortex steam-collection and/or checking the box in the "Games" menu of steamtinkerlaunch. I have no idea if this is what caused my problem, but when I added a different game in vortex after adding it to the games menu in steamtinkerlaunch, the problem did not replicate itself. Thanks for your time!

**Comment by sonic2kk** [comment] 2024-01-16 02:06
I'm glad it fixed it, but please don't use SteamTinkerLaunch v12.12. It is *horribly* outdated, I'm amazed Vortex even worked. You should be using the latest version from git, available from ProtonUp-Qt as SteamTinkerLaunch-git (you will need to enable advanced mode if you haven't already).
