### ISSUE TITLE
Steam Tinker Launch not working

### ISSUE THREAD

**Issue by arnavgr** [sonic2kk/steamtinkerlaunch#449] opened 2022-04-11 16:58 UTC
I have installed steamtinkerlaunch on pop os but it is not opening. 
i cloned the code and ran sudo make install.
after installation i ran steamtinkerlauch through applications menu but it didnt open
then i ran steamtinkerlaunch through the terminal and this is what i got
`Mon Apr 11 10:27:37 PM IST 2022 INFO - main - No arguments provided. See 'steamtinkerlaunch --help' for possible command line parameters`
i have installed all the dependencies . putting stl %command% in steam lauch options doesnt launch the game
what am i supposed to do

**Comment by frostworx** [comment] 2022-04-11 17:25
you ignored this note when opening the issue:
```
Note
If you experience an issue, please always post the exact version used and append the corresponding log file
```

**Comment by arnavgr** [comment] 2022-04-11 17:41
im sorry. I couldnt find steam tinker launch in my config files. using mlocate these are the places where `sudo make install` has installed the files
`/usr/bin/steamtinkerlaunch
/usr/share/steamtinkerlaunch`
im using the latest version of steamtinkerlaunch(v9.2)

**Comment by frostworx** [comment] 2022-04-11 18:03
please see [here](https://github.com/frostworx/steamtinkerlaunch/issues/93)

_(I'd guess you didn't install yad or the installed version is too old - logs will probably help here)_

`grep "^YAD" ~/.config/steamtinkerlaunch/global.conf`
and
`command -v yad` _(or `which yad` if you like)_ might be interesting as well

**Comment by arnavgr** [comment] 2022-04-11 18:11
i have yad version 11.1 (GTK+ 3.24.30) installed
when i add the command `grep "^YAD" ~/.config/steamtinkerlaunch/global.conf`
i get `YAD=""`
`command -v yad` gives `/usr/local/bin/yad`

**Comment by frostworx** [comment] 2022-04-11 18:18
the problem is apparently `YAD=""`.
The variable is filled by default with `command -v yad` so I assume you installed yad after you installed steamtinkerlaunch.
the log is still missing so this is just a wild guess.
You could possibly fix it using
`steamtinkerlaunch yad /usr/local/bin/yad`, but the function is not widely tested _(simply check with the grep afterwards if it worked)_

_(edit: formatting)_

**Comment by arnavgr** [comment] 2022-04-11 18:24
omg thanks bro wtf it worked

**Comment by frostworx** [comment] 2022-04-11 18:33
nice! happy tinkering :)

**Comment by arnavgr** [comment] 2022-04-11 18:53
ah i have another problem now. when i launch steam game with tinkerlaunch it shows the launcher menu and the game doesnt launch

**Comment by frostworx** [comment] 2022-04-11 18:57
more details, logs

**Comment by arnavgr** [comment] 2022-04-11 19:07
ok im using proton experimental with special k enabled(old)
here is the log 
```
Tue Apr 12 12:19:46 AM IST 2022 INFO - startGame - ## GAMESTART HERE ###
Tue Apr 12 12:19:46 AM IST 2022 INFO - restoreOrgVars - Restoring previously cleared Variables
Tue Apr 12 12:19:46 AM IST 2022 INFO - startGame - ## GAMESTOP after '0' seconds playtime
Tue Apr 12 12:19:46 AM IST 2022 STOP - ######### SteamTinkerLaunch v9.3.20220409 #########
Tue Apr 12 12:19:46 AM IST 2022 STOP - ######### CLEANUP #########
Tue Apr 12 12:19:46 AM IST 2022 INFO - closeSTL - closing STL
Tue Apr 12 12:19:46 AM IST 2022 INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/arnavgr/.config/steamtinkerlaunch/default_template.conf'
Tue Apr 12 12:19:46 AM IST 2022 INFO - updateConfigEntry - Option 'CUSTOMCMD' is updated with the new value 'echo' in config 'default_template.conf'
Tue Apr 12 12:19:46 AM IST 2022 INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue Apr 12 12:19:46 AM IST 2022 INFO - checkPlayTime - The game was not started via 'steamtinkerlaunch' but directly from Steam - skipping Crash Requester
Tue Apr 12 12:19:46 AM IST 2022 INFO - closeSTL - Game 'Brawlhalla (291550)' exited - cleaning up custom processes if necessary
Tue Apr 12 12:19:46 AM IST 2022 INFO - closeTrayIcon - Closing TrayIcon '13188'
Tue Apr 12 12:19:47 AM IST 2022 INFO - closeSTL - Removing '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue Apr 12 12:19:47 AM IST 2022 STOP - ######### closeSTL SteamTinkerLaunch v9.3.20220409 #########
Tue Apr 12 12:19:47 AM IST 2022 INFO - writeLastRun - Recreating /home/arnavgr/.config/steamtinkerlaunch/logs/steamtinkerlaunch/lastrun.txt
Tue Apr 12 12:19:47 AM IST 2022 INFO - storeMetaData - Saving metadata for game 'Brawlhalla (291550)'
Tue Apr 12 12:19:47 AM IST 2022 INFO - getArch - Architecture for '/home/arnavgr/.steam/debian-installation/steamapps/common/Brawlhalla/Brawlhalla.exe' is 32bit
Tue Apr 12 12:19:47 AM IST 2022 INFO - storeMetaData - '/home/arnavgr/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_291550.vdf' does not exists
Tue Apr 12 12:20:14 AM IST 2022 INFO - startSettings - createProtonList:
Tue Apr 12 12:20:14 AM IST 2022 INFO - startSettings - openTrayIcon:
Tue Apr 12 12:20:14 AM IST 2022 INFO - autoCategorySettings - Searching categories for game '291550' in 'sharedconfig.vdf'
Tue Apr 12 12:20:14 AM IST 2022 SKIP - autoCategorySettings - Config '/usr/share/steamtinkerlaunch/categories/.conf' not found - skipping
Tue Apr 12 12:20:14 AM IST 2022 SKIP - autoCategorySettings - Config '/home/arnavgr/.config/steamtinkerlaunch/categories/.conf' not found - skipping
Tue Apr 12 12:20:14 AM IST 2022 INFO - setFullGameExePath - Using the base game directory '' as absolute game exe path
Tue Apr 12 12:20:14 AM IST 2022 INFO - openTrayIcon - LoadCfg: /home/arnavgr/.config/steamtinkerlaunch/gamecfgs/id/291550.conf
Tue Apr 12 12:20:14 AM IST 2022 INFO - loadCfg - '/home/arnavgr/.config/steamtinkerlaunch/gamecfgs/id/291550.conf' START
Tue Apr 12 12:20:14 AM IST 2022 INFO - loadCfg - Loading game config '/home/arnavgr/.config/steamtinkerlaunch/gamecfgs/id/291550.conf'

```Tue Apr 12 12:20:14 AM IST 2022 INFO - loadCfg - '/home/arnavgr/.config/steamtinkerlaunch/gamecfgs/id/291550.conf' STOP

**Comment by frostworx** [comment] 2022-04-11 19:11
this is not the log you were talking about.
please re-produce your problem _(start a game via steam using steamtinkerlaunch and append that log as file - easier to read/search than a paste)_

**Comment by arnavgr** [comment] 2022-04-11 19:22
ok so as soon as i launch the game through steam with steamtinkerlaunch %command& the menu(which asks u to go to main menu or launch game) appears and then appears instantly with the game stopping to launch with it. these are the log files
```
Tue Apr 12 12:47:52 AM IST 2022 INFO - startGame - ## GAMESTART HERE ###
Tue Apr 12 12:47:52 AM IST 2022 INFO - restoreOrgVars - Restoring previously cleared Variables
Tue Apr 12 12:47:52 AM IST 2022 INFO - startGame - ## GAMESTOP after '0' seconds playtime
Tue Apr 12 12:47:52 AM IST 2022 STOP - ######### SteamTinkerLaunch v9.3.20220409 #########
Tue Apr 12 12:47:52 AM IST 2022 STOP - ######### CLEANUP #########
Tue Apr 12 12:47:52 AM IST 2022 INFO - closeSTL - closing STL
Tue Apr 12 12:47:52 AM IST 2022 INFO - updateConfigEntry - Emptying 'CUSTOMCMD' for '/home/arnavgr/.config/steamtinkerlaunch/default_template.conf'
Tue Apr 12 12:47:52 AM IST 2022 INFO - updateConfigEntry - Option 'CUSTOMCMD' is updated with the new value 'echo' in config 'default_template.conf'
Tue Apr 12 12:47:52 AM IST 2022 INFO - closeSTL - Creating '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue Apr 12 12:47:52 AM IST 2022 INFO - checkPlayTime - The game was not started via 'steamtinkerlaunch' but directly from Steam - skipping Crash Requester
Tue Apr 12 12:47:52 AM IST 2022 INFO - closeSTL - Game 'Brawlhalla (291550)' exited - cleaning up custom processes if necessary
Tue Apr 12 12:47:52 AM IST 2022 INFO - closeTrayIcon - Closing TrayIcon '17770'
Tue Apr 12 12:47:53 AM IST 2022 INFO - closeSTL - Removing '/dev/shm/steamtinkerlaunch/steamtinkerlaunch-closing.tmp'
Tue Apr 12 12:47:53 AM IST 2022 STOP - ######### closeSTL SteamTinkerLaunch v9.3.20220409 #########
Tue Apr 12 12:47:53 AM IST 2022 INFO - writeLastRun - Recreating /home/arnavgr/.config/steamtinkerlaunch/logs/steamtinkerlaunch/lastrun.txt
Tue Apr 12 12:47:53 AM IST 2022 INFO - storeMetaData - Saving metadata for game 'Brawlhalla (291550)'
Tue Apr 12 12:47:53 AM IST 2022 INFO - getArch - Architecture for '/home/arnavgr/.steam/debian-installation/steamapps/common/Brawlhalla/Brawlhalla.exe' is 32bit
Tue Apr 12 12:47:53 AM IST 2022 INFO - storeMetaData - '/home/arnavgr/.config/steamtinkerlaunch/meta/eval/id/evaluatorscript_291550.vdf' does not exists

**Comment by arnavgr** [comment] 2022-04-11 19:26
i get this when launching directly from the tinkerlauncher
`ERROR - setGPfxFromAppMa - '/home/arnavgr/.steam/debian-installation/steamapps/appmanifest_291550.acf' is no valid directory - probably function 'listAppManifests' requires a fix here!`

**Comment by frostworx** [comment] 2022-04-11 19:32
nice , another linux distribution with some weird custom steam paths _(`debian-installation` is new)_
we can debug this together, but please attach log files as requested.
please append your `/dev/shm/steamtinkerlaunch/steampaths.txt`

**Comment by arnavgr** [comment] 2022-04-11 19:35
```
SROOT="/home/arnavgr/.steam/debian-installation"
SUSDA="/home/arnavgr/.steam/debian-installation/userdata"
DEFSTEAMAPPS="/home/arnavgr/.steam/debian-installation/steamapps"
DEFSTEAMAPPSCOMMON="/home/arnavgr/.steam/debian-installation/steamapps/common"
CFGVDF="/home/arnavgr/.steam/debian-installation/config/config.vdf"
LFVDF="/home/arnavgr/.steam/debian-installation/steamapps/libraryfolders.vdf"
FAIVDF="/home/arnavgr/.steam/debian-installation/appcache/appinfo.vdf"
PIVDF="/home/arnavgr/.steam/debian-installation/appcache/packageinfo.vdf"
STEAMCOMPATOOLS="/home/arnavgr/.steam/debian-installation/compatibilitytools.d"
ICODIR="/home/arnavgr/.steam/debian-installation/steam/games"
STEAM_COMPAT_CLIENT_INSTALL_PATH="/home/arnavgr/.steam/debian-installation"
STUIDPATH="/home/arnavgr/.steam/debian-installation/userdata/324178763"
STEAMUSERID="324178763"
SUIC="/home/arnavgr/.steam/debian-installation/userdata/324178763/config"
FLCV="/home/arnavgr/.steam/debian-installation/userdata/324178763/config/localconfig.vdf"
```

**Comment by arnavgr** [comment] 2022-04-11 20:16
wth now i cant even launch a game without tinkerlauncher it just staright up crashes

**Comment by arnavgr** [comment] 2022-04-12 04:37
if this issue is unresolvable i would switch to arch

**Comment by frostworx** [comment] 2022-04-12 05:16
ok the paths looks sane. _(haven't checked `setGPfxFromAppMa` but this is a cosmetical glitch)_
please do the following:
- use steamtinkerlaunch as compatibility tool instead of command option _(recommended in the wiki)_
- remove anything in `/dev/shm/steamtinkerlaunch/`
- start the game _(if possible with a clean `~/.config/steamtinkerlaunch/`)_
- append(! so drag&drop) the logfile `/dev/shm/steamtinkerlaunch/steamtinkerlaunch.log` in your report.

**Comment by arnavgr** [comment] 2022-04-12 18:16
the folder `/dev/shm/steamtinkerlaunch/` contains `..` which has sticky permission t(drwxrwxrwxt) and is not letting me remove the file

**Comment by arnavgr** [comment] 2022-04-12 20:16
i am able to get steamtinkerlaunch running but wehn i launch it with special k (old) the game crashes.
For context i am trying to play Brawlahalla(-noeac) and i have tried the latest GE version as well as tkg version none of them seem to be running
EDIT: log files dont show any error

**Comment by frostworx** [comment] 2022-04-13 05:03
closing as invalid
specialk can crash, this is not steamtinkerlaunch related

**Closed as completed by frostworx** 2022-04-13 05:03 UTC
