### ISSUE TITLE
How am I supposed to use this on arch?

### ISSUE THREAD

**Issue by 32bitx64bit** [sonic2kk/steamtinkerlaunch#1175] opened 2024-09-29 10:25 UTC
Yad, just doesn't f**king work on Arch, because of libjxl dependency not being updated to the latest in yad, causing a issue where yad just wont work because of a version mismatch (i.e expected 10.3, actual version 11.0). I've made a issue on Yad but given the Yad developer doesn't seem to check bug reports, idk what todo anymore.  

Also would their be a alternative wrapper for this that doesn't use yad...?

**Comment by sonic2kk** [comment] 2024-09-29 17:57
Yad works fine here on Arch, with version v14.0 (maybe v14.1 now?). I have no idea what the problem is on your system. SteamTinkerLaunch is developed *on* Arch Linux.

If you don't want to use Yad from the repos, you can use the Yad AppImage, [as described on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad). You can build or supply your own Yad AppImage, or download one with SteamTinkerLaunch.

> Also would their be a alternative wrapper for this that doesn't use yad...

The UI requires Yad, there is no drop-in replacement to my understanding for Yad.

<hr>

This is not really a SteamTinkerLaunch problem, difficulty satisfying a dependency on a given distro is not really a bug on this project (especially when this dependency works fine on my end on the same distro). So I will close this issue.

**Closed as completed by sonic2kk** 2024-09-29 17:57 UTC
Labels: bug

**Comment by sonic2kk** [comment] 2024-09-29 18:16
~~Out of interest, I did a search on the Arch repos and I can't see what Yad dependency requires `libjxl`?~~

~~Yad itself doesn't depend on it, even as an optional dependency, and I can't see where any nested dependency lays here. It's entirely possible I'm missing it, though.~~

Seems like it's probably [webkit2gtk-4.1](https://archlinux.org/packages/extra/x86_64/webkit2gtk-4.1/). This is likely a wider packaging issue than anything specific to Yad, and you can supply Yad yourself as noted earlier so it shouldn't be a blocker for using this project.

**Comment by 32bitx64bit** [comment] 2024-09-30 10:28
> Yad works fine here on Arch, with version v14.0 (maybe v14.1 now?). I have no idea what the problem is on your system. SteamTinkerLaunch is developed _on_ Arch Linux.
> 
> If you don't want to use Yad from the repos, you can use the Yad AppImage, [as described on the wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Yad). You can build or supply your own Yad AppImage, or download one with SteamTinkerLaunch.
> 
> > Also would their be a alternative wrapper for this that doesn't use yad...
> 
> The UI requires Yad, there is no drop-in replacement to my understanding for Yad.
> 
> This is not really a SteamTinkerLaunch problem, difficulty satisfying a dependency on a given distro is not really a bug on this project (especially when this dependency works fine on my end on the same distro). So I will close this issue.

edit nvm, I got it working properly now. Thanks!
