### ISSUE TITLE
addnonsteamgame not working  | not showing up in steam

### ISSUE THREAD

**Issue by FeyrisTan** [sonic2kk/steamtinkerlaunch#1044] opened 2024-02-23 06:53 UTC
## System Information
- SteamTinkerLaunch version: master
- Distribution: Arch Linux
- Installation Method: manually

addnonsteamgame does not work. I create it however it does not show up and the libraryfolders.vdf stays the same.

**Comment by sonic2kk** [comment] 2024-02-23 17:31
Just tested, works for me (both from the commandline and the UI). You'll need to provide some more information, such as a log file after you attempt to add a game. I tested a native Linux executable and a Windows EXE file, both worked in my tests.

You should also provide information such as the exact command you ran, or the exact parameters given. This should also come through in the log, but both is useful. What exactly *isn't* working? Is the command showing up as not found? Does it exit with any suspicious logging information or Bash errors (latter is unlikely)? This is not a prescriptive list, it is just an idea of information that you should provide.

You should also note what investigation work you did before opening the issue, what troubleshooting steps did you take?

> and the libraryfolders.vdf stays the same

Why would `libraryfolders.vdf` be changed?

**Comment by sonic2kk** [comment] 2024-02-25 15:41
I tested a couple more times with some other options (setting a compatibility tool, setting game artwork) and I cannot replicate a case where the command or UI fail.

You'll need to provide a log file as requested earlier (and as instructed in the issue template) and give some more background on the exact command you tried to use and how it failed, as requested in my earlier comment.

**Comment by sonic2kk** [comment] 2024-02-26 18:58
Closing as I couldn't reproduce the problem and the requested log in the issue template was not provided, and not enough information was provided to help further.

Please re-open if you can provide this information.

**Closed as completed by sonic2kk** 2024-02-26 18:58 UTC
Labels: bug, Non-Steam Game

**Comment by sonic2kk** [comment] 2024-02-27 14:39
Possibly related: #1045.

If you have multiple Steam accounts on the same PC, that could be the issue. But this is incredibly rare, and it was not mentioned in your OP, so I have no way to know.
