### ISSUE TITLE
Not working for some games.

### ISSUE THREAD

**Issue by Laz55** [sonic2kk/steamtinkerlaunch#691] opened 2022-12-16 12:11 UTC
## System Information
- SteamTinkerLaunch version: 
- Distribution: 
- Installation Method: 

## Logs

Hi 

This needs a serious update its always crashing the menu no longer shows up for some games such as,  Days gone, steel rising . The Fork function is unstable seems too always crash the game or any Cheat Trianer also, why did cheat engine get removed?

**Comment by sonic2kk** [comment] 2022-12-16 14:25
Hi! Thanks for opening an issue.

You did not correctly fill out your issue template, providing **no** information that could help you fix the problems you are facing. Please update your issue to include this information, remembering also **to attach logs**.

> This needs a serious update

This attitude is not very helpful to anyone. Just because *you* are experiencing a problem does not automatically mean *everyone* is. A good chunk of the bug reports received are user error. Simply saying "it doesn't work" when that means it doesn't work for *you* is not helpful to anyone, especially when you are arrogant enough to ignore the issue template and requested information that is there to *help* users.

> its always crashing

This is far too vague and there are too many variables, as you did not fill out the issue template I don't know if it is even really crashing. It can appear to be crashing (as all software could) but there could be far more variables here.

> no longer shows up for some games such as, Days gone, steel rising 

Days Gone works fine for me on Arch Linux with SteamTinkerLaunch v11.12.20221215-2. I don't own Steel Rising so I cannot test that.

![image](https://user-images.githubusercontent.com/7917345/208117305-5d353922-ccd4-4ff0-939a-46fc58eaa323.png)

**This is why you need to provide a log**.

> The Fork function is unstable seems too always crash the game or any Cheat Trianer

This is more than likely a result of a third party program incompatibility, not SteamTinkerLaunch. The fork function works fine in my experience for more standard programs I have tested, and other users have used it too with some of the Truck Simulator games, Dark Souls, and I myself have used it for Factorio and Old School RuneScape.

From other users asking in the past, Cheat Trainers typically need various Winetricks to work. SteamTinkerLaunch is **not** here to automatically configure all of your third party programs for you, it simply allows you to run them with Wine and, assuming you understand which configuration is needed, provide a menu to apply that configuration. Some of these programs also require specific versions of Wine / Proton, which SteamTinkerLaunch will let you configure. SteamTinkerLaunch is not just a program for whatever these "trainer" programs are and I haven't even used one before, asking for general Wine program support on the SteamTinkerLaunch issue tracker is not valid.

> also, why did cheat engine get removed?

See #618, #664, the [changelog](https://github.com/sonic2kk/steamtinkerlaunch/wiki/changelog) and the [FAQ](https://github.com/sonic2kk/steamtinkerlaunch/wiki/faq). A little bit of research before opening your issue would've answered this for you. The short answer:
- Upstream CheatEngine does not allow redistribution
- CheatEngine has some questionable practices that make it more difficult to justify supporting
- Invasive anti-cheat programs like EAC would've ended up banning users who had SteamTinkerLaunch installed 

<hr>

You will need to update your issue template and attach a SteamTinkerLaunch log for the run of the games you are trying. Days Gone might be the most reasonable one to try since I own that game and can test it.

**Comment by Laz55** [comment] 2022-12-16 15:13
First of all, submitting process is a complete mess .

Secondly,  the programs has been less and less stable lately.  I
addressesed the issue and now your accusing me of being rude because I
point out that program has flaws?  That's a bunch of clownery.

**Comment by sonic2kk** [comment] 2022-12-16 15:15
> First of all, submitting process is a complete mess .

I'm not sure what about it is a mess. It's just pressing the "New Issue" button on GitHub and filling out information, like any other repository, no?

> I addressesed the issue and now your accusing me of being rude because I point out that program has flaws? 

I'm not sure how you addressed it, and all you said was that two games and some third-party programs were not working for you, without providing any of the requested issue template information such as logs, distribution, STL version, etc.

No one can help you with any software project if you do not provide more information than simply "This needs a serious update." Particularly when the case I can test with the information you gave, Days Gone, is working on my end.

**Comment by Laz55** [comment] 2022-12-16 15:19
Hi

Your the one that's being rude, what you  is for people too do the
homework  and write a damn memoir on what the bug is. The program has been
very buggy on steamdeck lately. The Fork functions has had stability issues
forever.  Not my fault you can't handle criticism on the Program .

You can try too fix  or don't. Either way life goes on.

**Comment by Laz55** [comment] 2022-12-16 15:21
Hi


Too be fair it maybe more of the steamdeck which has been havint alot more
bugs lately, but Days Gone now longer triggers the steam tinker and for
some reason Steele rising no longer does as well.

**Comment by sonic2kk** [comment] 2022-12-16 15:24
> Your the one that's being rude, what you  is for people too do the homework  and write a damn memoir on what the bug is. 

You need to provide information on what the problem is and how to reproduce it, your system information, and provide a log. If you are unwilling to do this, for SteamTinkerLaunch or other projects, no one can help you. It seems like you are presuming that this is a problem that *everyone* is facing, when I cannot reproduce the problem. I cannot help you if I cannot see what is going wrong or have more information about your system.

The majority of projects will ask you for this information. Your OS, software version, a description of the problem and a log. This is very standard-issue stuff. For example, [Proton](https://github.com/ValveSoftware/Proton/issues/new?assignees=&labels=&template=compatibility-report.md) asks for very similar information, as does [Steam for Linux](https://github.com/ValveSoftware/steam-for-linux/issues/new). It is unreasonable to expect a resolution to your issue by just saying "this isn't working".

As well as this, to use your phrasing, users *are* expected to "do the homework" before opening a bug report.

> You can try too fix  or don't. Either way life goes on.

Indeed, life does go on. If you don't want to provide logs or system information, please close this issue. I cannot look into problems that users don't give information on.

**Comment by sonic2kk** [comment] 2022-12-16 16:38
Given the lack of information in this report, OP's reluctance to provide further information and logs, and the conduct in this issue ("You can try to fix it or don't"), it seems no progress will be made here and the issue will be closed.

Normally re-opening an issue if the problem persists would be the general advice, but opening a new, **complete** issue the problem you are facing is probably better here. Since SteamTinkerLaunch works for many users, when you encounter a problem you *have* to provide information including a log which shows what SteamTinkerLaunch is doing, and this is usually what leads to fixes. This is standard issue with projects.

It is unfortunate when an issue has no resolution. There is not much anyone can do if users do not provide information though.

**Closed as completed by sonic2kk** 2022-12-16 16:38 UTC
Labels: bug

**Comment by Laz55** [comment] 2022-12-16 16:52
LOL

Typical I am not going too fix your product and do the work for you.  The
program needs too be updated as stated
 In the emails yet you're stating its too vague?


Steam tinker will not launch for days gone and now currently Steele rising
. I also, mentioned that the Fork Function can be very finicky and unstable
if you can't understand  that that's on you.
You either fix it or not , but what I won't do do the work for you that's
not how goes.

Person A makes a Program with a few Bugs  it isn't up too Person B aka the
consumer too fix the bugs.

I literally see random different but reports on other things involving the
program.

**Comment by sonic2kk** [comment] 2022-12-16 17:13
> Typical I am not going too fix your product and do the work for you.

I cannot reproduce the problem and other users have not reported it. This is a problem that *you* are experiencing, so *you* are expected to provide the information requested. It's requested for a reason.

> The program needs too be updated as stated in the emails yet you're stating its too vague?

Yes, this is far too vague.

> Steam tinker will not launch for days gone and now currently Steele rising

You mentioned a problem with Days Gone - I don't have the issue. You mentioned a problem with Fork Custom Command - I don't have the issue. How do you expect me to fix a bug that I can't reproduce? And since you have not provided a log, I cannot look into it.

> You either fix it or not , but what I won't do do the work for you that's not how goes.

I can't fix a problem I don't experience and don't have more information about. You *are* expected to provide the requested information when opening an issue though, and as I pointed out this is not unique to SteamTinkerLaunch. Good luck getting support on other projects by just saying "X thing is not working, your project needs an update."

> if you can't understand  that that's on you.

Okay. You're expected to provide more information to troubleshoot bugs though, for any project. If you see providing logs and system information as "doing the work", there is no reason to open an issue as there won't be a resolution.

> Person A makes a Program with a few Bugs  it isn't up too Person B aka the consumer too fix the bugs.

No, and I never claimed it was. But it *is* up to "Person B" to provide information and work with the developer, to try and troubleshoot further on what may be causing the problem, in other words "do the homework". Person B is not helpful by simply saying "it doesn't work" in a case where other users cannot replicate the problem.

**Comment by Laz55** [comment] 2022-12-17 20:21
Hi

I will give you an example, when you launch steam tinker on the steamdeck ,
when you select game menu which brings you too the options of selecting the
Fork function when you attach a cheat Trainer it will crash if some games
launch a second launcher, suck as Ubi connect or EA app. I will either
crash the game or close the Trainer / Fork function.


You can test this with Assassin Creed Valhalla when you attach the fork
function & add Fling Cheat Trainer for AC Valhalla it will launch normal ,
but rue moment the second Ubiconnet loads it will crash either the game or
the trainer.

Its seem the Fork function will crash or close if  roo many  programs or
poping up.
