### ISSUE TITLE
Zink and Prime-Run Compatibility

### ISSUE THREAD

**Issue by Rabcor** [sonic2kk/steamtinkerlaunch#1040] opened 2024-02-16 08:04 UTC
To ensure compatibility between prime-run and zink, the zink variables must be loaded after the prime-run ones (this is because both of them set  `__GLX_VENDOR_LIBRARY_NAME` and for Zink to activate this must be set to mesa.

Currently it seems the prime-run variables are loaded after the zink ones thus leading to no zink if prime-run is also enabled.

To illustrate:

`zinkrun prime-run mangohud glxgears`
![24-02-44-](https://github.com/sonic2kk/steamtinkerlaunch/assets/5684325/c76159d5-c98a-4a8c-876b-be8646a59314)

`prime-run zinkrun mangohud glxgears`
![24-02-45-](https://github.com/sonic2kk/steamtinkerlaunch/assets/5684325/7e9c6066-96fc-4e6a-9909-c7ff18981f62)

**Comment by sonic2kk** [comment] 2024-02-16 17:04
Nice catch, thanks!

The issue and solution you described makes sense after looking at the code too, I didn't realise how `__GLX_VENDOR_LIBRARY_NAME` was being set at first.

The solution should be as straightforward as moving the check for Zink to be after Primerun (as you described) in the following place (looks like GitHub doesn't embed linked code snippets for files with many lines): https://github.com/sonic2kk/steamtinkerlaunch/blob/b106b3304dd3c4fd6ad8d4364cb79003f2ca5cc3/steamtinkerlaunch#L12422-L12426

I would normally open this up to ask if you would like to make a PR for this, since you took the time to understand and cleanly report the problem, but I actually want to do a slight refactor here to break some of the code into separate "checker" functions, so I'll take a look at fixing this. Otherwise I would've given an opportunity to contribute the fix and get all the credit, but you'll just have to settle for most of it I think ;-) 

I'll push a branch and open a PR. I'll let you know when it's ready for testing and you can check if the problem is fixed on your end with the branch. I think we tested some branches before but let me know if you need any help checking out the branch.

**Comment by sonic2kk** [comment] 2024-02-16 17:11
A branch that implements the fix as described is available at [`primerun-zink-change`](https://github.com/sonic2kk/steamtinkerlaunch/tree/primerun-zink-change).

The associated PR is up at #1041.

If/when you are able to confirm this fixes the issue, I'll bump the version and merge the PR :-)

**Comment by Rabcor** [comment] 2024-02-17 03:32
Launched with tinkerlaunch with prime-run and zink:
![image](https://github.com/sonic2kk/steamtinkerlaunch/assets/5684325/c8a67dad-ce43-4665-af85-417174a6c2c1)


It works.

**Comment by sonic2kk** [comment] 2024-02-17 14:48
Awesome! I'll merge when I'm on my PC. Thank you!

**Comment by sonic2kk** [comment] 2024-02-17 16:32
Fixed with #1041. Thanks again!!

**Closed as completed** 2024-02-17 16:32 UTC
Labels: bug
