### ISSUE TITLE
Vortex fails to launch on Steam Deck

### ISSUE THREAD

**Issue by apaz-cli** [sonic2kk/steamtinkerlaunch#797] opened 2023-04-26 22:15 UTC
## System Information
- SteamTinkerLaunch version:  v12.12
- Distribution: SteamOS ()
- Installation Method: ProtonUp-Qt

```
$ uname -a
Linux apaz-steamdeck 5.13.0-valve36-1-neptune #1 SMP PREEMPT Mon, 19 Dec 2022 23:39:41 +0000 x86_64 GNU/Linux
```

## Issue Description
I go from main menu to Vortex, install it, and press start. The window below pops up for a few seconds, and then goes away. Vortex does not launch.

The same thing happens when I run
`~/stl/prefix/steamtinkerlaunch start vortex`.

![2023-04-26-165443_1680x1050_scrot](https://user-images.githubusercontent.com/47389403/234713517-5cca6dfc-d38c-4e55-922d-30ff74630476.png)

This may be a SteamTinkerLaunch problem, or it may be a Vortex problem, or it could be anything else. If it's not your problem, I'll be take it down the chain.

Thanks,
apaz

## Logs
(deck@apaz-steamdeck steamtinkerlaunch)$ cat /dev/shm/steamtinkerlaunch/steamtinkerlaunch.log
Wed Apr 26 04:54:35 PM CDT 2023 INFO - setflatpak - started SteamTinkerLaunch from /home/deck/stl/prefix/steamtinkerlaunch
Wed Apr 26 04:54:35 PM CDT 2023 INFO - initAID - Set AID from STEAM_COMPAT_APP_ID to '489830'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - initAID - Set OSCDP to STEAM_COMPAT_DATA_PATH '/home/deck/.local/share/Steam/steamapps/compatdata/489830'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLangFile - Language from command line is 'english'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Wed Apr 26 04:54:35 PM CDT 2023 INFO - steamdedeckt - Seems like we have a Steam Deck here - making some specific settings
Wed Apr 26 04:54:36 PM CDT 2023 INFO - steamdedeckt - Did not detect a running 'gamescope' process - assuming we're running in Desktop Mode
Wed Apr 26 04:54:36 PM CDT 2023 INFO - steamdedeckt - Set 'FIXGAMESCOPE' to '0'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - steamdedeckt - Set 'SMALLDESK' to '1'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - steamdedeckt - Looks like we have a game but we're running from the Steam Deck install Prefix, not doing any updating here!
Wed Apr 26 04:54:36 PM CDT 2023 INFO - steamdedeckt - Seems like we're being run by Steam here, not doing any installation steps
Wed Apr 26 04:54:36 PM CDT 2023 INFO - setLocalInstall - Looks like we don't have a local non-root install
Wed Apr 26 04:54:36 PM CDT 2023 INFO - updateConfigEntry - Option 'GLOBALCOLLECTIONDIR' is updated with the new value '/home/deck/stl/prefix/collections' in config 'global.conf'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - getCurrentCommandline - No Proton in command line arguments 'vortex start'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - saveOrgVars - Storing some original variables to restore them later
Wed Apr 26 04:54:36 PM CDT 2023 INFO - emptyVars - Emptied some original variables as they slowdown several system calls when started from steam
Wed Apr 26 04:54:36 PM CDT 2023 INFO - emptyVars - Set $PATH to '/usr/local/sbin:/usr/local/bin:/usr/bin:/var/lib/flatpak/exports/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:/home/deck/stl/deps/usr/bin::/home/deck/stl/deps/usr/bin::/home/deck/stl/deps/usr/bin:'
Wed Apr 26 04:54:36 PM CDT 2023 START - ######### Initializing Game Launch 489830 using SteamTinkerLaunch v12.12 #########
Wed Apr 26 04:54:36 PM CDT 2023 INFO - main - Starting with a clean log
Wed Apr 26 04:54:36 PM CDT 2023 INFO - main - Start creating default configs
Wed Apr 26 04:54:36 PM CDT 2023 INFO - createDefaultCfgs - START
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLanguage - First load the default language 'english' to make sure all variables are filled
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLangFile - Language from command line is 'english'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLangFile - GLOBALSTLLANGDIR is '/home/deck/stl/prefix/lang'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLangFile - Command line language 'english' is no file - trying to find its absolute path
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLangFile - Loading language file from script directory '/home/deck/stl/prefix/lang/english.txt'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLanguage - Loading STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - loadLanguage - STLLANG from '/home/deck/.config/steamtinkerlaunch/global.conf' is 'english'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - createDefaultCfgs - setSteamPaths:
Wed Apr 26 04:54:36 PM CDT 2023 INFO - setSteamPaths - Reading Steam Path variables from '/dev/shm/steamtinkerlaunch/steampaths.txt'
Wed Apr 26 04:54:36 PM CDT 2023 INFO - getGameOS - Starting game OS detection
Wed Apr 26 04:54:36 PM CDT 2023 WARN - getGameOS - Could not extract the full game binary path from the incoming game launch command, so assuming this is a Windows game!
Wed Apr 26 04:54:36 PM CDT 2023 INFO - setWin - '' determined to be a Windows Game
Wed Apr 26 04:54:36 PM CDT 2023 INFO - createDefaultCfgs - createProtonList:
Wed Apr 26 04:54:36 PM CDT 2023 INFO - createDefaultCfgs - createProtonList end
Wed Apr 26 04:54:37 PM CDT 2023 INFO - listAllSettingsEntries - '/dev/shm/steamtinkerlaunch/setentries.txt' already exists - nothing to do
Wed Apr 26 04:54:37 PM CDT 2023 INFO - createDefaultCfgs - STOP
Wed Apr 26 04:54:37 PM CDT 2023 SKIP - listSteamLibraries - not recreating already available '/dev/shm/steamtinkerlaunch/SteamLibraries.txt'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_LIBRARY_PATHS set to '/home/deck/.local/share/Steam/steamapps'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_MOUNTS set to '/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setSteamLibraryPaths - STEAM_COMPAT_TOOL_PATHS set to '/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime:/home/deck/.local/share/Steam/steamapps/common/SteamLinuxRuntime_soldier:/home/deck/.local/share/Steam/steamapps/common/Steamworks Shared'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - main - Checking internal dependencies:
Wed Apr 26 04:54:37 PM CDT 2023 INFO - checkIntDeps - Skipping yad version check on SteamDeck
Wed Apr 26 04:54:37 PM CDT 2023 INFO - main - Initializing first Proton:
Wed Apr 26 04:54:37 PM CDT 2023 INFO - initOldProtonArr - Creating an initial array with available Proton versions using the file '/dev/shm/steamtinkerlaunch/ProtonCSV.txt' which was created during a previous run
Wed Apr 26 04:54:37 PM CDT 2023 INFO - initFirstProton - Initializing Proton
Wed Apr 26 04:54:37 PM CDT 2023 INFO - initFirstProton - Initial Proton version 'FIRSTUSEPROTON' from '/home/deck/.config/steamtinkerlaunch/default_template.conf' is 'proton-7.0-6e'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - main - Initializing default window resolution
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setInitWinXY - Using '1280x800' from config '/dev/shm/steamtinkerlaunch/defres.txt'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - main - Welcome to SteamTinkerLaunch
Wed Apr 26 04:54:37 PM CDT 2023 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/appinfo'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - removeEmptyFiles - Removing empty files from '/home/deck/.config/steamtinkerlaunch/games/header'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - main - Checking command line: incoming arguments 'vortex start'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setVortexVars - Using GE-Proton7-55 for vortex
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setModWine - DNPROTON is '/home/deck/.config/steamtinkerlaunch/proton/custom/GE-Proton7-55/proton'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setModWine - DNPROTON is a file -- it is '/home/deck/.config/steamtinkerlaunch/proton/custom/GE-Proton7-55/proton'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setVortexDLMime - INFO: Linking Nexus Mods downloads to Vortex
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setVortexDLMime - Desktopfile /home/deck/.local/share/applications/vortex-steamtinkerlaunch-dl.desktop seems to be up2date
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setVortexDLPath - Setting Vortex Download WinDir 'Z:\\home\\deck\\.config\\steamtinkerlaunch\\vortex\\downloads' in Vortex
Wed Apr 26 04:54:37 PM CDT 2023 INFO - setVortexConfigVdf - Updating 'config/config.vdf' in the Vortex pfx, to make newly games available when auto-detectable
Wed Apr 26 04:54:37 PM CDT 2023 INFO - pollWinRes - Using GEOM '--geometry=1280x800+0+0' from '/home/deck/.config/steamtinkerlaunch/guicfgs/1280x800/489830/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - StatusWindow - for 'Vortex'
Wed Apr 26 04:54:37 PM CDT 2023 INFO - prepareVortexGame - '"skyrimse" (489830)' is already setup for 'Vortex' - remove from '/home/deck/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Wed Apr 26 04:54:38 PM CDT 2023 INFO - pollWinRes - Using GEOM '--geometry=1280x800+0+0' from '/home/deck/.config/steamtinkerlaunch/guicfgs/1280x800/489830/SteamTinkerLaunch-PrepareVortexGameStatus.conf'
Wed Apr 26 04:54:38 PM CDT 2023 INFO - StatusWindow - for 'Vortex'
Wed Apr 26 04:54:38 PM CDT 2023 INFO - prepareAllInstalledVortexGames - Preparing all installed games supported by Vortex
Wed Apr 26 04:54:38 PM CDT 2023 INFO - setVortexVars - Using GE-Proton7-55 for vortex
Wed Apr 26 04:54:38 PM CDT 2023 INFO - setVortexVars - Using GE-Proton7-55 for vortex
Wed Apr 26 04:54:38 PM CDT 2023 INFO - gVSIDs - Searching for SteamIDs in '/home/deck/.config/steamtinkerlaunch/vortex/compatdata/pfx/drive_c/Program Files/Black Tree Gaming Ltd/Vortex/resources/app.asar.unpacked/bundledPlugins'
Wed Apr 26 04:54:39 PM CDT 2023 INFO - prepareVortexGame - '"skyrimse" (489830)' is already setup for 'Vortex' - remove from '/home/deck/.config/steamtinkerlaunch/vortex/compatdata/seenvortexgames.txt' for retry
Wed Apr 26 04:54:39 PM CDT 2023 INFO - prepareAllInstalledVortexGames - Applying Vortex settings for all games via autogenerated cmd '/dev/shm/steamtinkerlaunch/vortset.cmd'
Wed Apr 26 04:54:49 PM CDT 2023 INFO - prepareAllInstalledVortexGames - Symlinks, registry entries and vortex settings for all found supported games should be ready at this point for Vortex
Wed Apr 26 04:54:49 PM CDT 2023 INFO - startVortex - Starting Vortex without options
Wed Apr 26 04:55:08 PM CDT 2023 INFO - startVortex - Vortex exited - starting game now

**Comment by sonic2kk** [comment] 2023-04-26 22:45
This is almost certainly #792 - Vortex 1.8.0 requires a build of Proton that implements `DiscardVirtualMemory`, which was first made available in Wine 8.4. [The wiki](https://github.com/sonic2kk/steamtinkerlaunch/wiki/Vortex#note-for-vortex-180) notes this as well. You are using GE-Proton7-55 which is not compatible as it's still based on Wine 7.0 staging afaik.

Try getting a build of Proton based on this - there are various, the wiki links to Proton-tkg which may be the most straightforward (can be installed manually or with ProtonUp-Qt in advanced mode) but feel free to build your own if you'd like, as long as it's a version of Wine that implements `DiscardVirtualMemory` it should work. From what I have seen not even Proton Experimental implements this, so a build of Proton based on Wine 8.4 or above *or* an older version of Wine that implements this method with a patch may work too. If one of these newer builds works, feel free to close the issue.

This should also not be specific to Steam Deck in case you were wondering :-)

Breakages with Vortex because of Wine version incompatibility are up to users to fix, there is nothing STL can do about it. Like with games that might break with newer/older Proton versions, users have to resolve the mismatch themselves. Any kind of "solution" STL would implement to guess what Proton version might be needed for a given Vortex version would end up getting quite messy and end up being a game of cat and mouse. As STL is a tinker tool for experienced Linux users it's expected that users will find or build a Proton version that resolves the issue if one is available, or otherwise wait/manually rollback the Vortex version. STL isn't a Wine support forum so there is nothing to "fix" here which is why I removed the bug label (upstream Wine breakages are not STL bugs as a general rule, some instances i.e. extra launch options or symlinks or that kind of configuration would be something STL could address, but if the issue is solely that a newer Wine version is required, that isn't something directly that STL can fix).

**Comment by sonic2kk** [comment] 2023-04-26 22:54
I should also note that mod compatibility has not been tested with Vortex 1.8.0, but in my testing on my Arch PC, using a build of Proton-tkg based on Wine staging seemed to fix the issue. I downloaded from the CI directly from the repo, but afaik ProtonUp-Qt should work as well (it should use the same CI pipeline I think, I wrote the ctmod for ProtonUp-Qt but don't recall exactly which workflow it points to, but it'll be a super bleeding edge Wine build).

**Comment by sonic2kk** [comment] 2023-04-30 14:31
Did using a newer version of Proton fix the issue?

**Comment by FaeAngst** [comment] 2023-05-01 21:36
I am having this same issue but am completely new to using a steam deck and Linux. Hoe do I go about using a new version of Proton?

**Comment by FaeAngst** [comment] 2023-05-01 23:13
Heya! been having this same problem and have set my vortex to use the latest version of proton-tkg wine. But the download still stays at 0 percent and then close.

**Comment by sonic2kk** [comment] 2023-05-04 23:47
Closing due to lack of response, feel free to re-open if a newer Proton version doesn't solve the issue, ideally with some sort of Wine trace so we can try and figure out the issue :-)

**Closed as completed by sonic2kk** 2023-05-04 23:47 UTC
Labels: Vortex Mod Manager, Upstream
